# Get the list of countries by natural gas proven reserves
def get_the_list_of_countries_by_natural_gas_proven_reserves():
    data = [
        {'country_region': 'Russia', 'us_eia_start_of_2021': '47798', 'opec_start_of_2018': '50,617',
         'bp_start_of_2018': '35000', 'other': '', 'production_in_cubic_km_per_year_in_2020': '624',
         'years_of_production_in_reserve': '77'},
        {'country_region': 'Iran', 'us_eia_start_of_2021': '33980', 'opec_start_of_2018': '33,810',
         'bp_start_of_2018': '33200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '238',
         'years_of_production_in_reserve': '143'},
        {'country_region': 'Qatar', 'us_eia_start_of_2021': '23871', 'opec_start_of_2018': '23,861',
         'bp_start_of_2018': '24900', 'other': '', 'production_in_cubic_km_per_year_in_2020': '167',
         'years_of_production_in_reserve': '143'},
        {'country_region': 'Saudi Arabia', 'us_eia_start_of_2021': '15910', 'opec_start_of_2018': '8,715',
         'bp_start_of_2018': '8000', 'other': '', 'production_in_cubic_km_per_year_in_2020': '114',
         'years_of_production_in_reserve': '140'},
        {'country_region': 'United States', 'us_eia_start_of_2021': '13167', 'opec_start_of_2018': '9,067',
         'bp_start_of_2018': '8700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '947',
         'years_of_production_in_reserve': '14'},
        {'country_region': 'Turkmenistan', 'us_eia_start_of_2021': '11326', 'opec_start_of_2018': '9,838',
         'bp_start_of_2018': '19500', 'other': '', 'production_in_cubic_km_per_year_in_2020': '84',
         'years_of_production_in_reserve': '135'},
        {'country_region': 'China', 'us_eia_start_of_2021': '6654', 'opec_start_of_2018': '2,934',
         'bp_start_of_2018': '5500', 'other': '', 'production_in_cubic_km_per_year_in_2020': '179',
         'years_of_production_in_reserve': '37'},
        {'country_region': 'United Arab Emirates', 'us_eia_start_of_2021': '6088', 'opec_start_of_2018': '6,091',
         'bp_start_of_2018': '5900', 'other': '', 'production_in_cubic_km_per_year_in_2020': '63',
         'years_of_production_in_reserve': '97'},
        {'country_region': 'Nigeria', 'us_eia_start_of_2021': '5748', 'opec_start_of_2018': '5,627',
         'bp_start_of_2018': '5200', 'other': '5932[11]', 'production_in_cubic_km_per_year_in_2020': '46',
         'years_of_production_in_reserve': '125'},
        {'country_region': 'Venezuela', 'us_eia_start_of_2021': '5663', 'opec_start_of_2018': '5,707',
         'bp_start_of_2018': '6400', 'other': '', 'production_in_cubic_km_per_year_in_2020': '23',
         'years_of_production_in_reserve': '246'},
        {'country_region': 'Algeria', 'us_eia_start_of_2021': '4502', 'opec_start_of_2018': '4,504',
         'bp_start_of_2018': '4300', 'other': '', 'production_in_cubic_km_per_year_in_2020': '88',
         'years_of_production_in_reserve': '51'},
        {'country_region': 'Iraq', 'us_eia_start_of_2021': '3738', 'opec_start_of_2018': '3,744',
         'bp_start_of_2018': '3500', 'other': '', 'production_in_cubic_km_per_year_in_2020': '11',
         'years_of_production_in_reserve': '340'},
        {'country_region': 'Australia', 'us_eia_start_of_2021': '3228', 'opec_start_of_2018': '3,173',
         'bp_start_of_2018': '3600', 'other': '', 'production_in_cubic_km_per_year_in_2020': '146',
         'years_of_production_in_reserve': '22'},
        {'country_region': 'Mozambique', 'us_eia_start_of_2021': '2832', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '5',
         'years_of_production_in_reserve': '566'},
        {'country_region': 'Canada', 'us_eia_start_of_2021': '2067', 'opec_start_of_2018': '2,059',
         'bp_start_of_2018': '1900', 'other': '', 'production_in_cubic_km_per_year_in_2020': '179',
         'years_of_production_in_reserve': '12'},
        {'country_region': 'Uzbekistan', 'us_eia_start_of_2021': '1841', 'opec_start_of_2018': '1,564',
         'bp_start_of_2018': '1200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '47',
         'years_of_production_in_reserve': '39'},
        {'country_region': 'Kazakhstan', 'us_eia_start_of_2021': '1840', 'opec_start_of_2018': '1,898',
         'bp_start_of_2018': '1100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '26',
         'years_of_production_in_reserve': '71'},
        {'country_region': 'Egypt', 'us_eia_start_of_2021': '1784', 'opec_start_of_2018': '2,221',
         'bp_start_of_2018': '1800', 'other': '', 'production_in_cubic_km_per_year_in_2020': '77',
         'years_of_production_in_reserve': '23'},
        {'country_region': 'Kuwait', 'us_eia_start_of_2021': '1784', 'opec_start_of_2018': '1,784',
         'bp_start_of_2018': '1700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '20',
         'years_of_production_in_reserve': '89'},
        {'country_region': 'Azerbaijan', 'us_eia_start_of_2021': '1699', 'opec_start_of_2018': '1,227',
         'bp_start_of_2018': '2800', 'other': '', 'production_in_cubic_km_per_year_in_2020': '23',
         'years_of_production_in_reserve': '74'},
        {'country_region': 'Norway', 'us_eia_start_of_2021': '1557', 'opec_start_of_2018': '2,314',
         'bp_start_of_2018': '1700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '112',
         'years_of_production_in_reserve': '14'},
        {'country_region': 'Libya', 'us_eia_start_of_2021': '1501', 'opec_start_of_2018': '1,505',
         'bp_start_of_2018': '1400', 'other': '', 'production_in_cubic_km_per_year_in_2020': '11(2019)',
         'years_of_production_in_reserve': '136'},
        {'country_region': 'Indonesia', 'us_eia_start_of_2021': '1415', 'opec_start_of_2018': '2,866',
         'bp_start_of_2018': '2900', 'other': '', 'production_in_cubic_km_per_year_in_2020': '63',
         'years_of_production_in_reserve': '22'},
        {'country_region': 'India', 'us_eia_start_of_2021': '1388', 'opec_start_of_2018': '1,289',
         'bp_start_of_2018': '1200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '28',
         'years_of_production_in_reserve': '50'},
        {'country_region': 'Malaysia', 'us_eia_start_of_2021': '1189', 'opec_start_of_2018': '2,909',
         'bp_start_of_2018': '2700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '75',
         'years_of_production_in_reserve': '16'},
        {'country_region': 'Ukraine', 'us_eia_start_of_2021': '1104', 'opec_start_of_2018': '304',
         'bp_start_of_2018': '1100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '20',
         'years_of_production_in_reserve': '55'},
        {'country_region': 'Vietnam', 'us_eia_start_of_2021': '708', 'opec_start_of_2018': '203',
         'bp_start_of_2018': '600', 'other': '', 'production_in_cubic_km_per_year_in_2020': '8',
         'years_of_production_in_reserve': '88'},
        {'country_region': 'Oman', 'us_eia_start_of_2021': '651', 'opec_start_of_2018': '884',
         'bp_start_of_2018': '700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '37',
         'years_of_production_in_reserve': '18'},
        {'country_region': 'Myanmar', 'us_eia_start_of_2021': '651', 'opec_start_of_2018': '273',
         'bp_start_of_2018': '1200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '18',
         'years_of_production_in_reserve': '36'},
        {'country_region': 'Pakistan', 'us_eia_start_of_2021': '595', 'opec_start_of_2018': '757',
         'bp_start_of_2018': '400', 'other': '', 'production_in_cubic_km_per_year_in_2020': '38',
         'years_of_production_in_reserve': '16'},
        {'country_region': 'Yemen', 'us_eia_start_of_2021': '481', 'opec_start_of_2018': '', 'bp_start_of_2018': '300',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.09', 'years_of_production_in_reserve': '5344'},
        {'country_region': 'Argentina', 'us_eia_start_of_2021': '396', 'opec_start_of_2018': '381',
         'bp_start_of_2018': '300', 'other': '', 'production_in_cubic_km_per_year_in_2020': '41',
         'years_of_production_in_reserve': '10'},
        {'country_region': 'Brazil', 'us_eia_start_of_2021': '368', 'opec_start_of_2018': '325',
         'bp_start_of_2018': '400', 'other': '', 'production_in_cubic_km_per_year_in_2020': '25',
         'years_of_production_in_reserve': '15'},
        {'country_region': 'Angola', 'us_eia_start_of_2021': '339', 'opec_start_of_2018': '422', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '7', 'years_of_production_in_reserve': '48'},
        {'country_region': 'Peru', 'us_eia_start_of_2021': '311', 'opec_start_of_2018': '513',
         'bp_start_of_2018': '400', 'other': '', 'production_in_cubic_km_per_year_in_2020': '12',
         'years_of_production_in_reserve': '26'},
        {'country_region': 'Trinidad and Tobago', 'us_eia_start_of_2021': '311', 'opec_start_of_2018': '433',
         'bp_start_of_2018': '300', 'other': '', 'production_in_cubic_km_per_year_in_2020': '31',
         'years_of_production_in_reserve': '10'},
        {'country_region': 'Bolivia', 'us_eia_start_of_2021': '311', 'opec_start_of_2018': '310',
         'bp_start_of_2018': '300', 'other': '', 'production_in_cubic_km_per_year_in_2020': '15',
         'years_of_production_in_reserve': '21'},
        {'country_region': 'Congo', 'us_eia_start_of_2021': '283', 'opec_start_of_2018': '111', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1.4', 'years_of_production_in_reserve': '202'},
        {'country_region': 'Brunei', 'us_eia_start_of_2021': '261', 'opec_start_of_2018': '252', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '12', 'years_of_production_in_reserve': '22'},
        {'country_region': 'Syria', 'us_eia_start_of_2021': '241', 'opec_start_of_2018': '300',
         'bp_start_of_2018': '300', 'other': '', 'production_in_cubic_km_per_year_in_2020': '4',
         'years_of_production_in_reserve': '60'},
        {'country_region': 'Papua New Guinea', 'us_eia_start_of_2021': '184', 'opec_start_of_2018': '',
         'bp_start_of_2018': '200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '12',
         'years_of_production_in_reserve': '15'},
        {'country_region': 'Mexico', 'us_eia_start_of_2021': '181', 'opec_start_of_2018': '146',
         'bp_start_of_2018': '200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '27',
         'years_of_production_in_reserve': '7'},
        {'country_region': 'United Kingdom', 'us_eia_start_of_2021': '181', 'opec_start_of_2018': '269',
         'bp_start_of_2018': '200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '40',
         'years_of_production_in_reserve': '5'},
        {'country_region': 'Israel', 'us_eia_start_of_2021': '176', 'opec_start_of_2018': '', 'bp_start_of_2018': '500',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '10', 'years_of_production_in_reserve': '18'},
        {'country_region': 'Thailand', 'us_eia_start_of_2021': '139', 'opec_start_of_2018': '180',
         'bp_start_of_2018': '200', 'other': '', 'production_in_cubic_km_per_year_in_2020': '38',
         'years_of_production_in_reserve': '4'},
        {'country_region': 'Equatorial Guinea', 'us_eia_start_of_2021': '139', 'opec_start_of_2018': '145',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '5',
         'years_of_production_in_reserve': '28'},
        {'country_region': 'Cameroon', 'us_eia_start_of_2021': '135', 'opec_start_of_2018': '152',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '3',
         'years_of_production_in_reserve': '45'},
        {'country_region': 'Netherlands', 'us_eia_start_of_2021': '133', 'opec_start_of_2018': '804',
         'bp_start_of_2018': '700', 'other': '', 'production_in_cubic_km_per_year_in_2020': '33',
         'years_of_production_in_reserve': '4'},
        {'country_region': 'Bangladesh', 'us_eia_start_of_2021': '127', 'opec_start_of_2018': '346',
         'bp_start_of_2018': '200', 'other': '[12] 385', 'production_in_cubic_km_per_year_in_2020': '29',
         'years_of_production_in_reserve': '4'},
        {'country_region': 'Romania', 'us_eia_start_of_2021': '105', 'opec_start_of_2018': '105',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '10',
         'years_of_production_in_reserve': '10'},
        {'country_region': 'Philippines', 'us_eia_start_of_2021': '99', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '4',
         'years_of_production_in_reserve': '25'},
        {'country_region': 'Chile', 'us_eia_start_of_2021': '99', 'opec_start_of_2018': '5.30', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1', 'years_of_production_in_reserve': '99'},
        {'country_region': 'Poland', 'us_eia_start_of_2021': '90', 'opec_start_of_2018': '56.3',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '5.66',
         'years_of_production_in_reserve': '16'},
        {'country_region': 'Colombia', 'us_eia_start_of_2021': '88', 'opec_start_of_2018': '104',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '11',
         'years_of_production_in_reserve': '8'},
        {'country_region': 'Sudan', 'us_eia_start_of_2021': '85', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Bahrain', 'us_eia_start_of_2021': '82', 'opec_start_of_2018': '', 'bp_start_of_2018': '200',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '18', 'years_of_production_in_reserve': '5'},
        {'country_region': 'Cuba', 'us_eia_start_of_2021': '71', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1', 'years_of_production_in_reserve': '71'},
        {'country_region': 'Tunisia', 'us_eia_start_of_2021': '65', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1', 'years_of_production_in_reserve': '65'},
        {'country_region': 'Namibia', 'us_eia_start_of_2021': '62', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Rwanda', 'us_eia_start_of_2021': '57', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Afghanistan', 'us_eia_start_of_2021': '51', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.08',
         'years_of_production_in_reserve': '638'},
        {'country_region': 'Serbia', 'us_eia_start_of_2021': '48', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.45', 'years_of_production_in_reserve': '107'},
        {'country_region': 'Italy', 'us_eia_start_of_2021': '45', 'opec_start_of_2018': '27.1',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '4',
         'years_of_production_in_reserve': '11'},
        {'country_region': 'New Zealand', 'us_eia_start_of_2021': '31', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '5',
         'years_of_production_in_reserve': '6'},
        {'country_region': 'Ivory Coast', 'us_eia_start_of_2021': '28', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '2.44',
         'years_of_production_in_reserve': '11'},
        {'country_region': 'Mauritania', 'us_eia_start_of_2021': '28', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Denmark', 'us_eia_start_of_2021': '28', 'opec_start_of_2018': '73.9',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '1.3',
         'years_of_production_in_reserve': '22'},
        {'country_region': 'Gabon', 'us_eia_start_of_2021': '26', 'opec_start_of_2018': '25.5', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.31', 'years_of_production_in_reserve': '84'},
        {'country_region': 'Croatia', 'us_eia_start_of_2021': '25', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.85', 'years_of_production_in_reserve': '29'},
        {'country_region': 'Ethiopia', 'us_eia_start_of_2021': '25', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Germany', 'us_eia_start_of_2021': '23', 'opec_start_of_2018': '39.6',
         'bp_start_of_2018': '100', 'other': '', 'production_in_cubic_km_per_year_in_2020': '5',
         'years_of_production_in_reserve': '5'},
        {'country_region': 'Ghana', 'us_eia_start_of_2021': '23', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1.56', 'years_of_production_in_reserve': '15'},
        {'country_region': 'Japan', 'us_eia_start_of_2021': '20', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1.93', 'years_of_production_in_reserve': '10'},
        {'country_region': 'Moldova', 'us_eia_start_of_2021': '-', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '[13] 20', 'production_in_cubic_km_per_year_in_2020': '0.006',
         'years_of_production_in_reserve': '3333'},
        {'country_region': 'Slovakia', 'us_eia_start_of_2021': '14', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.06', 'years_of_production_in_reserve': '233'},
        {'country_region': 'Uganda', 'us_eia_start_of_2021': '14', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Ecuador', 'us_eia_start_of_2021': '11', 'opec_start_of_2018': '5.4', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.34', 'years_of_production_in_reserve': '32'},
        {'country_region': 'Ireland', 'us_eia_start_of_2021': '11', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '2.66', 'years_of_production_in_reserve': '4'},
        {'country_region': 'Georgia', 'us_eia_start_of_2021': '8.5+16 [14]', 'opec_start_of_2018': '8.5',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '',
         'years_of_production_in_reserve': '0.02'},
        {'country_region': 'South Korea', 'us_eia_start_of_2021': '8.5', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.24',
         'years_of_production_in_reserve': '35'},
        {'country_region': 'Austria', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.93', 'years_of_production_in_reserve': '6'},
        {'country_region': 'Tanzania', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1.39', 'years_of_production_in_reserve': '4'},
        {'country_region': 'Taiwan', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.15', 'years_of_production_in_reserve': '38'},
        {'country_region': 'Jordan', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.12', 'years_of_production_in_reserve': '47'},
        {'country_region': 'Bulgaria', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.06', 'years_of_production_in_reserve': '94'},
        {'country_region': 'Somalia', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Tajikistan', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.02',
         'years_of_production_in_reserve': '283'},
        {'country_region': 'Kyrgyzstan', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.03',
         'years_of_production_in_reserve': '189'},
        {'country_region': 'Albania', 'us_eia_start_of_2021': '5.66', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.04', 'years_of_production_in_reserve': '142'},
        {'country_region': 'South Africa', 'us_eia_start_of_2021': '-', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '[15] 3', 'production_in_cubic_km_per_year_in_2020': '1.22',
         'years_of_production_in_reserve': '2'},
        {'country_region': 'Turkey', 'us_eia_start_of_2021': '2.83', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '300TPAO estimate', 'production_in_cubic_km_per_year_in_2020': '0.48',
         'years_of_production_in_reserve': '6'},
        {'country_region': 'Czech Republic', 'us_eia_start_of_2021': '2.83', 'opec_start_of_2018': '',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.19',
         'years_of_production_in_reserve': '15'},
        {'country_region': 'Belarus', 'us_eia_start_of_2021': '2.83', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '2.4', 'years_of_production_in_reserve': '1.2'},
        {'country_region': 'Hungary', 'us_eia_start_of_2021': '2.8', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '1.7', 'years_of_production_in_reserve': '1.6'},
        {'country_region': 'Spain', 'us_eia_start_of_2021': '2.55', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.06', 'years_of_production_in_reserve': '42'},
        {'country_region': 'Morocco', 'us_eia_start_of_2021': '1.44', 'opec_start_of_2018': '474',
         'bp_start_of_2018': '', 'other': '', 'production_in_cubic_km_per_year_in_2020': '0.1',
         'years_of_production_in_reserve': '14'},
        {'country_region': 'Benin', 'us_eia_start_of_2021': '1.13', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'DR Congo', 'us_eia_start_of_2021': '0.99', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
        {'country_region': 'Greece', 'us_eia_start_of_2021': '0.99', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.01', 'years_of_production_in_reserve': '99'},
        {'country_region': 'Barbados', 'us_eia_start_of_2021': '0.11', 'opec_start_of_2018': '', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0.02', 'years_of_production_in_reserve': '6'},
        {'country_region': 'Armenia', 'us_eia_start_of_2021': '0', 'opec_start_of_2018': '18.0', 'bp_start_of_2018': '',
         'other': '', 'production_in_cubic_km_per_year_in_2020': '0', 'years_of_production_in_reserve': '-'},
    ]

    return data


# Get the list of countries by natural gas consumption
def get_the_list_of_countries_by_natural_gas_consumption():
    data = [
        {'country_region': 'World', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3929000',
         'date_of_information': '2019'},
        {'country_region': 'United States', 'natural_gas_consumption_in_million_cubic_meter_per_year': '846600',
         'date_of_information': '2019'},
        {'country_region': 'European Union', 'natural_gas_consumption_in_million_cubic_meter_per_year': '469600',
         'date_of_information': '2019'},
        {'country_region': 'Russia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '444300',
         'date_of_information': '2019'},
        {'country_region': 'China', 'natural_gas_consumption_in_million_cubic_meter_per_year': '307300',
         'date_of_information': '2019'},
        {'country_region': 'Iran', 'natural_gas_consumption_in_million_cubic_meter_per_year': '223600',
         'date_of_information': '2019'},
        {'country_region': 'ASEAN', 'natural_gas_consumption_in_million_cubic_meter_per_year': '165900',
         'date_of_information': '2019'},
        {'country_region': 'Canada', 'natural_gas_consumption_in_million_cubic_meter_per_year': '120300',
         'date_of_information': '2019'},
        {'country_region': 'Saudi Arabia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '113600',
         'date_of_information': '2019'},
        {'country_region': 'Japan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '108100',
         'date_of_information': '2019'},
        {'country_region': 'Mexico', 'natural_gas_consumption_in_million_cubic_meter_per_year': '90700',
         'date_of_information': '2019'},
        {'country_region': 'Germany', 'natural_gas_consumption_in_million_cubic_meter_per_year': '88700',
         'date_of_information': '2019'},
        {'country_region': 'United Kingdom', 'natural_gas_consumption_in_million_cubic_meter_per_year': '78800',
         'date_of_information': '2019'},
        {'country_region': 'United Arab Emirates', 'natural_gas_consumption_in_million_cubic_meter_per_year': '72200',
         'date_of_information': '2017'},
        {'country_region': 'Italy', 'natural_gas_consumption_in_million_cubic_meter_per_year': '72100',
         'date_of_information': '2017'},
        {'country_region': 'Egypt', 'natural_gas_consumption_in_million_cubic_meter_per_year': '58900',
         'date_of_information': '2020'},
        {'country_region': 'India', 'natural_gas_consumption_in_million_cubic_meter_per_year': '54200',
         'date_of_information': '2017'},
        {'country_region': 'Turkey', 'natural_gas_consumption_in_million_cubic_meter_per_year': '51700',
         'date_of_information': '2017'},
        {'country_region': 'Thailand', 'natural_gas_consumption_in_million_cubic_meter_per_year': '50100',
         'date_of_information': '2017'},
        {'country_region': 'South Korea', 'natural_gas_consumption_in_million_cubic_meter_per_year': '49400',
         'date_of_information': '2017'},
        {'country_region': 'Argentina', 'natural_gas_consumption_in_million_cubic_meter_per_year': '48500',
         'date_of_information': '2017'},
        {'country_region': 'Qatar', 'natural_gas_consumption_in_million_cubic_meter_per_year': '47400',
         'date_of_information': '2017'},
        {'country_region': 'France', 'natural_gas_consumption_in_million_cubic_meter_per_year': '44700',
         'date_of_information': '2017'},
        {'country_region': 'Malaysia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '42800',
         'date_of_information': '2017'},
        {'country_region': 'Australia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '41900',
         'date_of_information': '2017'},
        {'country_region': 'Uzbekistan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '41600',
         'date_of_information': '2017'},
        {'country_region': 'Pakistan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '40700',
         'date_of_information': '2017'},
        {'country_region': 'Indonesia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '39200',
         'date_of_information': '2017'},
        {'country_region': 'Algeria', 'natural_gas_consumption_in_million_cubic_meter_per_year': '38900',
         'date_of_information': '2017'},
        {'country_region': 'Brazil', 'natural_gas_consumption_in_million_cubic_meter_per_year': '38300',
         'date_of_information': '2017'},
        {'country_region': 'Venezuela', 'natural_gas_consumption_in_million_cubic_meter_per_year': '37600',
         'date_of_information': '2017'},
        {'country_region': 'Netherlands', 'natural_gas_consumption_in_million_cubic_meter_per_year': '36100',
         'date_of_information': '2017'},
        {'country_region': 'Bangladesh', 'natural_gas_consumption_in_million_cubic_meter_per_year': '34400',
         'date_of_information': '2019'},
        {'country_region': 'Spain', 'natural_gas_consumption_in_million_cubic_meter_per_year': '32000',
         'date_of_information': '2017'},
        {'country_region': 'Turkmenistan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '31500',
         'date_of_information': '2019'},
        {'country_region': 'Ukraine', 'natural_gas_consumption_in_million_cubic_meter_per_year': '29800',
         'date_of_information': '2017'},
        {'country_region': 'Oman', 'natural_gas_consumption_in_million_cubic_meter_per_year': '25000',
         'date_of_information': '2019'},
        {'country_region': 'Kuwait', 'natural_gas_consumption_in_million_cubic_meter_per_year': '23500',
         'date_of_information': '2019'},
        {'country_region': 'Taiwan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '23300',
         'date_of_information': '2019'},
        {'country_region': 'Poland', 'natural_gas_consumption_in_million_cubic_meter_per_year': '20400',
         'date_of_information': '2019'},
        {'country_region': 'Iraq', 'natural_gas_consumption_in_million_cubic_meter_per_year': '19900',
         'date_of_information': '2019'},
        {'country_region': 'Belarus', 'natural_gas_consumption_in_million_cubic_meter_per_year': '19300',
         'date_of_information': '2019'},
        {'country_region': 'Nigeria', 'natural_gas_consumption_in_million_cubic_meter_per_year': '18820',
         'date_of_information': '2015'},
        {'country_region': 'Trinidad and Tobago', 'natural_gas_consumption_in_million_cubic_meter_per_year': '17500',
         'date_of_information': '2019'},
        {'country_region': 'Belgium', 'natural_gas_consumption_in_million_cubic_meter_per_year': '17400',
         'date_of_information': '2019'},
        {'country_region': 'Kazakhstan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '16300',
         'date_of_information': '2017'},
        {'country_region': 'Bahrain', 'natural_gas_consumption_in_million_cubic_meter_per_year': '15500',
         'date_of_information': '2015'},
        {'country_region': 'Colombia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '13400',
         'date_of_information': '2019'},
        {'country_region': 'Singapore', 'natural_gas_consumption_in_million_cubic_meter_per_year': '12700',
         'date_of_information': '2019'},
        {'country_region': 'Azerbaijan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '11800',
         'date_of_information': '2019'},
        {'country_region': 'Romania', 'natural_gas_consumption_in_million_cubic_meter_per_year': '10900',
         'date_of_information': '2019'},
        {'country_region': 'Israel', 'natural_gas_consumption_in_million_cubic_meter_per_year': '10800',
         'date_of_information': '2019'},
        {'country_region': 'Vietnam', 'natural_gas_consumption_in_million_cubic_meter_per_year': '9900',
         'date_of_information': '2019'},
        {'country_region': 'Hungary', 'natural_gas_consumption_in_million_cubic_meter_per_year': '9800',
         'date_of_information': '2019'},
        {'country_region': 'Austria', 'natural_gas_consumption_in_million_cubic_meter_per_year': '8900',
         'date_of_information': '2019'},
        {'country_region': 'Czech Republic', 'natural_gas_consumption_in_million_cubic_meter_per_year': '8300',
         'date_of_information': '2019'},
        {'country_region': 'Peru', 'natural_gas_consumption_in_million_cubic_meter_per_year': '8300',
         'date_of_information': '2019'},
        {'country_region': 'Chile', 'natural_gas_consumption_in_million_cubic_meter_per_year': '6500',
         'date_of_information': '2019'},
        {'country_region': 'Slovakia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '6216',
         'date_of_information': '2007'},
        {'country_region': 'Portugal', 'natural_gas_consumption_in_million_cubic_meter_per_year': '6100',
         'date_of_information': '2019'},
        {'country_region': 'Greece', 'natural_gas_consumption_in_million_cubic_meter_per_year': '5100',
         'date_of_information': '2019'},
        {'country_region': 'New Zealand', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4800',
         'date_of_information': '2019'},
        {'country_region': 'Denmark', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4555',
         'date_of_information': '2007'},
        {'country_region': 'Norway', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4500',
         'date_of_information': '2019'},
        {'country_region': 'Libya', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4490',
         'date_of_information': '2015'},
        {'country_region': 'Ireland', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4354',
         'date_of_information': '2015'},
        {'country_region': 'Syria', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4300',
         'date_of_information': '2015'},
        {'country_region': 'South Africa', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4300',
         'date_of_information': '2019'},
        {'country_region': 'Philippines', 'natural_gas_consumption_in_million_cubic_meter_per_year': '4100',
         'date_of_information': '2019'},
        {'country_region': 'Tunisia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3850',
         'date_of_information': '2006'},
        {'country_region': 'Myanmar', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3620',
         'date_of_information': '2006'},
        {'country_region': 'Bulgaria', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3500',
         'date_of_information': '2007'},
        {'country_region': 'Brunei', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3480',
         'date_of_information': '2015'},
        {'country_region': 'Lithuania', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3440',
         'date_of_information': '2007'},
        {'country_region': 'Switzerland', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3400',
         'date_of_information': '2019'},
        {'country_region': 'Croatia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3300',
         'date_of_information': '2007'},
        {'country_region': 'Hong Kong', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3100',
         'date_of_information': '2019'},
        {'country_region': 'Bolivia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '3000',
         'date_of_information': '2007'},
        {'country_region': 'Jordan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2897',
         'date_of_information': '2015'},
        {'country_region': 'Moldova', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2440',
         'date_of_information': '2007'},
        {'country_region': 'Serbia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2180',
         'date_of_information': '2015'},
        {'country_region': 'Armenia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2050',
         'date_of_information': '2015'},
        {'country_region': 'Latvia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2040',
         'date_of_information': '2007'},
        {'country_region': 'Finland', 'natural_gas_consumption_in_million_cubic_meter_per_year': '2000',
         'date_of_information': '2019'},
        {'country_region': 'Mozambique', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1895',
         'date_of_information': '2015'},
        {'country_region': 'Georgia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1490',
         'date_of_information': '2007'},
        {'country_region': 'Luxembourg', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1329',
         'date_of_information': '2007'},
        {'country_region': 'Equatorial Guinea', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1300',
         'date_of_information': '2006'},
        {'country_region': "Côte d'Ivoire", 'natural_gas_consumption_in_million_cubic_meter_per_year': '1300',
         'date_of_information': '2006'},
        {'country_region': 'Cuba', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1185',
         'date_of_information': '2016'},
        {'country_region': 'Sweden', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1000',
         'date_of_information': '2019'},
        {'country_region': 'Morocco', 'natural_gas_consumption_in_million_cubic_meter_per_year': '1000',
         'date_of_information': '2019'},
        {'country_region': 'Kyrgyzstan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '768',
         'date_of_information': '2007'},
        {'country_region': 'Slovenia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '743',
         'date_of_information': '2017'},
        {'country_region': 'Puerto Rico', 'natural_gas_consumption_in_million_cubic_meter_per_year': '736.2',
         'date_of_information': '2007'},
        {'country_region': 'Angola', 'natural_gas_consumption_in_million_cubic_meter_per_year': '680',
         'date_of_information': '2006'},
        {'country_region': 'Cameroon', 'natural_gas_consumption_in_million_cubic_meter_per_year': '680',
         'date_of_information': '2015'},
        {'country_region': 'Ecuador', 'natural_gas_consumption_in_million_cubic_meter_per_year': '600',
         'date_of_information': '2019'},
        {'country_region': 'Estonia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '525',
         'date_of_information': '2016'},
        {'country_region': 'Gabon', 'natural_gas_consumption_in_million_cubic_meter_per_year': '378',
         'date_of_information': '2015'},
        {'country_region': 'Dominican Republic', 'natural_gas_consumption_in_million_cubic_meter_per_year': '250',
         'date_of_information': '2006'},
        {'country_region': 'Bosnia and Herzegovina', 'natural_gas_consumption_in_million_cubic_meter_per_year': '200',
         'date_of_information': '2015'},
        {'country_region': 'Republic of the Congo', 'natural_gas_consumption_in_million_cubic_meter_per_year': '180',
         'date_of_information': '2006'},
        {'country_region': 'Afghanistan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '146.6',
         'date_of_information': '2015'},
        {'country_region': 'Tanzania', 'natural_gas_consumption_in_million_cubic_meter_per_year': '146',
         'date_of_information': '2006'},
        {'country_region': 'Papua New Guinea', 'natural_gas_consumption_in_million_cubic_meter_per_year': '100',
         'date_of_information': '2015'},
        {'country_region': 'North Macedonia', 'natural_gas_consumption_in_million_cubic_meter_per_year': '60',
         'date_of_information': '2015'},
        {'country_region': 'Senegal', 'natural_gas_consumption_in_million_cubic_meter_per_year': '60',
         'date_of_information': '2015'},
        {'country_region': 'Uruguay', 'natural_gas_consumption_in_million_cubic_meter_per_year': '40',
         'date_of_information': '2015'},
        {'country_region': 'Albania', 'natural_gas_consumption_in_million_cubic_meter_per_year': '35',
         'date_of_information': '2015'},
        {'country_region': 'Tajikistan', 'natural_gas_consumption_in_million_cubic_meter_per_year': '20',
         'date_of_information': '2015'},
        {'country_region': 'Barbados', 'natural_gas_consumption_in_million_cubic_meter_per_year': '12.7',
         'date_of_information': '2015'},
        {'country_region': 'Macau', 'natural_gas_consumption_in_million_cubic_meter_per_year': '0.4',
         'date_of_information': '2013'}
    ]

    return data


# Get the list of countries by natural gas production
def get_the_list_of_countries_by_natural_gas_production():
    data = [
        {'rank': '1', 'country_region': 'United States', 'continent': 'North America',
         'annual_ng_production_in_million_cubic_meter': 'North America', 'date_of_information': '831,800'},
        {'rank': '2', 'country_region': 'Russia', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '669,500'},
        {'rank': '3', 'country_region': 'Qatar', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '239,500'},
        {'rank': '4', 'country_region': 'Canada', 'continent': 'North America',
         'annual_ng_production_in_million_cubic_meter': 'North America', 'date_of_information': '184,700'},
        {'rank': '5', 'country_region': 'United Arab Emirates', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '175,500'},
        {'rank': '6', 'country_region': 'China', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '161,500'},
        {'rank': '7', 'country_region': 'Australia', 'continent': 'Oceania',
         'annual_ng_production_in_million_cubic_meter': 'Oceania', 'date_of_information': '130,100'},
        {'rank': '8', 'country_region': 'Norway', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '120,700'},
        {'rank': '—', 'country_region': 'European Union', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '118,200'},
        {'rank': '9', 'country_region': 'Saudi Arabia', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '112,100'},
        {'rank': '10', 'country_region': 'Algeria', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '92,300'},
        {'rank': '11', 'country_region': 'Indonesia', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '73,200'},
        {'rank': '12', 'country_region': 'Malaysia', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '72,500'},
        {'rank': '13', 'country_region': 'Turkmenistan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '61,500'},
        {'rank': '14', 'country_region': 'Iran', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '60,180'},
        {'rank': '15', 'country_region': 'Uzbekistan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '56,600'},
        {'rank': '16', 'country_region': 'Nigeria', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '49,200'},
        {'rank': '17', 'country_region': 'Netherlands', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '47,460'},
        {'rank': '18', 'country_region': 'Trinidad and Tobago', 'continent': 'Caribbean',
         'annual_ng_production_in_million_cubic_meter': 'Caribbean', 'date_of_information': '40,870'},
        {'rank': '19', 'country_region': 'United Kingdom', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '40,600'},
        {'rank': '20', 'country_region': 'Mexico', 'continent': 'North America',
         'annual_ng_production_in_million_cubic_meter': 'North America', 'date_of_information': '40,370'},
        {'rank': '21', 'country_region': 'Argentina', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '39,400'},
        {'rank': '22', 'country_region': 'Pakistan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '39,300'},
        {'rank': '23', 'country_region': 'Thailand', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '37,700'},
        {'rank': '24', 'country_region': 'Oman', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '29,930'},
        {'rank': '25', 'country_region': 'Azerbaijan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '29,370'},
        {'rank': '26', 'country_region': 'India', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '26,210'},
        {'rank': '27', 'country_region': 'Bangladesh', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '26,100'},
        {'rank': '28', 'country_region': 'Venezuela', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '26,000'},
        {'rank': '29', 'country_region': 'Kazakhstan', 'continent': 'Eurasia',
         'annual_ng_production_in_million_cubic_meter': 'Eurasia', 'date_of_information': '22,890'},
        {'rank': '30', 'country_region': 'Bahrain', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '21,070'},
        {'rank': '31', 'country_region': 'Bolivia', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '20,510'},
        {'rank': '32', 'country_region': 'Brazil', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '20,410'},
        {'rank': '33', 'country_region': 'Ukraine', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '19,000'},
        {'rank': '34', 'country_region': 'Myanmar', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '17,500'},
        {'rank': '35', 'country_region': 'Kuwait', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '16,910'},
        {'rank': '36', 'country_region': 'Peru', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '12,620'},
        {'rank': '37', 'country_region': 'Brunei', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '12,000'},
        {'rank': '38', 'country_region': 'Libya', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '11,600'},
        {'rank': '39', 'country_region': 'Romania', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '11,170'},
        {'rank': '40', 'country_region': 'Colombia', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '9,897'},
        {'rank': '41', 'country_region': 'Vietnam', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '9,890'},
        {'rank': '42', 'country_region': 'Papua New Guinea', 'continent': 'Oceania',
         'annual_ng_production_in_million_cubic_meter': 'Oceania', 'date_of_information': '9,800'},
        {'rank': '43', 'country_region': 'Germany', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '8,730'},
        {'rank': '44', 'country_region': 'Israel', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '8,500'},
        {'rank': '45', 'country_region': 'Timor-Leste', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '7,700'},
        {'rank': '46', 'country_region': 'Equatorial Guinea', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '6,200'},
        {'rank': '47', 'country_region': 'Poland', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '6,132'},
        {'rank': '48', 'country_region': 'Italy', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '5,785'},
        {'rank': '49', 'country_region': 'Mozambique', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '5,695'},
        {'rank': '50', 'country_region': 'New Zealand', 'continent': 'Oceania',
         'annual_ng_production_in_million_cubic_meter': 'Oceania', 'date_of_information': '4,954'},
        {'rank': '51', 'country_region': 'Denmark', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '4,618'},
        {'rank': '52', 'country_region': 'Japan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '4,453'},
        {'rank': '53', 'country_region': 'Syria', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '4,300'},
        {'rank': '54', 'country_region': 'Philippines', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '3,942'},
        {'rank': '55', 'country_region': 'Egypt', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '3,610'},
        {'rank': '56', 'country_region': 'Yemen', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '2,850'},
        {'rank': '57', 'country_region': "Cote d'Ivoire", 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '2,063'},
        {'rank': '58', 'country_region': 'Hungary', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '1,772'},
        {'rank': '59', 'country_region': 'Croatia', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '1,691'},
        {'rank': '60', 'country_region': 'Tunisia', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '1,575'},
        {'rank': '61', 'country_region': 'Congo, Republic of the', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '1,500'},
        {'rank': '62', 'country_region': 'Cuba', 'continent': 'Caribbean',
         'annual_ng_production_in_million_cubic_meter': 'Caribbean', 'date_of_information': '1,185'},
        {'rank': '63', 'country_region': 'Austria', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '1,124'},
        {'rank': '64', 'country_region': 'South Africa', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '1,100'},
        {'rank': '65', 'country_region': 'Tanzania', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '1,100'},
        {'rank': '66', 'country_region': 'Chile', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '1,008'},
        {'rank': '67', 'country_region': 'Iraq', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '1,002'},
        {'rank': '68', 'country_region': 'Angola', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '773'},
        {'rank': '69', 'country_region': 'Cameroon', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '680'},
        {'rank': '70', 'country_region': 'Serbia', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '586'},
        {'rank': '71', 'country_region': 'Ghana', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '554'},
        {'rank': '72', 'country_region': 'Ecuador', 'continent': 'South America',
         'annual_ng_production_in_million_cubic_meter': 'South America', 'date_of_information': '497'},
        {'rank': '73', 'country_region': 'Turkey', 'continent': 'Eurasia',
         'annual_ng_production_in_million_cubic_meter': 'Eurasia', 'date_of_information': '381'},
        {'rank': '74', 'country_region': 'Gabon', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '378'},
        {'rank': '75', 'country_region': 'Taiwan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '340'},
        {'rank': '76', 'country_region': 'Czech Republic', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '247'},
        {'rank': '77', 'country_region': 'South Korea', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '188'},
        {'rank': '78', 'country_region': 'Afghanistan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '165'},
        {'rank': '79', 'country_region': 'Jordan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '151'},
        {'rank': '80', 'country_region': 'Ireland', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '132'},
        {'rank': '81', 'country_region': 'Morocco', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '94'},
        {'rank': '82', 'country_region': 'Slovakia', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '94'},
        {'rank': '83', 'country_region': 'Bulgaria', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '79'},
        {'rank': '84', 'country_region': 'Spain', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '62'},
        {'rank': '85', 'country_region': 'Senegal', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '62'},
        {'rank': '86', 'country_region': 'Albania', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '35'},
        {'rank': '87', 'country_region': 'Kyrgyzstan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '30'},
        {'rank': '88', 'country_region': 'Belarus', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '30'},
        {'rank': '89', 'country_region': 'France', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '28'},
        {'rank': '90', 'country_region': 'Switzerland', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '25'},
        {'rank': '91', 'country_region': 'Tajikistan', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '20'},
        {'rank': '92', 'country_region': 'Barbados', 'continent': 'Caribbean',
         'annual_ng_production_in_million_cubic_meter': 'Caribbean', 'date_of_information': '17'},
        {'rank': '93', 'country_region': 'Georgia', 'continent': 'Asia',
         'annual_ng_production_in_million_cubic_meter': 'Asia', 'date_of_information': '10'},
        {'rank': '94', 'country_region': 'Congo, Democratic Republic of the', 'continent': 'Africa',
         'annual_ng_production_in_million_cubic_meter': 'Africa', 'date_of_information': '8'},
        {'rank': '95', 'country_region': 'Finland', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '8'},
        {'rank': '96', 'country_region': 'Luxembourg', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '6'},
        {'rank': '97', 'country_region': 'Greece', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '4'},
        {'rank': '98', 'country_region': 'Slovenia', 'continent': 'Europe',
         'annual_ng_production_in_million_cubic_meter': 'Europe', 'date_of_information': '4'},
    ]

    return data


# Get the list of countries by natural gas imports
def get_the_list_of_countries_by_natural_gas_imports():
    data = [
        {'country_region': 'World', 'natural_gas_for_imports_in_cubic_meter_per_year': '957600000000',
         'date_of_information': '2007'},
        {'country_region': 'European Union', 'natural_gas_for_imports_in_cubic_meter_per_year': '420600000000',
         'date_of_information': '2010'},
        {'country_region': 'Japan', 'natural_gas_for_imports_in_cubic_meter_per_year': '99774000000',
         'date_of_information': '2018'},
        {'country_region': 'Germany', 'natural_gas_for_imports_in_cubic_meter_per_year': '155493000000',
         'date_of_information': '2020'},
        {'country_region': 'Italy', 'natural_gas_for_imports_in_cubic_meter_per_year': '70200000000',
         'date_of_information': '2011'},
        {'country_region': 'United Kingdom', 'natural_gas_for_imports_in_cubic_meter_per_year': '53630000000',
         'date_of_information': '2010'},
        {'country_region': 'Korea, South', 'natural_gas_for_imports_in_cubic_meter_per_year': '51888000000',
         'date_of_information': '2018'},
        {'country_region': 'France', 'natural_gas_for_imports_in_cubic_meter_per_year': '46200000000',
         'date_of_information': '2010'},
        {'country_region': 'United States', 'natural_gas_for_imports_in_cubic_meter_per_year': '45000000000',
         'date_of_information': '2012'},
        {'country_region': 'Russia', 'natural_gas_for_imports_in_cubic_meter_per_year': '38200000000',
         'date_of_information': '2010'},
        {'country_region': 'Turkey', 'natural_gas_for_imports_in_cubic_meter_per_year': '38040000000',
         'date_of_information': '2010'},
        {'country_region': 'Spain', 'natural_gas_for_imports_in_cubic_meter_per_year': '36710000000',
         'date_of_information': '2010'},
        {'country_region': 'China', 'natural_gas_for_imports_in_cubic_meter_per_year': '52578000000',
         'date_of_information': '2018[1]'},
        {'country_region': 'Ukraine', 'natural_gas_for_imports_in_cubic_meter_per_year': '26700000000',
         'date_of_information': '2009'},
        {'country_region': 'India', 'natural_gas_for_imports_in_cubic_meter_per_year': '26400000000',
         'date_of_information': '2017[2]'},
        {'country_region': 'Netherlands', 'natural_gas_for_imports_in_cubic_meter_per_year': '25770000000',
         'date_of_information': '2010'},
        {'country_region': 'Canada', 'natural_gas_for_imports_in_cubic_meter_per_year': '22530000000',
         'date_of_information': '2010'},
        {'country_region': 'Belgium', 'natural_gas_for_imports_in_cubic_meter_per_year': '19320000000',
         'date_of_information': '2010'},
        {'country_region': 'Belarus', 'natural_gas_for_imports_in_cubic_meter_per_year': '17600000000',
         'date_of_information': '2009'},
        {'country_region': 'United Arab Emirates', 'natural_gas_for_imports_in_cubic_meter_per_year': '17250000000',
         'date_of_information': '2009'},
        {'country_region': 'Mexico', 'natural_gas_for_imports_in_cubic_meter_per_year': '14590000000',
         'date_of_information': '2010'},
        {'country_region': 'Brazil', 'natural_gas_for_imports_in_cubic_meter_per_year': '12480000000',
         'date_of_information': '2011'},
        {'country_region': 'Austria', 'natural_gas_for_imports_in_cubic_meter_per_year': '12130000000',
         'date_of_information': '2010'},
        {'country_region': 'Taiwan', 'natural_gas_for_imports_in_cubic_meter_per_year': '11790000000',
         'date_of_information': '2009'},
        {'country_region': 'Poland', 'natural_gas_for_imports_in_cubic_meter_per_year': '10890000000',
         'date_of_information': '2010'},
        {'country_region': 'Hungary', 'natural_gas_for_imports_in_cubic_meter_per_year': '9636000000',
         'date_of_information': '2010'},
        {'country_region': 'Czech Republic', 'natural_gas_for_imports_in_cubic_meter_per_year': '9320000000',
         'date_of_information': '2011'},
        {'country_region': 'Singapore', 'natural_gas_for_imports_in_cubic_meter_per_year': '8400000000',
         'date_of_information': '2010'},
        {'country_region': 'Thailand', 'natural_gas_for_imports_in_cubic_meter_per_year': '8290000000',
         'date_of_information': '2009'},
        {'country_region': 'Iran', 'natural_gas_for_imports_in_cubic_meter_per_year': '6900000000',
         'date_of_information': '2010'},
        {'country_region': 'Australia', 'natural_gas_for_imports_in_cubic_meter_per_year': '5990000000',
         'date_of_information': '2010'},
        {'country_region': 'Slovakia', 'natural_gas_for_imports_in_cubic_meter_per_year': '5586000000',
         'date_of_information': '2011'},
        {'country_region': 'Ireland', 'natural_gas_for_imports_in_cubic_meter_per_year': '5293000000',
         'date_of_information': '2010'},
        {'country_region': 'Portugal', 'natural_gas_for_imports_in_cubic_meter_per_year': '5122000000',
         'date_of_information': '2010'},
        {'country_region': 'Finland', 'natural_gas_for_imports_in_cubic_meter_per_year': '4782000000',
         'date_of_information': '2010'},
        {'country_region': 'Greece', 'natural_gas_for_imports_in_cubic_meter_per_year': '3815000000',
         'date_of_information': '2010'},
        {'country_region': 'Argentina', 'natural_gas_for_imports_in_cubic_meter_per_year': '3780000000',
         'date_of_information': '2010'},
        {'country_region': 'Kazakhstan', 'natural_gas_for_imports_in_cubic_meter_per_year': '3700000000',
         'date_of_information': '2011'},
        {'country_region': 'Switzerland', 'natural_gas_for_imports_in_cubic_meter_per_year': '3625000000',
         'date_of_information': '2010'},
        {'country_region': 'South Africa', 'natural_gas_for_imports_in_cubic_meter_per_year': '3500000000',
         'date_of_information': '2009'},
        {'country_region': 'Hong Kong', 'natural_gas_for_imports_in_cubic_meter_per_year': '3460000000',
         'date_of_information': '2011'},
        {'country_region': 'Lithuania', 'natural_gas_for_imports_in_cubic_meter_per_year': '3120000000',
         'date_of_information': '2010'},
        {'country_region': 'Jordan', 'natural_gas_for_imports_in_cubic_meter_per_year': '2850000000',
         'date_of_information': '2009'},
        {'country_region': 'Bulgaria', 'natural_gas_for_imports_in_cubic_meter_per_year': '2480000000',
         'date_of_information': '2010'},
        {'country_region': 'Moldova', 'natural_gas_for_imports_in_cubic_meter_per_year': '2330000000',
         'date_of_information': '2009'},
        {'country_region': 'Romania', 'natural_gas_for_imports_in_cubic_meter_per_year': '2290000000',
         'date_of_information': '2010'},
        {'country_region': 'Venezuela', 'natural_gas_for_imports_in_cubic_meter_per_year': '2180000000',
         'date_of_information': '2010'},
        {'country_region': 'Serbia', 'natural_gas_for_imports_in_cubic_meter_per_year': '2150000000',
         'date_of_information': '2011'},
        {'country_region': 'Armenia', 'natural_gas_for_imports_in_cubic_meter_per_year': '2077000000',
         'date_of_information': '2011'},
        {'country_region': 'Georgia', 'natural_gas_for_imports_in_cubic_meter_per_year': '1740000000',
         'date_of_information': '2011'},
        {'country_region': 'Israel', 'natural_gas_for_imports_in_cubic_meter_per_year': '1700000000',
         'date_of_information': '2009'},
        {'country_region': 'Sweden', 'natural_gas_for_imports_in_cubic_meter_per_year': '1626000000',
         'date_of_information': '2010'},
        {'country_region': 'Oman', 'natural_gas_for_imports_in_cubic_meter_per_year': '1500000000',
         'date_of_information': '2009'},
        {'country_region': 'Chile', 'natural_gas_for_imports_in_cubic_meter_per_year': '1490000000',
         'date_of_information': '2009'},
        {'country_region': 'Luxembourg', 'natural_gas_for_imports_in_cubic_meter_per_year': '1366000000',
         'date_of_information': '2010'},
        {'country_region': 'Malaysia', 'natural_gas_for_imports_in_cubic_meter_per_year': '1269000000',
         'date_of_information': '2009'},
        {'country_region': 'Tunisia', 'natural_gas_for_imports_in_cubic_meter_per_year': '1250000000',
         'date_of_information': '2009'},
        {'country_region': 'Latvia', 'natural_gas_for_imports_in_cubic_meter_per_year': '1125000000',
         'date_of_information': '2010'},
        {'country_region': 'Vietnam', 'natural_gas_for_imports_in_cubic_meter_per_year': '1000000000',
         'date_of_information': '2011'},
        {'country_region': 'Croatia', 'natural_gas_for_imports_in_cubic_meter_per_year': '971200000',
         'date_of_information': '2010'},
        {'country_region': 'Syria', 'natural_gas_for_imports_in_cubic_meter_per_year': '910000000',
         'date_of_information': '2009'},
        {'country_region': 'Kuwait', 'natural_gas_for_imports_in_cubic_meter_per_year': '890000000',
         'date_of_information': '2009'},
        {'country_region': 'Slovenia', 'natural_gas_for_imports_in_cubic_meter_per_year': '890000000',
         'date_of_information': '2009'},
        {'country_region': 'Puerto Rico', 'natural_gas_for_imports_in_cubic_meter_per_year': '756700000',
         'date_of_information': '2009'},
        {'country_region': 'Estonia', 'natural_gas_for_imports_in_cubic_meter_per_year': '701000000',
         'date_of_information': '2010'},
        {'country_region': 'Kyrgyzstan', 'natural_gas_for_imports_in_cubic_meter_per_year': '640000000',
         'date_of_information': '2009'},
        {'country_region': 'Dominican Republic', 'natural_gas_for_imports_in_cubic_meter_per_year': '560000000',
         'date_of_information': '2009'},
        {'country_region': 'Morocco', 'natural_gas_for_imports_in_cubic_meter_per_year': '500000000',
         'date_of_information': '2009'},
        {'country_region': 'Bosnia and Herzegovina', 'natural_gas_for_imports_in_cubic_meter_per_year': '390000000',
         'date_of_information': '2010'},
        {'country_region': 'Tajikistan', 'natural_gas_for_imports_in_cubic_meter_per_year': '189000000',
         'date_of_information': '2009'},
        {'country_region': 'Macau', 'natural_gas_for_imports_in_cubic_meter_per_year': '154500000',
         'date_of_information': '2010'},
        {'country_region': 'Denmark', 'natural_gas_for_imports_in_cubic_meter_per_year': '149000000',
         'date_of_information': '2010'},
        {'country_region': 'North Macedonia', 'natural_gas_for_imports_in_cubic_meter_per_year': '136800000',
         'date_of_information': '2011'},
        {'country_region': 'Uruguay', 'natural_gas_for_imports_in_cubic_meter_per_year': '86400000',
         'date_of_information': '2011'},
        {'country_region': 'Mongolia', 'natural_gas_for_imports_in_cubic_meter_per_year': '11790',
         'date_of_information': '2010'},
        {'country_region': 'Aruba', 'natural_gas_for_imports_in_cubic_meter_per_year': '1',
         'date_of_information': '2009'},
        {'country_region': 'Other Countries', 'natural_gas_for_imports_in_cubic_meter_per_year': '0',
         'date_of_information': '2009-2011'},
    ]

    return data


# Get the list of countries by natural gas exports
def get_the_list_of_countries_by_natural_gas_exports():
    data = [
        {'country_region': 'Russia', 'natural_gas_exports_in_cubic_meter_per_year': '199928345000',
         'date_of_information': '2020'},
        {'country_region': 'United States', 'natural_gas_exports_in_cubic_meter_per_year': '149538000000',
         'date_of_information': '2020'},
        {'country_region': 'Qatar', 'natural_gas_exports_in_cubic_meter_per_year': '143700000000',
         'date_of_information': '2020'},
        {'country_region': 'Norway', 'natural_gas_exports_in_cubic_meter_per_year': '112951000000',
         'date_of_information': '2020'},
        {'country_region': 'Australia', 'natural_gas_exports_in_cubic_meter_per_year': '102262000000',
         'date_of_information': '2020'},
        {'country_region': 'Canada', 'natural_gas_exports_in_cubic_meter_per_year': '70932000000',
         'date_of_information': '2020'},
        {'country_region': 'Germany', 'natural_gas_exports_in_cubic_meter_per_year': '50092000000',
         'date_of_information': '2020'},
        {'country_region': 'Netherlands', 'natural_gas_exports_in_cubic_meter_per_year': '39976000000',
         'date_of_information': '2020'},
        {'country_region': 'Algeria', 'natural_gas_exports_in_cubic_meter_per_year': '39459000000',
         'date_of_information': '2020'},
        {'country_region': 'Nigeria', 'natural_gas_exports_in_cubic_meter_per_year': '35586138000',
         'date_of_information': '2020'},
        {'country_region': 'Turkmenistan', 'natural_gas_exports_in_cubic_meter_per_year': '32643400000',
         'date_of_information': '2020'},
        {'country_region': 'Malaysia', 'natural_gas_exports_in_cubic_meter_per_year': '31262000000',
         'date_of_information': '2020'},
        {'country_region': 'Indonesia', 'natural_gas_exports_in_cubic_meter_per_year': '22524630000',
         'date_of_information': '2020'},
        {'country_region': 'Azerbaijan', 'natural_gas_exports_in_cubic_meter_per_year': '13800000000',
         'date_of_information': '2020'},
        {'country_region': 'Kazakhstan', 'natural_gas_exports_in_cubic_meter_per_year': '13221990000',
         'date_of_information': '2020'},
        {'country_region': 'Iran', 'natural_gas_exports_in_cubic_meter_per_year': '12670000000',
         'date_of_information': '2020'},
        {'country_region': 'Bolivia', 'natural_gas_exports_in_cubic_meter_per_year': '12400000000',
         'date_of_information': '2020'},
        {'country_region': 'Trinidad and Tobago', 'natural_gas_exports_in_cubic_meter_per_year': '12021000000',
         'date_of_information': '2020'},
        {'country_region': 'Uzbekistan', 'natural_gas_exports_in_cubic_meter_per_year': '11731200000',
         'date_of_information': '2020'},
        {'country_region': 'Brazil', 'natural_gas_exports_in_cubic_meter_per_year': '11700000000',
         'date_of_information': '2007'},
        {'country_region': 'Myanmar', 'natural_gas_exports_in_cubic_meter_per_year': '11505600000',
         'date_of_information': '2020'},
        {'country_region': 'Oman', 'natural_gas_exports_in_cubic_meter_per_year': '10625777000',
         'date_of_information': '2020'},
        {'country_region': 'United Kingdom', 'natural_gas_exports_in_cubic_meter_per_year': '9595000000',
         'date_of_information': '2020'},
        {'country_region': 'France', 'natural_gas_exports_in_cubic_meter_per_year': '9102000000',
         'date_of_information': '2020'},
        {'country_region': 'United Arab Emirates', 'natural_gas_exports_in_cubic_meter_per_year': '8766123000',
         'date_of_information': '2020'},
        {'country_region': 'Brunei', 'natural_gas_exports_in_cubic_meter_per_year': '7848000000',
         'date_of_information': '2020'},
        {'country_region': 'Egypt', 'natural_gas_exports_in_cubic_meter_per_year': '7100000000',
         'date_of_information': '2020'},
        {'country_region': 'China', 'natural_gas_exports_in_cubic_meter_per_year': '5360000000',
         'date_of_information': '2007'},
        {'country_region': 'Denmark', 'natural_gas_exports_in_cubic_meter_per_year': '4517000000',
         'date_of_information': '2007'},
        {'country_region': 'Libya', 'natural_gas_exports_in_cubic_meter_per_year': '4292000000',
         'date_of_information': '2020'},
        {'country_region': 'Austria', 'natural_gas_exports_in_cubic_meter_per_year': '2767000000',
         'date_of_information': '2007'},
        {'country_region': 'Ukraine', 'natural_gas_exports_in_cubic_meter_per_year': '1000000000',
         'date_of_information': '2008'},
        {'country_region': 'Croatia', 'natural_gas_exports_in_cubic_meter_per_year': '751700000',
         'date_of_information': '2007'},
        {'country_region': 'Argentina', 'natural_gas_exports_in_cubic_meter_per_year': '700000000',
         'date_of_information': '2020'},
        {'country_region': 'Czech Republic', 'natural_gas_exports_in_cubic_meter_per_year': '402000000',
         'date_of_information': '2007'},
        {'country_region': 'Italy', 'natural_gas_exports_in_cubic_meter_per_year': '315000000',
         'date_of_information': '2020'},
        {'country_region': 'Slovakia', 'natural_gas_exports_in_cubic_meter_per_year': '180000000',
         'date_of_information': '2007'},
        {'country_region': 'Hungary', 'natural_gas_exports_in_cubic_meter_per_year': '138000000',
         'date_of_information': '2007'},
        {'country_region': 'Poland', 'natural_gas_exports_in_cubic_meter_per_year': '45000000',
         'date_of_information': '2007'},
        {'country_region': 'Turkey', 'natural_gas_exports_in_cubic_meter_per_year': '31000000',
         'date_of_information': '2007'},
        {'country_region': 'Mexico', 'natural_gas_exports_in_cubic_meter_per_year': '12000000',
         'date_of_information': '2019'},
        {'country_region': 'Aruba', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Bahrain', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2020'},
        {'country_region': 'Botswana', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Solomon Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Belarus', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2020'},
        {'country_region': 'Benin', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2020'},
        {'country_region': 'Bosnia and Herzegovina', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Belize', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Bangladesh', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Bahamas', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Belgium', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Bermuda', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Cuba', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Central African Republic', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Costa Rica', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Colombia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Comoros', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Cameroon', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Cayman Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Chile', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'DR Congo', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Guam', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Greenland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Grenada', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Gibraltar', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Ghana', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Georgia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Gabon', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Gambia', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Faroe Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Haiti', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Kyrgyzstan', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Kenya', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Jordan', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Jamaica', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Japan', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Iraq', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Ivory Coast', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Israel', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'India', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Malawi', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Montserrat', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Mongolia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Moldova', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Macau', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2008'},
        {'country_region': 'Madagascar', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Luxembourg', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Lesotho', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Liberia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Zimbabwe', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Zambia', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Yemen', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Swaziland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Samoa', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Western Sahara', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Namibia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'U.S. Virgin Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Vietnam', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'British Virgin Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Venezuela', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Saint Vincent and the Grenadines', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Uruguay', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Burkina Faso', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Uganda', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Tanzania', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Taiwan', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2008'},
        {'country_region': 'East Timor', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Tunisia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'São Tomé and Príncipe', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Togo', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Tonga', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Turks and Caicos Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Tajikistan', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2008'},
        {'country_region': 'Thailand', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Switzerland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Sweden', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Sudan', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Saint Lucia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Spain', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Somalia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Singapore', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Sierra Leone', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Slovenia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Saint Helena', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Senegal', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'South Africa', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Seychelles', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Saint Kitts and Nevis', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Saint Pierre and Miquelon', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Saudi Arabia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Rwanda', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Puerto Rico', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Philippines', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Romania', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Serbia', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2005'},
        {'country_region': 'Guinea-Bissau', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Papua New Guinea', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Portugal', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Panama', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Pakistan', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Peru', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2008'},
        {'country_region': 'Paraguay', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'New Zealand', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Nicaragua', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Netherlands Antilles', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Suriname', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Nauru', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Nepal', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2008'},
        {'country_region': 'Vanuatu', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Niger', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Niue', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'New Caledonia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Mozambique', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2005'},
        {'country_region': 'Maldives', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2008'},
        {'country_region': 'Malta', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Mauritania', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Mauritius', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Morocco', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Mali', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Macedonia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Lithuania', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Latvia', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Lebanon', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Laos', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Kuwait', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'South Korea', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Kiribati', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'North Korea', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Iceland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Honduras', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Hong Kong', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2008'},
        {'country_region': 'Haiti', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Guyana', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Guinea', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Guatemala', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Greece', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Falkland Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Fiji', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Finland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Ethiopia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'El Salvador', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Eritrea', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Estonia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Equatorial Guinea', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'French Polynesia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Ireland', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Ecuador', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Dominican Republic', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Dominica', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Djibouti', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Cyprus', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Cook Islands', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Cape Verde', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Congo', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Sri Lanka', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2008'},
        {'country_region': 'Chad', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Cambodia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Burundi', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Bulgaria', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Bhutan', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Barbados', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Armenia', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'American Samoa', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Angola', 'natural_gas_exports_in_cubic_meter_per_year': '0', 'date_of_information': '2007'},
        {'country_region': 'Albania', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Afghanistan', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
        {'country_region': 'Antigua and Barbuda', 'natural_gas_exports_in_cubic_meter_per_year': '0',
         'date_of_information': '2007'},
    ]

    return data
