# Get the list of countries by electricity consumption
def get_the_list_of_countries_by_electricity_consumption():
    data = [
        {'rank': '—', 'country_region': 'World', 'total_electricity_consumption_in_gwh_per_year': '23398000',
         'year_of_data': '2018', 'source': 'EIA', 'population': '7800000000', 'as_of': '2018',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3081',
         'average_electrical_power_per_capita_expressed_in_watts': '350'},
        {'rank': '1', 'country_region': 'China', 'total_electricity_consumption_in_gwh_per_year': '8312800',
         'year_of_data': '2021', 'source': 'ENGLISH.GOV.CN', 'population': '1412600000', 'as_of': '2021',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5885',
         'average_electrical_power_per_capita_expressed_in_watts': '671'},
        {'rank': '2', 'country_region': 'United States', 'total_electricity_consumption_in_gwh_per_year': '3989566',
         'year_of_data': '2019', 'source': 'EIA', 'population': '328200000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '12154',
         'average_electrical_power_per_capita_expressed_in_watts': '1387'},
        {'rank': '3', 'country_region': 'India', 'total_electricity_consumption_in_gwh_per_year': '1383416',
         'year_of_data': '2020', 'source': 'CSO', 'population': '1384660000', 'as_of': '2020',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1208',
         'average_electrical_power_per_capita_expressed_in_watts': '107'},
        {'rank': '4', 'country_region': 'Russia', 'total_electricity_consumption_in_gwh_per_year': '965156',
         'year_of_data': '2019', 'source': 'EIA', 'population': '146700000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6685',
         'average_electrical_power_per_capita_expressed_in_watts': '763'},
        {'rank': '5', 'country_region': 'Japan', 'total_electricity_consumption_in_gwh_per_year': '902842',
         'year_of_data': '2019', 'source': 'EIA', 'population': '126860000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '7150',
         'average_electrical_power_per_capita_expressed_in_watts': '816'},
        {'rank': '6', 'country_region': 'Brazil', 'total_electricity_consumption_in_gwh_per_year': '597234',
         'year_of_data': '2019', 'source': 'EIA', 'population': '210000000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2830',
         'average_electrical_power_per_capita_expressed_in_watts': '323'},
        {'rank': '7', 'country_region': 'Canada', 'total_electricity_consumption_in_gwh_per_year': '549263',
         'year_of_data': '2019', 'source': 'EIA', 'population': '37534000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '14612',
         'average_electrical_power_per_capita_expressed_in_watts': '1667'},
        {'rank': '8', 'country_region': 'Korea, South', 'total_electricity_consumption_in_gwh_per_year': '527035',
         'year_of_data': '2019', 'source': 'EIA', 'population': '51710000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '10192',
         'average_electrical_power_per_capita_expressed_in_watts': '1163'},
        {'rank': '9', 'country_region': 'Germany', 'total_electricity_consumption_in_gwh_per_year': '524268',
         'year_of_data': '2019', 'source': 'EIA', 'population': '83200000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6306',
         'average_electrical_power_per_capita_expressed_in_watts': '719'},
        {'rank': '10', 'country_region': 'France', 'total_electricity_consumption_in_gwh_per_year': '449422',
         'year_of_data': '2019', 'source': 'EIA', 'population': '66980000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6702',
         'average_electrical_power_per_capita_expressed_in_watts': '765'},
        {'rank': '11', 'country_region': 'Saudi Arabia', 'total_electricity_consumption_in_gwh_per_year': '322372',
         'year_of_data': '2018', 'source': 'EIA', 'population': '33413000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9407',
         'average_electrical_power_per_capita_expressed_in_watts': '1073'},
        {'rank': '12', 'country_region': 'United Kingdom', 'total_electricity_consumption_in_gwh_per_year': '300520',
         'year_of_data': '2019', 'source': 'EIA', 'population': '66800000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4496',
         'average_electrical_power_per_capita_expressed_in_watts': '513'},
        {'rank': '13', 'country_region': 'Italy', 'total_electricity_consumption_in_gwh_per_year': '297150',
         'year_of_data': '2019', 'source': 'EIA', 'population': '60244000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4928',
         'average_electrical_power_per_capita_expressed_in_watts': '562'},
        {'rank': '14', 'country_region': 'Mexico', 'total_electricity_consumption_in_gwh_per_year': '267910',
         'year_of_data': '2019', 'source': 'EIA', 'population': '127580000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2100',
         'average_electrical_power_per_capita_expressed_in_watts': '240'},
        {'rank': '15', 'country_region': 'Indonesia', 'total_electricity_consumption_in_gwh_per_year': '263139',
         'year_of_data': '2019', 'source': 'EIA', 'population': '270625570', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '972',
         'average_electrical_power_per_capita_expressed_in_watts': '111'},
        {'rank': '16', 'country_region': 'Iran', 'total_electricity_consumption_in_gwh_per_year': '254724',
         'year_of_data': '2018', 'source': 'EIA', 'population': '82913910', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3072',
         'average_electrical_power_per_capita_expressed_in_watts': '350'},
        {'rank': '17', 'country_region': 'Turkey', 'total_electricity_consumption_in_gwh_per_year': '251376',
         'year_of_data': '2019', 'source': 'EIA', 'population': '83429620', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3013',
         'average_electrical_power_per_capita_expressed_in_watts': '344'},
        {'rank': '18', 'country_region': 'Spain', 'total_electricity_consumption_in_gwh_per_year': '241563',
         'year_of_data': '2019', 'source': 'EIA', 'population': '47076780', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5131',
         'average_electrical_power_per_capita_expressed_in_watts': '585'},
        {'rank': '19', 'country_region': 'Australia', 'total_electricity_consumption_in_gwh_per_year': '241020',
         'year_of_data': '2019', 'source': 'EIA', 'population': '25364310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9502',
         'average_electrical_power_per_capita_expressed_in_watts': '1084'},
        {'rank': '20', 'country_region': 'Taiwan', 'total_electricity_consumption_in_gwh_per_year': '237557',
         'year_of_data': '2019', 'source': 'EIA', 'population': '23775000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9992',
         'average_electrical_power_per_capita_expressed_in_watts': '1140'},
        {'rank': '21', 'country_region': 'Vietnam', 'total_electricity_consumption_in_gwh_per_year': '216994',
         'year_of_data': '2018', 'source': 'EIA', 'population': '96462110', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2250',
         'average_electrical_power_per_capita_expressed_in_watts': '257'},
        {'rank': '22', 'country_region': 'South Africa', 'total_electricity_consumption_in_gwh_per_year': '210304',
         'year_of_data': '2019', 'source': 'EIA', 'population': '58558270', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3591',
         'average_electrical_power_per_capita_expressed_in_watts': '410'},
        {'rank': '23', 'country_region': 'Thailand', 'total_electricity_consumption_in_gwh_per_year': '185852',
         'year_of_data': '2018', 'source': 'EIA', 'population': '69625580', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2669',
         'average_electrical_power_per_capita_expressed_in_watts': '305'},
        {'rank': '24', 'country_region': 'Egypt', 'total_electricity_consumption_in_gwh_per_year': '150579',
         'year_of_data': '2018', 'source': 'EIA', 'population': '100388070', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1500',
         'average_electrical_power_per_capita_expressed_in_watts': '171'},
        {'rank': '25', 'country_region': 'Ukraine', 'total_electricity_consumption_in_gwh_per_year': '128806',
         'year_of_data': '2019', 'source': 'EIA', 'population': '44385150', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2902',
         'average_electrical_power_per_capita_expressed_in_watts': '331'},
        {'rank': '26', 'country_region': 'Poland', 'total_electricity_consumption_in_gwh_per_year': '152573',
         'year_of_data': '2019', 'source': 'EIA', 'population': '37970870', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4018',
         'average_electrical_power_per_capita_expressed_in_watts': '458'},
        {'rank': '27', 'country_region': 'Malaysia', 'total_electricity_consumption_in_gwh_per_year': '147209',
         'year_of_data': '2018', 'source': 'EIA', 'population': '31949780', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4608',
         'average_electrical_power_per_capita_expressed_in_watts': '526'},
        {'rank': '28', 'country_region': 'Sweden', 'total_electricity_consumption_in_gwh_per_year': '131798',
         'year_of_data': '2019', 'source': 'EIA', 'population': '10285450', 'as_of': '2020',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '13085',
         'average_electrical_power_per_capita_expressed_in_watts': '1462'},
        {'rank': '29', 'country_region': 'Norway', 'total_electricity_consumption_in_gwh_per_year': '124127',
         'year_of_data': '2019', 'source': 'EIA', 'population': '5347900', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '23210',
         'average_electrical_power_per_capita_expressed_in_watts': '2648'},
        {'rank': '30', 'country_region': 'Argentina', 'total_electricity_consumption_in_gwh_per_year': '125030',
         'year_of_data': '2018', 'source': 'EIA', 'population': '44938710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2782',
         'average_electrical_power_per_capita_expressed_in_watts': '317'},
        {'rank': '31', 'country_region': 'Netherlands', 'total_electricity_consumption_in_gwh_per_year': '110682',
         'year_of_data': '2019', 'source': 'EIA', 'population': '17332850', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6386',
         'average_electrical_power_per_capita_expressed_in_watts': '728'},
        {'rank': '32', 'country_region': 'United Arab Emirates',
         'total_electricity_consumption_in_gwh_per_year': '119455', 'year_of_data': '2018', 'source': 'EIA',
         'population': '9770530', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '12226',
         'average_electrical_power_per_capita_expressed_in_watts': '1395'},
        {'rank': '33', 'country_region': 'Philippines', 'total_electricity_consumption_in_gwh_per_year': '93354',
         'year_of_data': '2019', 'source': 'EIA', 'population': '108116620', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '863',
         'average_electrical_power_per_capita_expressed_in_watts': '99'},
        {'rank': '34', 'country_region': 'Kazakhstan', 'total_electricity_consumption_in_gwh_per_year': '91668',
         'year_of_data': '2018', 'source': 'EIA', 'population': '18513930', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4951',
         'average_electrical_power_per_capita_expressed_in_watts': '565'},
        {'rank': '35', 'country_region': 'Pakistan', 'total_electricity_consumption_in_gwh_per_year': '90000',
         'year_of_data': '2020', 'source': 'EIA', 'population': '216565320', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '557',
         'average_electrical_power_per_capita_expressed_in_watts': '64'},
        {'rank': '36', 'country_region': 'Finland', 'total_electricity_consumption_in_gwh_per_year': '84207',
         'year_of_data': '2019', 'source': 'EIA', 'population': '5520310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '15254',
         'average_electrical_power_per_capita_expressed_in_watts': '1740'},
        {'rank': '37', 'country_region': 'Belgium', 'total_electricity_consumption_in_gwh_per_year': '82051',
         'year_of_data': '2019', 'source': 'EIA', 'population': '11484060', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '7145',
         'average_electrical_power_per_capita_expressed_in_watts': '815'},
        {'rank': '38', 'country_region': 'Venezuela', 'total_electricity_consumption_in_gwh_per_year': '64660',
         'year_of_data': '2018', 'source': 'EIA', 'population': '28515830', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2268',
         'average_electrical_power_per_capita_expressed_in_watts': '259'},
        {'rank': '39', 'country_region': 'Austria', 'total_electricity_consumption_in_gwh_per_year': '66849',
         'year_of_data': '2019', 'source': 'EIA', 'population': '8877070', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '7530',
         'average_electrical_power_per_capita_expressed_in_watts': '859'},
        {'rank': '40', 'country_region': 'Chile', 'total_electricity_consumption_in_gwh_per_year': '74992',
         'year_of_data': '2019', 'source': 'EIA', 'population': '18952040', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3957',
         'average_electrical_power_per_capita_expressed_in_watts': '451'},
        {'rank': '41', 'country_region': 'Czech Republic', 'total_electricity_consumption_in_gwh_per_year': '63920',
         'year_of_data': '2019', 'source': 'EIA', 'population': '10669710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5991',
         'average_electrical_power_per_capita_expressed_in_watts': '683'},
        {'rank': '42', 'country_region': 'Colombia', 'total_electricity_consumption_in_gwh_per_year': '70203',
         'year_of_data': '2018', 'source': 'EIA', 'population': '50339440', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1395',
         'average_electrical_power_per_capita_expressed_in_watts': '159'},
        {'rank': '43', 'country_region': 'Israel', 'total_electricity_consumption_in_gwh_per_year': '56391',
         'year_of_data': '2018', 'source': 'EIA', 'population': '9053300', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6229',
         'average_electrical_power_per_capita_expressed_in_watts': '711'},
        {'rank': '44', 'country_region': 'Switzerland', 'total_electricity_consumption_in_gwh_per_year': '56353',
         'year_of_data': '2019', 'source': 'EIA', 'population': '8574830', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6572',
         'average_electrical_power_per_capita_expressed_in_watts': '750'},
        {'rank': '45', 'country_region': 'Bangladesh', 'total_electricity_consumption_in_gwh_per_year': '70594',
         'year_of_data': '2018', 'source': 'EIA', 'population': '163046160', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '433',
         'average_electrical_power_per_capita_expressed_in_watts': '49'},
        {'rank': '46', 'country_region': 'Kuwait', 'total_electricity_consumption_in_gwh_per_year': '59278',
         'year_of_data': '2018', 'source': 'EIA', 'population': '4207080', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '14090',
         'average_electrical_power_per_capita_expressed_in_watts': '1607'},
        {'rank': '47', 'country_region': 'Greece', 'total_electricity_consumption_in_gwh_per_year': '53635',
         'year_of_data': '2019', 'source': 'EIA', 'population': '10716320', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5005',
         'average_electrical_power_per_capita_expressed_in_watts': '571'},
        {'rank': '48', 'country_region': 'Algeria', 'total_electricity_consumption_in_gwh_per_year': '62062',
         'year_of_data': '2018', 'source': 'EIA', 'population': '43053050', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1442',
         'average_electrical_power_per_capita_expressed_in_watts': '164'},
        {'rank': '49', 'country_region': 'Romania', 'total_electricity_consumption_in_gwh_per_year': '55008',
         'year_of_data': '2019', 'source': 'EIA', 'population': '19356540', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2842',
         'average_electrical_power_per_capita_expressed_in_watts': '324'},
        {'rank': '50', 'country_region': 'Uzbekistan', 'total_electricity_consumption_in_gwh_per_year': '49204',
         'year_of_data': '2018', 'source': 'EIA', 'population': '33580650', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1465',
         'average_electrical_power_per_capita_expressed_in_watts': '167'},
        {'rank': '51', 'country_region': 'Singapore', 'total_electricity_consumption_in_gwh_per_year': '47583',
         'year_of_data': '2019', 'source': 'EIA', 'population': '5703570', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8343',
         'average_electrical_power_per_capita_expressed_in_watts': '952'},
        {'rank': '52', 'country_region': 'Portugal', 'total_electricity_consumption_in_gwh_per_year': '48035',
         'year_of_data': '2019', 'source': 'EIA', 'population': '10269420', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4677',
         'average_electrical_power_per_capita_expressed_in_watts': '534'},
        {'rank': '53', 'country_region': 'Hong Kong', 'total_electricity_consumption_in_gwh_per_year': '44730',
         'year_of_data': '2018', 'source': 'EIA', 'population': '7507400', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5958',
         'average_electrical_power_per_capita_expressed_in_watts': '680'},
        {'rank': '54', 'country_region': 'Iraq', 'total_electricity_consumption_in_gwh_per_year': '43971',
         'year_of_data': '2018', 'source': 'EIA', 'population': '39309780', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1119',
         'average_electrical_power_per_capita_expressed_in_watts': '128'},
        {'rank': '55', 'country_region': 'New Zealand', 'total_electricity_consumption_in_gwh_per_year': '41165',
         'year_of_data': '2019', 'source': 'EIA', 'population': '4917000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8372',
         'average_electrical_power_per_capita_expressed_in_watts': '955'},
        {'rank': '56', 'country_region': 'Hungary', 'total_electricity_consumption_in_gwh_per_year': '41621',
         'year_of_data': '2019', 'source': 'EIA', 'population': '9769950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4260',
         'average_electrical_power_per_capita_expressed_in_watts': '486'},
        {'rank': '57', 'country_region': 'Peru', 'total_electricity_consumption_in_gwh_per_year': '47409',
         'year_of_data': '2018', 'source': 'EIA', 'population': '32510450', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1458',
         'average_electrical_power_per_capita_expressed_in_watts': '166'},
        {'rank': '58', 'country_region': 'Qatar', 'total_electricity_consumption_in_gwh_per_year': '43375',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2832070', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '15316',
         'average_electrical_power_per_capita_expressed_in_watts': '1747'},
        {'rank': '59', 'country_region': 'Belarus', 'total_electricity_consumption_in_gwh_per_year': '32736',
         'year_of_data': '2019', 'source': 'EIA', 'population': '9466860', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3458',
         'average_electrical_power_per_capita_expressed_in_watts': '394'},
        {'rank': '60', 'country_region': 'Denmark', 'total_electricity_consumption_in_gwh_per_year': '32703',
         'year_of_data': '2019', 'source': 'EIA', 'population': '5818550', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5620',
         'average_electrical_power_per_capita_expressed_in_watts': '641'},
        {'rank': '61', 'country_region': 'Bulgaria', 'total_electricity_consumption_in_gwh_per_year': '33134',
         'year_of_data': '2019', 'source': 'EIA', 'population': '6975760', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4750',
         'average_electrical_power_per_capita_expressed_in_watts': '542'},
        {'rank': '62', 'country_region': 'Morocco', 'total_electricity_consumption_in_gwh_per_year': '29678',
         'year_of_data': '2018', 'source': 'EIA', 'population': '36471770', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '814',
         'average_electrical_power_per_capita_expressed_in_watts': '93'},
        {'rank': '63', 'country_region': 'Slovakia', 'total_electricity_consumption_in_gwh_per_year': '26237',
         'year_of_data': '2019', 'source': 'EIA', 'population': '5454070', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4810',
         'average_electrical_power_per_capita_expressed_in_watts': '549'},
        {'rank': '64', 'country_region': 'Serbia', 'total_electricity_consumption_in_gwh_per_year': '30292',
         'year_of_data': '2018', 'source': 'EIA', 'population': '6944980', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4362',
         'average_electrical_power_per_capita_expressed_in_watts': '498'},
        {'rank': '65', 'country_region': 'Bahrain', 'total_electricity_consumption_in_gwh_per_year': '27447',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1641170', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '16724',
         'average_electrical_power_per_capita_expressed_in_watts': '1908'},
        {'rank': '66', 'country_region': 'Ireland', 'total_electricity_consumption_in_gwh_per_year': '27203',
         'year_of_data': '2019', 'source': 'EIA', 'population': '4941440', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5505',
         'average_electrical_power_per_capita_expressed_in_watts': '628'},
        {'rank': '67', 'country_region': 'Oman', 'total_electricity_consumption_in_gwh_per_year': '31766',
         'year_of_data': '2018', 'source': 'EIA', 'population': '4974990', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6385',
         'average_electrical_power_per_capita_expressed_in_watts': '728'},
        {'rank': '68', 'country_region': 'Nigeria', 'total_electricity_consumption_in_gwh_per_year': '29011',
         'year_of_data': '2018', 'source': 'EIA', 'population': '200963600', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '144',
         'average_electrical_power_per_capita_expressed_in_watts': '16'},
        {'rank': '69', 'country_region': 'Ecuador', 'total_electricity_consumption_in_gwh_per_year': '24605',
         'year_of_data': '2018', 'source': 'EIA', 'population': '17373660', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1416',
         'average_electrical_power_per_capita_expressed_in_watts': '162'},
        {'rank': '70', 'country_region': 'Azerbaijan', 'total_electricity_consumption_in_gwh_per_year': '20286',
         'year_of_data': '2018', 'source': 'EIA', 'population': '10023320', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2024',
         'average_electrical_power_per_capita_expressed_in_watts': '231'},
        {'rank': '71', 'country_region': 'Puerto Rico', 'total_electricity_consumption_in_gwh_per_year': '15466',
         'year_of_data': '2018', 'source': 'EIA', 'population': '3193690', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4843',
         'average_electrical_power_per_capita_expressed_in_watts': '552'},
        {'rank': '72', 'country_region': 'Iceland', 'total_electricity_consumption_in_gwh_per_year': '18679',
         'year_of_data': '2019', 'source': 'EIA', 'population': '361310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '51699',
         'average_electrical_power_per_capita_expressed_in_watts': '5898'},
        {'rank': '73', 'country_region': 'Syria', 'total_electricity_consumption_in_gwh_per_year': '14263',
         'year_of_data': '2018', 'source': 'EIA', 'population': '17070130', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '836',
         'average_electrical_power_per_capita_expressed_in_watts': '95'},
        {'rank': '74', 'country_region': 'Croatia', 'total_electricity_consumption_in_gwh_per_year': '17475',
         'year_of_data': '2019', 'source': 'EIA', 'population': '4067500', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4296',
         'average_electrical_power_per_capita_expressed_in_watts': '490'},
        {'rank': '75', 'country_region': 'Jordan', 'total_electricity_consumption_in_gwh_per_year': '17384',
         'year_of_data': '2018', 'source': 'EIA', 'population': '10101690', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1721',
         'average_electrical_power_per_capita_expressed_in_watts': '196'},
        {'rank': '76', 'country_region': 'Lebanon', 'total_electricity_consumption_in_gwh_per_year': '17708',
         'year_of_data': '2018', 'source': 'EIA', 'population': '6855710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2583',
         'average_electrical_power_per_capita_expressed_in_watts': '295'},
        {'rank': '77', 'country_region': 'Dominican Republic', 'total_electricity_consumption_in_gwh_per_year': '16067',
         'year_of_data': '2018', 'source': 'EIA', 'population': '10738960', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1496',
         'average_electrical_power_per_capita_expressed_in_watts': '171'},
        {'rank': '78', 'country_region': 'Tunisia', 'total_electricity_consumption_in_gwh_per_year': '15838',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11694720', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1354',
         'average_electrical_power_per_capita_expressed_in_watts': '154'},
        {'rank': '79', 'country_region': 'Cuba', 'total_electricity_consumption_in_gwh_per_year': '16341',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11333480', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1442',
         'average_electrical_power_per_capita_expressed_in_watts': '164'},
        {'rank': '80', 'country_region': 'Korea, North', 'total_electricity_consumption_in_gwh_per_year': '12708',
         'year_of_data': '2018', 'source': 'EIA', 'population': '25666160', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '495',
         'average_electrical_power_per_capita_expressed_in_watts': '56'},
        {'rank': '81', 'country_region': 'Slovenia', 'total_electricity_consumption_in_gwh_per_year': '14023',
         'year_of_data': '2019', 'source': 'EIA', 'population': '2087950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6716',
         'average_electrical_power_per_capita_expressed_in_watts': '766'},
        {'rank': '82', 'country_region': 'Turkmenistan', 'total_electricity_consumption_in_gwh_per_year': '15090',
         'year_of_data': '2018', 'source': 'EIA', 'population': '5942090', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2540',
         'average_electrical_power_per_capita_expressed_in_watts': '290'},
        {'rank': '83', 'country_region': 'Tajikistan', 'total_electricity_consumption_in_gwh_per_year': '16085',
         'year_of_data': '2019', 'source': 'EIA', 'population': '9321020', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1726',
         'average_electrical_power_per_capita_expressed_in_watts': '197'},
        {'rank': '84', 'country_region': 'Mozambique', 'total_electricity_consumption_in_gwh_per_year': '13390',
         'year_of_data': '2018', 'source': 'EIA', 'population': '30366040', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '441',
         'average_electrical_power_per_capita_expressed_in_watts': '50'},
        {'rank': '85', 'country_region': 'Kyrgyzstan', 'total_electricity_consumption_in_gwh_per_year': '11740',
         'year_of_data': '2018', 'source': 'EIA', 'population': '6456900', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1818',
         'average_electrical_power_per_capita_expressed_in_watts': '207'},
        {'rank': '86', 'country_region': 'Sri Lanka', 'total_electricity_consumption_in_gwh_per_year': '13438',
         'year_of_data': '2018', 'source': 'EIA', 'population': '21803000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '616',
         'average_electrical_power_per_capita_expressed_in_watts': '70'},
        {'rank': '87', 'country_region': 'Zambia', 'total_electricity_consumption_in_gwh_per_year': '13097',
         'year_of_data': '2018', 'source': 'EIA', 'population': '17861030', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '733',
         'average_electrical_power_per_capita_expressed_in_watts': '84'},
        {'rank': '88', 'country_region': 'Bosnia and Herzegovina',
         'total_electricity_consumption_in_gwh_per_year': '12253', 'year_of_data': '2018', 'source': 'EIA',
         'population': '3301000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3712',
         'average_electrical_power_per_capita_expressed_in_watts': '423'},
        {'rank': '89', 'country_region': 'Myanmar', 'total_electricity_consumption_in_gwh_per_year': '18024',
         'year_of_data': '2018', 'source': 'EIA', 'population': '54045420', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '333',
         'average_electrical_power_per_capita_expressed_in_watts': '38'},
        {'rank': '90', 'country_region': 'Uruguay', 'total_electricity_consumption_in_gwh_per_year': '11812',
         'year_of_data': '2018', 'source': 'EIA', 'population': '3461730', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3412',
         'average_electrical_power_per_capita_expressed_in_watts': '389'},
        {'rank': '91', 'country_region': 'Lithuania', 'total_electricity_consumption_in_gwh_per_year': '11306',
         'year_of_data': '2019', 'source': 'EIA', 'population': '2786840', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4057',
         'average_electrical_power_per_capita_expressed_in_watts': '463'},
        {'rank': '92', 'country_region': 'Sudan', 'total_electricity_consumption_in_gwh_per_year': '11463',
         'year_of_data': '2018', 'source': 'EIA', 'population': '42813240', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '268',
         'average_electrical_power_per_capita_expressed_in_watts': '31'},
        {'rank': '93', 'country_region': 'Georgia', 'total_electricity_consumption_in_gwh_per_year': '12179',
         'year_of_data': '2019', 'source': 'EIA', 'population': '3720380', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3274',
         'average_electrical_power_per_capita_expressed_in_watts': '373'},
        {'rank': '94', 'country_region': 'Paraguay', 'total_electricity_consumption_in_gwh_per_year': '13097',
         'year_of_data': '2018', 'source': 'EIA', 'population': '7044640', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1859',
         'average_electrical_power_per_capita_expressed_in_watts': '212'},
        {'rank': '95', 'country_region': 'Libya', 'total_electricity_consumption_in_gwh_per_year': '25693',
         'year_of_data': '2018', 'source': 'EIA', 'population': '6777450', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3791',
         'average_electrical_power_per_capita_expressed_in_watts': '432'},
        {'rank': '96', 'country_region': 'Congo, Democratic Republic of the',
         'total_electricity_consumption_in_gwh_per_year': '8594', 'year_of_data': '2018', 'source': 'EIA',
         'population': '86790570', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '99',
         'average_electrical_power_per_capita_expressed_in_watts': '11'},
        {'rank': '97', 'country_region': 'Costa Rica', 'total_electricity_consumption_in_gwh_per_year': '10065',
         'year_of_data': '2018', 'source': 'EIA', 'population': '5047560', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1994',
         'average_electrical_power_per_capita_expressed_in_watts': '227'},
        {'rank': '98', 'country_region': 'Ghana', 'total_electricity_consumption_in_gwh_per_year': '8842',
         'year_of_data': '2018', 'source': 'EIA', 'population': '30417860', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '291',
         'average_electrical_power_per_capita_expressed_in_watts': '33'},
        {'rank': '99', 'country_region': 'Trinidad and Tobago', 'total_electricity_consumption_in_gwh_per_year': '8246',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1394970', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5911',
         'average_electrical_power_per_capita_expressed_in_watts': '674'},
        {'rank': '100', 'country_region': 'Guatemala', 'total_electricity_consumption_in_gwh_per_year': '10570',
         'year_of_data': '2018', 'source': 'EIA', 'population': '16604030', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '637',
         'average_electrical_power_per_capita_expressed_in_watts': '73'},
        {'rank': '101', 'country_region': 'Estonia', 'total_electricity_consumption_in_gwh_per_year': '8858',
         'year_of_data': '2019', 'source': 'EIA', 'population': '1326590', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6677',
         'average_electrical_power_per_capita_expressed_in_watts': '762'},
        {'rank': '102', 'country_region': 'Angola', 'total_electricity_consumption_in_gwh_per_year': '10364',
         'year_of_data': '2018', 'source': 'EIA', 'population': '31825290', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '326',
         'average_electrical_power_per_capita_expressed_in_watts': '37'},
        {'rank': '103', 'country_region': 'Zimbabwe', 'total_electricity_consumption_in_gwh_per_year': '7401',
         'year_of_data': '2018', 'source': 'EIA', 'population': '14645470', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '505',
         'average_electrical_power_per_capita_expressed_in_watts': '58'},
        {'rank': '104', 'country_region': 'Panama', 'total_electricity_consumption_in_gwh_per_year': '9258',
         'year_of_data': '2018', 'source': 'EIA', 'population': '4246440', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2180',
         'average_electrical_power_per_capita_expressed_in_watts': '249'},
        {'rank': '105', 'country_region': 'Albania', 'total_electricity_consumption_in_gwh_per_year': '4849',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2854190', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1699',
         'average_electrical_power_per_capita_expressed_in_watts': '194'},
        {'rank': '106', 'country_region': 'Kenya', 'total_electricity_consumption_in_gwh_per_year': '8722',
         'year_of_data': '2018', 'source': 'EIA', 'population': '52573970', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '166',
         'average_electrical_power_per_capita_expressed_in_watts': '19'},
        {'rank': '107', 'country_region': 'Bolivia', 'total_electricity_consumption_in_gwh_per_year': '9057',
         'year_of_data': '2019', 'source': 'EIA', 'population': '11513100', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '787',
         'average_electrical_power_per_capita_expressed_in_watts': '90'},
        {'rank': '108', 'country_region': 'North Macedonia', 'total_electricity_consumption_in_gwh_per_year': '7024',
         'year_of_data': '2019', 'source': 'EIA', 'population': '2083460', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3371',
         'average_electrical_power_per_capita_expressed_in_watts': '385'},
        {'rank': '109', 'country_region': 'Latvia', 'total_electricity_consumption_in_gwh_per_year': '6877',
         'year_of_data': '2019', 'source': 'EIA', 'population': '1912790', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3595',
         'average_electrical_power_per_capita_expressed_in_watts': '410'},
        {'rank': '110', 'country_region': 'Ethiopia', 'total_electricity_consumption_in_gwh_per_year': '8986',
         'year_of_data': '2018', 'source': 'EIA', 'population': '112078730', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '80',
         'average_electrical_power_per_capita_expressed_in_watts': '9'},
        {'rank': '111', 'country_region': 'Luxembourg', 'total_electricity_consumption_in_gwh_per_year': '5817',
         'year_of_data': '2019', 'source': 'EIA', 'population': '619900', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9383',
         'average_electrical_power_per_capita_expressed_in_watts': '1070'},
        {'rank': '112', 'country_region': 'Cameroon', 'total_electricity_consumption_in_gwh_per_year': '6743',
         'year_of_data': '2018', 'source': 'EIA', 'population': '25876380', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '261',
         'average_electrical_power_per_capita_expressed_in_watts': '30'},
        {'rank': '113', 'country_region': 'Ivory Coast', 'total_electricity_consumption_in_gwh_per_year': '6686',
         'year_of_data': '2018', 'source': 'EIA', 'population': '25716540', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '260',
         'average_electrical_power_per_capita_expressed_in_watts': '30'},
        {'rank': '114', 'country_region': 'El Salvador', 'total_electricity_consumption_in_gwh_per_year': '6212',
         'year_of_data': '2019', 'source': 'EIA', 'population': '6453550', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '963',
         'average_electrical_power_per_capita_expressed_in_watts': '110'},
        {'rank': '115', 'country_region': 'Mongolia', 'total_electricity_consumption_in_gwh_per_year': '6933',
         'year_of_data': '2018', 'source': 'EIA', 'population': '3225170', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2150',
         'average_electrical_power_per_capita_expressed_in_watts': '245'},
        {'rank': '116', 'country_region': 'Honduras', 'total_electricity_consumption_in_gwh_per_year': '6696',
         'year_of_data': '2018', 'source': 'EIA', 'population': '9746120', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '687',
         'average_electrical_power_per_capita_expressed_in_watts': '78'},
        {'rank': '117', 'country_region': 'West Bank', 'total_electricity_consumption_in_gwh_per_year': '5496',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2697687', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1103',
         'average_electrical_power_per_capita_expressed_in_watts': '126'},
        {'rank': '118', 'country_region': 'Yemen', 'total_electricity_consumption_in_gwh_per_year': '2653',
         'year_of_data': '2018', 'source': 'EIA', 'population': '29161920', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '91',
         'average_electrical_power_per_capita_expressed_in_watts': '10'},
        {'rank': '119', 'country_region': 'Armenia', 'total_electricity_consumption_in_gwh_per_year': '5791',
         'year_of_data': '2019', 'source': 'EIA', 'population': '2957730', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1958',
         'average_electrical_power_per_capita_expressed_in_watts': '223'},
        {'rank': '120', 'country_region': 'Tanzania', 'total_electricity_consumption_in_gwh_per_year': '5813',
         'year_of_data': '2018', 'source': 'EIA', 'population': '58005460', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '100',
         'average_electrical_power_per_capita_expressed_in_watts': '11'},
        {'rank': '121', 'country_region': 'Afghanistan', 'total_electricity_consumption_in_gwh_per_year': '6023',
         'year_of_data': '2018', 'source': 'EIA', 'population': '38041750', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '158',
         'average_electrical_power_per_capita_expressed_in_watts': '18'},
        {'rank': '122', 'country_region': 'Macau', 'total_electricity_consumption_in_gwh_per_year': '5378',
         'year_of_data': '2018', 'source': 'EIA', 'population': '640450', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8397',
         'average_electrical_power_per_capita_expressed_in_watts': '958'},
        {'rank': '123', 'country_region': 'Nicaragua', 'total_electricity_consumption_in_gwh_per_year': '3738',
         'year_of_data': '2018', 'source': 'EIA', 'population': '6545500', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '571',
         'average_electrical_power_per_capita_expressed_in_watts': '65'},
        {'rank': '124', 'country_region': 'Moldova', 'total_electricity_consumption_in_gwh_per_year': '5957',
         'year_of_data': '2019', 'source': 'EIA', 'population': '2657640', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2241',
         'average_electrical_power_per_capita_expressed_in_watts': '256'},
        {'rank': '125', 'country_region': 'Cambodia', 'total_electricity_consumption_in_gwh_per_year': '8402',
         'year_of_data': '2018', 'source': 'EIA', 'population': '16486540', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '510',
         'average_electrical_power_per_capita_expressed_in_watts': '58'},
        {'rank': '126', 'country_region': 'Laos', 'total_electricity_consumption_in_gwh_per_year': '4059',
         'year_of_data': '2018', 'source': 'EIA', 'population': '7169450', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '566',
         'average_electrical_power_per_capita_expressed_in_watts': '65'},
        {'rank': '127', 'country_region': 'Nepal', 'total_electricity_consumption_in_gwh_per_year': '6562',
         'year_of_data': '2018', 'source': 'EIA', 'population': '28608710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '229',
         'average_electrical_power_per_capita_expressed_in_watts': '26'},
        {'rank': '128', 'country_region': 'Cyprus', 'total_electricity_consumption_in_gwh_per_year': '4524',
         'year_of_data': '2019', 'source': 'EIA', 'population': '1198580', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3774',
         'average_electrical_power_per_capita_expressed_in_watts': '431'},
        {'rank': '129', 'country_region': 'Brunei', 'total_electricity_consumption_in_gwh_per_year': '3555',
         'year_of_data': '2018', 'source': 'EIA', 'population': '433290', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8206',
         'average_electrical_power_per_capita_expressed_in_watts': '936'},
        {'rank': '130', 'country_region': 'Botswana', 'total_electricity_consumption_in_gwh_per_year': '3301',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2303700', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1433',
         'average_electrical_power_per_capita_expressed_in_watts': '163'},
        {'rank': '131', 'country_region': 'Namibia', 'total_electricity_consumption_in_gwh_per_year': '4184',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2494530', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1677',
         'average_electrical_power_per_capita_expressed_in_watts': '191'},
        {'rank': '132', 'country_region': 'Papua New Guinea', 'total_electricity_consumption_in_gwh_per_year': '3777',
         'year_of_data': '2018', 'source': 'EIA', 'population': '8776110', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '430',
         'average_electrical_power_per_capita_expressed_in_watts': '49'},
        {'rank': '133', 'country_region': 'Senegal', 'total_electricity_consumption_in_gwh_per_year': '3842',
         'year_of_data': '2018', 'source': 'EIA', 'population': '16296360', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '236',
         'average_electrical_power_per_capita_expressed_in_watts': '27'},
        {'rank': '134', 'country_region': 'Kosovo', 'total_electricity_consumption_in_gwh_per_year': '5715',
         'year_of_data': '2019', 'source': 'EIA', 'population': '1794250', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3185',
         'average_electrical_power_per_capita_expressed_in_watts': '363'},
        {'rank': '135', 'country_region': 'Montenegro', 'total_electricity_consumption_in_gwh_per_year': '2998',
         'year_of_data': '2018', 'source': 'EIA', 'population': '622140', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4818',
         'average_electrical_power_per_capita_expressed_in_watts': '550'},
        {'rank': '136', 'country_region': 'Jamaica', 'total_electricity_consumption_in_gwh_per_year': '3025',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2948280', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1026',
         'average_electrical_power_per_capita_expressed_in_watts': '117'},
        {'rank': '137', 'country_region': 'Uganda', 'total_electricity_consumption_in_gwh_per_year': '3534',
         'year_of_data': '2018', 'source': 'EIA', 'population': '44269590', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '80',
         'average_electrical_power_per_capita_expressed_in_watts': '9'},
        {'rank': '138', 'country_region': 'Mauritius', 'total_electricity_consumption_in_gwh_per_year': '2800',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1265710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2212',
         'average_electrical_power_per_capita_expressed_in_watts': '252'},
        {'rank': '139', 'country_region': 'Gabon', 'total_electricity_consumption_in_gwh_per_year': '2230',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2172580', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1027',
         'average_electrical_power_per_capita_expressed_in_watts': '117'},
        {'rank': '140', 'country_region': 'Bhutan', 'total_electricity_consumption_in_gwh_per_year': '2386',
         'year_of_data': '2018', 'source': 'EIA', 'population': '763090', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3126',
         'average_electrical_power_per_capita_expressed_in_watts': '357'},
        {'rank': '141', 'country_region': 'New Caledonia', 'total_electricity_consumption_in_gwh_per_year': '2741',
         'year_of_data': '2018', 'source': 'EIA', 'population': '287800', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9524',
         'average_electrical_power_per_capita_expressed_in_watts': '1086'},
        {'rank': '142', 'country_region': 'Malta', 'total_electricity_consumption_in_gwh_per_year': '2456',
         'year_of_data': '2019', 'source': 'EIA', 'population': '502650', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4886',
         'average_electrical_power_per_capita_expressed_in_watts': '557'},
        {'rank': '143', 'country_region': 'Suriname', 'total_electricity_consumption_in_gwh_per_year': '1663',
         'year_of_data': '2018', 'source': 'EIA', 'population': '581360', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2861',
         'average_electrical_power_per_capita_expressed_in_watts': '326'},
        {'rank': '144', 'country_region': 'Malawi', 'total_electricity_consumption_in_gwh_per_year': '1515',
         'year_of_data': '2018', 'source': 'EIA', 'population': '18628750', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '81',
         'average_electrical_power_per_capita_expressed_in_watts': '9'},
        {'rank': '145', 'country_region': 'Bahamas', 'total_electricity_consumption_in_gwh_per_year': '1770',
         'year_of_data': '2018', 'source': 'EIA', 'population': '389480', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4545',
         'average_electrical_power_per_capita_expressed_in_watts': '518'},
        {'rank': '146', 'country_region': 'Guam', 'total_electricity_consumption_in_gwh_per_year': '1639',
         'year_of_data': '2018', 'source': 'EIA', 'population': '167290', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9797',
         'average_electrical_power_per_capita_expressed_in_watts': '1118'},
        {'rank': '147', 'country_region': 'Swaziland', 'total_electricity_consumption_in_gwh_per_year': '1682',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1148130', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1465',
         'average_electrical_power_per_capita_expressed_in_watts': '167'},
        {'rank': '148', 'country_region': 'Mali', 'total_electricity_consumption_in_gwh_per_year': '3040',
         'year_of_data': '2018', 'source': 'EIA', 'population': '19658030', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '155',
         'average_electrical_power_per_capita_expressed_in_watts': '18'},
        {'rank': '149', 'country_region': 'Liechtenstein', 'total_electricity_consumption_in_gwh_per_year': '394',
         'year_of_data': '2015', 'source': 'CIA', 'population': '38020', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '10352',
         'average_electrical_power_per_capita_expressed_in_watts': '1181'},
        {'rank': '150', 'country_region': 'Madagascar', 'total_electricity_consumption_in_gwh_per_year': '2117',
         'year_of_data': '2018', 'source': 'EIA', 'population': '26969310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '78',
         'average_electrical_power_per_capita_expressed_in_watts': '9'},
        {'rank': '151', 'country_region': 'Burkina Faso', 'total_electricity_consumption_in_gwh_per_year': '1760',
         'year_of_data': '2018', 'source': 'EIA', 'population': '20321380', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '87',
         'average_electrical_power_per_capita_expressed_in_watts': '10'},
        {'rank': '152', 'country_region': 'Niger', 'total_electricity_consumption_in_gwh_per_year': '1586',
         'year_of_data': '2018', 'source': 'EIA', 'population': '23310720', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '68',
         'average_electrical_power_per_capita_expressed_in_watts': '8'},
        {'rank': '153', 'country_region': 'Togo', 'total_electricity_consumption_in_gwh_per_year': '1251',
         'year_of_data': '2018', 'source': 'EIA', 'population': '8082370', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '155',
         'average_electrical_power_per_capita_expressed_in_watts': '18'},
        {'rank': '154', 'country_region': 'Benin', 'total_electricity_consumption_in_gwh_per_year': '1188',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11801150', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '101',
         'average_electrical_power_per_capita_expressed_in_watts': '11'},
        {'rank': '155', 'country_region': 'Curacao', 'total_electricity_consumption_in_gwh_per_year': '900',
         'year_of_data': '2008', 'source': 'EIA', 'population': '157540', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5713',
         'average_electrical_power_per_capita_expressed_in_watts': '652'},
        {'rank': '156', 'country_region': 'Congo, Republic of the',
         'total_electricity_consumption_in_gwh_per_year': '2018', 'year_of_data': '2018', 'source': 'EIA',
         'population': '5380510', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '375',
         'average_electrical_power_per_capita_expressed_in_watts': '43'},
        {'rank': '157', 'country_region': 'Guinea', 'total_electricity_consumption_in_gwh_per_year': '1983',
         'year_of_data': '2018', 'source': 'EIA', 'population': '12771250', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '155',
         'average_electrical_power_per_capita_expressed_in_watts': '18'},
        {'rank': '158', 'country_region': 'Barbados', 'total_electricity_consumption_in_gwh_per_year': '990',
         'year_of_data': '2018', 'source': 'EIA', 'population': '287020', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3450',
         'average_electrical_power_per_capita_expressed_in_watts': '394'},
        {'rank': '159', 'country_region': 'Mauritania', 'total_electricity_consumption_in_gwh_per_year': '882',
         'year_of_data': '2018', 'source': 'EIA', 'population': '4525700', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '195',
         'average_electrical_power_per_capita_expressed_in_watts': '22'},
        {'rank': '160', 'country_region': 'Lesotho', 'total_electricity_consumption_in_gwh_per_year': '902',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2125270', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '424',
         'average_electrical_power_per_capita_expressed_in_watts': '48'},
        {'rank': '161', 'country_region': 'Guyana', 'total_electricity_consumption_in_gwh_per_year': '851',
         'year_of_data': '2018', 'source': 'EIA', 'population': '782770', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1087',
         'average_electrical_power_per_capita_expressed_in_watts': '124'},
        {'rank': '162', 'country_region': 'Fiji', 'total_electricity_consumption_in_gwh_per_year': '997',
         'year_of_data': '2018', 'source': 'EIA', 'population': '889950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1120',
         'average_electrical_power_per_capita_expressed_in_watts': '128'},
        {'rank': '163', 'country_region': 'Aruba', 'total_electricity_consumption_in_gwh_per_year': '899',
         'year_of_data': '2018', 'source': 'EIA', 'population': '106310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8457',
         'average_electrical_power_per_capita_expressed_in_watts': '965'},
        {'rank': '164', 'country_region': 'French Polynesia', 'total_electricity_consumption_in_gwh_per_year': '544',
         'year_of_data': '2018', 'source': 'EIA', 'population': '279290', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1946',
         'average_electrical_power_per_capita_expressed_in_watts': '222'},
        {'rank': '165', 'country_region': 'South Sudan', 'total_electricity_consumption_in_gwh_per_year': '529',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11062110', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '48',
         'average_electrical_power_per_capita_expressed_in_watts': '5'},
        {'rank': '166', 'country_region': 'Jersey', 'total_electricity_consumption_in_gwh_per_year': '600',
         'year_of_data': '2004', 'source': 'EIA', 'population': '98069', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6425',
         'average_electrical_power_per_capita_expressed_in_watts': '733'},
        {'rank': '167', 'country_region': 'Bermuda', 'total_electricity_consumption_in_gwh_per_year': '560',
         'year_of_data': '2018', 'source': 'EIA', 'population': '63920', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8759',
         'average_electrical_power_per_capita_expressed_in_watts': '999'},
        {'rank': '168', 'country_region': 'Cayman Islands', 'total_electricity_consumption_in_gwh_per_year': '629',
         'year_of_data': '2019', 'source': 'EIA', 'population': '64950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9687',
         'average_electrical_power_per_capita_expressed_in_watts': '1105'},
        {'rank': '169', 'country_region': 'U.S. Virgin Islands', 'total_electricity_consumption_in_gwh_per_year': '553',
         'year_of_data': '2018', 'source': 'EIA', 'population': '106630', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5188',
         'average_electrical_power_per_capita_expressed_in_watts': '592'},
        {'rank': '170', 'country_region': 'Marshall Islands', 'total_electricity_consumption_in_gwh_per_year': '562.40',
         'year_of_data': '2014', 'source': 'EIA', 'population': '58790', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '9566',
         'average_electrical_power_per_capita_expressed_in_watts': '1091'},
        {'rank': '171', 'country_region': 'Andorra', 'total_electricity_consumption_in_gwh_per_year': '500',
         'year_of_data': '2012', 'source': 'EIA', 'population': '77140', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6482',
         'average_electrical_power_per_capita_expressed_in_watts': '739'},
        {'rank': '172', 'country_region': 'Rwanda', 'total_electricity_consumption_in_gwh_per_year': '764',
         'year_of_data': '2018', 'source': 'EIA', 'population': '12626950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '61',
         'average_electrical_power_per_capita_expressed_in_watts': '7'},
        {'rank': '173', 'country_region': 'Burundi', 'total_electricity_consumption_in_gwh_per_year': '339',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11530580', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '29',
         'average_electrical_power_per_capita_expressed_in_watts': '3'},
        {'rank': '174', 'country_region': 'Belize', 'total_electricity_consumption_in_gwh_per_year': '568',
         'year_of_data': '2018', 'source': 'EIA', 'population': '390350', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1454',
         'average_electrical_power_per_capita_expressed_in_watts': '166'},
        {'rank': '175', 'country_region': 'Djibouti', 'total_electricity_consumption_in_gwh_per_year': '381',
         'year_of_data': '2018', 'source': 'EIA', 'population': '973560', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '391',
         'average_electrical_power_per_capita_expressed_in_watts': '45'},
        {'rank': '176', 'country_region': 'Haiti', 'total_electricity_consumption_in_gwh_per_year': '359',
         'year_of_data': '2018', 'source': 'EIA', 'population': '11263080', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '32',
         'average_electrical_power_per_capita_expressed_in_watts': '4'},
        {'rank': '177', 'country_region': 'Seychelles', 'total_electricity_consumption_in_gwh_per_year': '403',
         'year_of_data': '2018', 'source': 'EIA', 'population': '97630', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4125',
         'average_electrical_power_per_capita_expressed_in_watts': '471'},
        {'rank': '178', 'country_region': 'Somalia', 'total_electricity_consumption_in_gwh_per_year': '323',
         'year_of_data': '2018', 'source': 'EIA', 'population': '15442910', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '21',
         'average_electrical_power_per_capita_expressed_in_watts': '2'},
        {'rank': '179', 'country_region': 'Saint Lucia', 'total_electricity_consumption_in_gwh_per_year': '352',
         'year_of_data': '2018', 'source': 'EIA', 'population': '182790', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1924',
         'average_electrical_power_per_capita_expressed_in_watts': '219'},
        {'rank': '180', 'country_region': 'Antigua and Barbuda', 'total_electricity_consumption_in_gwh_per_year': '314',
         'year_of_data': '2018', 'source': 'EIA', 'population': '97120', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3237',
         'average_electrical_power_per_capita_expressed_in_watts': '369'},
        {'rank': '181', 'country_region': 'Cabo Verde', 'total_electricity_consumption_in_gwh_per_year': '455',
         'year_of_data': '2018', 'source': 'EIA', 'population': '549930', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '827',
         'average_electrical_power_per_capita_expressed_in_watts': '94'},
        {'rank': '182', 'country_region': 'Eritrea', 'total_electricity_consumption_in_gwh_per_year': '408',
         'year_of_data': '2018', 'source': 'EIA', 'population': '3213970', 'as_of': '2011',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '127',
         'average_electrical_power_per_capita_expressed_in_watts': '14'},
        {'rank': '183', 'country_region': 'Faroe Islands', 'total_electricity_consumption_in_gwh_per_year': '316',
         'year_of_data': '2019', 'source': 'EIA', 'population': '48680', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '6492',
         'average_electrical_power_per_capita_expressed_in_watts': '741'},
        {'rank': '184', 'country_region': 'Gambia', 'total_electricity_consumption_in_gwh_per_year': '291',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2347710', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '124',
         'average_electrical_power_per_capita_expressed_in_watts': '14'},
        {'rank': '185', 'country_region': 'Greenland', 'total_electricity_consumption_in_gwh_per_year': '496',
         'year_of_data': '2018', 'source': 'EIA', 'population': '56230', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '8812',
         'average_electrical_power_per_capita_expressed_in_watts': '1005'},
        {'rank': '186', 'country_region': 'Liberia', 'total_electricity_consumption_in_gwh_per_year': '348',
         'year_of_data': '2018', 'source': 'EIA', 'population': '4937370', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '70',
         'average_electrical_power_per_capita_expressed_in_watts': '8'},
        {'rank': '187', 'country_region': 'Maldives', 'total_electricity_consumption_in_gwh_per_year': '565',
         'year_of_data': '2018', 'source': 'EIA', 'population': '530950', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1064',
         'average_electrical_power_per_capita_expressed_in_watts': '121'},
        {'rank': '188', 'country_region': 'Northern Mariana Islands',
         'total_electricity_consumption_in_gwh_per_year': '200', 'year_of_data': '2012', 'source': 'EIA',
         'population': '57220', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3495',
         'average_electrical_power_per_capita_expressed_in_watts': '399'},
        {'rank': '189', 'country_region': 'Chad', 'total_electricity_consumption_in_gwh_per_year': '213',
         'year_of_data': '2018', 'source': 'EIA', 'population': '15946880', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '13',
         'average_electrical_power_per_capita_expressed_in_watts': '2'},
        {'rank': '190', 'country_region': 'Saint Kitts and Nevis',
         'total_electricity_consumption_in_gwh_per_year': '184', 'year_of_data': '2018', 'source': 'EIA',
         'population': '52830', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3478',
         'average_electrical_power_per_capita_expressed_in_watts': '397'},
        {'rank': '191', 'country_region': 'Central African Republic',
         'total_electricity_consumption_in_gwh_per_year': '140', 'year_of_data': '2018', 'source': 'EIA',
         'population': '4745190', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '30',
         'average_electrical_power_per_capita_expressed_in_watts': '3'},
        {'rank': '192', 'country_region': 'Sierra Leone', 'total_electricity_consumption_in_gwh_per_year': '242',
         'year_of_data': '2018', 'source': 'EIA', 'population': '7813220', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '31',
         'average_electrical_power_per_capita_expressed_in_watts': '4'},
        {'rank': '193', 'country_region': 'Turks and Caicos Islands',
         'total_electricity_consumption_in_gwh_per_year': '186', 'year_of_data': '2018', 'source': 'EIA',
         'population': '38190', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4870',
         'average_electrical_power_per_capita_expressed_in_watts': '556'},
        {'rank': '194', 'country_region': 'Gibraltar', 'total_electricity_consumption_in_gwh_per_year': '196',
         'year_of_data': '2018', 'source': 'EIA', 'population': '33700', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '5803',
         'average_electrical_power_per_capita_expressed_in_watts': '662'},
        {'rank': '195', 'country_region': 'Grenada', 'total_electricity_consumption_in_gwh_per_year': '198',
         'year_of_data': '2018', 'source': 'EIA', 'population': '112000', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1772',
         'average_electrical_power_per_capita_expressed_in_watts': '202'},
        {'rank': '196', 'country_region': 'Micronesia, Federated States of',
         'total_electricity_consumption_in_gwh_per_year': '125', 'year_of_data': '2002', 'source': 'EIA',
         'population': '113810', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1101',
         'average_electrical_power_per_capita_expressed_in_watts': '126'},
        {'rank': '197', 'country_region': 'Timor-Leste', 'total_electricity_consumption_in_gwh_per_year': '100',
         'year_of_data': '2014', 'source': 'EIA', 'population': '1293120', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '77',
         'average_electrical_power_per_capita_expressed_in_watts': '9'},
        {'rank': '198', 'country_region': 'British Virgin Islands',
         'total_electricity_consumption_in_gwh_per_year': '94', 'year_of_data': '2018', 'source': 'EIA',
         'population': '30030', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3145',
         'average_electrical_power_per_capita_expressed_in_watts': '359'},
        {'rank': '199', 'country_region': 'Saint Vincent and the Grenadines',
         'total_electricity_consumption_in_gwh_per_year': '133', 'year_of_data': '2018', 'source': 'EIA',
         'population': '110590', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1203',
         'average_electrical_power_per_capita_expressed_in_watts': '137'},
        {'rank': '200', 'country_region': 'American Samoa', 'total_electricity_consumption_in_gwh_per_year': '152',
         'year_of_data': '2018', 'source': 'EIA', 'population': '55310', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2741',
         'average_electrical_power_per_capita_expressed_in_watts': '313'},
        {'rank': '201', 'country_region': 'Samoa', 'total_electricity_consumption_in_gwh_per_year': '124',
         'year_of_data': '2018', 'source': 'EIA', 'population': '197100', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '627',
         'average_electrical_power_per_capita_expressed_in_watts': '72'},
        {'rank': '202', 'country_region': 'Equatorial Guinea', 'total_electricity_consumption_in_gwh_per_year': '1321',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1355990', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '975',
         'average_electrical_power_per_capita_expressed_in_watts': '111'},
        {'rank': '203', 'country_region': 'Dominica', 'total_electricity_consumption_in_gwh_per_year': '59.69',
         'year_of_data': '2019', 'source': 'EIA', 'population': '71810', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '831',
         'average_electrical_power_per_capita_expressed_in_watts': '95'},
        {'rank': '204', 'country_region': 'Solomon Islands', 'total_electricity_consumption_in_gwh_per_year': '98.26',
         'year_of_data': '2018', 'source': 'EIA', 'population': '669820', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '147',
         'average_electrical_power_per_capita_expressed_in_watts': '17'},
        {'rank': '205', 'country_region': 'Sao Tome and Principe',
         'total_electricity_consumption_in_gwh_per_year': '80.91', 'year_of_data': '2018', 'source': 'EIA',
         'population': '215060', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '376',
         'average_electrical_power_per_capita_expressed_in_watts': '43'},
        {'rank': '206', 'country_region': 'Vanuatu', 'total_electricity_consumption_in_gwh_per_year': '65.19',
         'year_of_data': '2018', 'source': 'EIA', 'population': '299880', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '217',
         'average_electrical_power_per_capita_expressed_in_watts': '25'},
        {'rank': '207', 'country_region': 'Tonga', 'total_electricity_consumption_in_gwh_per_year': '51.15',
         'year_of_data': '2018', 'source': 'EIA', 'population': '104490', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '490',
         'average_electrical_power_per_capita_expressed_in_watts': '56'},
        {'rank': '208', 'country_region': 'Saint Pierre and Miquelon',
         'total_electricity_consumption_in_gwh_per_year': '44.64', 'year_of_data': '2018', 'source': 'EIA',
         'population': '850890', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '7479',
         'average_electrical_power_per_capita_expressed_in_watts': '853'},
        {'rank': '209', 'country_region': 'Comoros', 'total_electricity_consumption_in_gwh_per_year': '93.37',
         'year_of_data': '2018', 'source': 'EIA', 'population': '850890', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '110',
         'average_electrical_power_per_capita_expressed_in_watts': '13'},
        {'rank': '210', 'country_region': 'Guinea-Bissau', 'total_electricity_consumption_in_gwh_per_year': '39.06',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1920920', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '20',
         'average_electrical_power_per_capita_expressed_in_watts': '2'},
        {'rank': '211', 'country_region': 'Cook Islands', 'total_electricity_consumption_in_gwh_per_year': '38.81',
         'year_of_data': '2018', 'source': 'EIA', 'population': '9556', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3308',
         'average_electrical_power_per_capita_expressed_in_watts': '377'},
        {'rank': '212', 'country_region': 'Kiribati', 'total_electricity_consumption_in_gwh_per_year': '27.75',
         'year_of_data': '2018', 'source': 'EIA', 'population': '117610', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '236',
         'average_electrical_power_per_capita_expressed_in_watts': '27'},
        {'rank': '213', 'country_region': 'Nauru', 'total_electricity_consumption_in_gwh_per_year': '32.55',
         'year_of_data': '2018', 'source': 'EIA', 'population': '12580', 'as_of': '2019',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '2587',
         'average_electrical_power_per_capita_expressed_in_watts': '295'},
        {'rank': '214', 'country_region': 'Montserrat', 'total_electricity_consumption_in_gwh_per_year': '14.88',
         'year_of_data': '2018', 'source': 'EIA', 'population': '5267', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4061',
         'average_electrical_power_per_capita_expressed_in_watts': '463'},
        {'rank': '215', 'country_region': 'Falkland Islands', 'total_electricity_consumption_in_gwh_per_year': '18.32',
         'year_of_data': '2018', 'source': 'EIA', 'population': '2931', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '4759',
         'average_electrical_power_per_capita_expressed_in_watts': '543'},
        {'rank': '216', 'country_region': 'Saint Helena, Ascension and Tristan da Cunha',
         'total_electricity_consumption_in_gwh_per_year': '2.79', 'year_of_data': '2018', 'source': 'EIA',
         'population': '7795', 'as_of': '2016', 'average_electrical_power_per_capita_expressed_in_kwh_per_year': '3126',
         'average_electrical_power_per_capita_expressed_in_watts': '357'},
        {'rank': '217', 'country_region': 'Niue', 'total_electricity_consumption_in_gwh_per_year': '7.44',
         'year_of_data': '2018', 'source': 'EIA', 'population': '1190', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '1193',
         'average_electrical_power_per_capita_expressed_in_watts': '136'},
        {'rank': '218', 'country_region': 'Gaza Strip', 'total_electricity_consumption_in_gwh_per_year': '202',
         'year_of_data': '2009', 'source': 'CIA', 'population': '1753327', 'as_of': '2016',
         'average_electrical_power_per_capita_expressed_in_kwh_per_year': '0.1',
         'average_electrical_power_per_capita_expressed_in_watts': '0.01'}
    ]

    return data
