# Get the list of chemical elements
def get_the_list_of_chemical_elements():
    data = [
        {'element': {'atomic_number': '1', 'symbol': 'H', 'name': 'Hydrogen'},
         'origin_of_name': "Greek elements hydro- and -gen 'water-forming'", 'group': '1', 'period': '1',
         'block': 's-block', 'standard_atomic_weight': '1.0080', 'density': '0.00008988', 'melting_point': '14.01',
         'boiling_point': '20.28', 'specific_heat_capacity': '14.304', 'electronegativity': '2.20',
         'abundance_in_earth_crust': '1400', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '2', 'symbol': 'He', 'name': 'Helium'}, 'origin_of_name': "Greek hḗlios 'sun'",
         'group': '18', 'period': '1', 'block': 's-block', 'standard_atomic_weight': '4.0026', 'density': '0.0001785',
         'melting_point': '–[k]', 'boiling_point': '4.22', 'specific_heat_capacity': '5.193', 'electronegativity': '–',
         'abundance_in_earth_crust': '0.008', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '3', 'symbol': 'Li', 'name': 'Lithium'}, 'origin_of_name': "Greek líthos 'stone'",
         'group': '1', 'period': '2', 'block': 's-block', 'standard_atomic_weight': '6.94', 'density': '0.534',
         'melting_point': '453.69', 'boiling_point': '1560', 'specific_heat_capacity': '3.582',
         'electronegativity': '0.98', 'abundance_in_earth_crust': '20', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '4', 'symbol': 'Be', 'name': 'Beryllium'},
         'origin_of_name': 'Beryl a mineral (ultimately from the name of Belur in southern India)[4]', 'group': '2',
         'period': '2', 'block': 's-block', 'standard_atomic_weight': '9.0122', 'density': '1.85',
         'melting_point': '1560', 'boiling_point': '2742', 'specific_heat_capacity': '1.825',
         'electronegativity': '1.57', 'abundance_in_earth_crust': '2.8', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '5', 'symbol': 'B', 'name': 'Boron'},
         'origin_of_name': 'Borax a mineral (from Arabic bawraq Middle Persian *bōrag)', 'group': '13', 'period': '2',
         'block': 'p-block', 'standard_atomic_weight': '10.81', 'density': '2.34', 'melting_point': '2349',
         'boiling_point': '4200', 'specific_heat_capacity': '1.026', 'electronegativity': '2.04',
         'abundance_in_earth_crust': '10', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '6', 'symbol': 'C', 'name': 'Carbon'}, 'origin_of_name': "Latin carbo 'coal'",
         'group': '14', 'period': '2', 'block': 'p-block', 'standard_atomic_weight': '12.011', 'density': '2.267',
         'melting_point': '>4000', 'boiling_point': '4300', 'specific_heat_capacity': '0.709',
         'electronegativity': '2.55', 'abundance_in_earth_crust': '200', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '7', 'symbol': 'N', 'name': 'Nitrogen'},
         'origin_of_name': "Greek nítron and -gen 'niter-forming'", 'group': '15', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '14.007', 'density': '0.0012506', 'melting_point': '63.15', 'boiling_point': '77.36',
         'specific_heat_capacity': '1.04', 'electronegativity': '3.04', 'abundance_in_earth_crust': '19',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '8', 'symbol': 'O', 'name': 'Oxygen'},
         'origin_of_name': "Greek oxy- and -gen 'acid-forming'", 'group': '16', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '15.999', 'density': '0.001429', 'melting_point': '54.36', 'boiling_point': '90.20',
         'specific_heat_capacity': '0.918', 'electronegativity': '3.44', 'abundance_in_earth_crust': '461000',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '9', 'symbol': 'F', 'name': 'Fluorine'},
         'origin_of_name': "Latin fluere 'to flow'", 'group': '17', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '18.998', 'density': '0.001696', 'melting_point': '53.53', 'boiling_point': '85.03',
         'specific_heat_capacity': '0.824', 'electronegativity': '3.98', 'abundance_in_earth_crust': '585',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '10', 'symbol': 'Ne', 'name': 'Neon'}, 'origin_of_name': "Greek néon 'new'",
         'group': '18', 'period': '2', 'block': 'p-block', 'standard_atomic_weight': '20.180', 'density': '0.0009002',
         'melting_point': '24.56', 'boiling_point': '27.07', 'specific_heat_capacity': '1.03', 'electronegativity': '–',
         'abundance_in_earth_crust': '0.005', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '11', 'symbol': 'Na', 'name': 'Sodium'},
         'origin_of_name': "English (from medieval Latin) soda\xa0· \xa0Symbol Na is derived from New Latin natrium coined from German Natron 'natron'",
         'group': '1', 'period': '3', 'block': 's-block', 'standard_atomic_weight': '22.990', 'density': '0.968',
         'melting_point': '370.87', 'boiling_point': '1156', 'specific_heat_capacity': '1.228',
         'electronegativity': '0.93', 'abundance_in_earth_crust': '23600', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '12', 'symbol': 'Mg', 'name': 'Magnesium'},
         'origin_of_name': 'Magnesia a district of Eastern Thessaly in Greece', 'group': '2', 'period': '3',
         'block': 's-block', 'standard_atomic_weight': '24.305', 'density': '1.738', 'melting_point': '923',
         'boiling_point': '1363', 'specific_heat_capacity': '1.023', 'electronegativity': '1.31',
         'abundance_in_earth_crust': '23300', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '13', 'symbol': 'Al', 'name': 'Aluminium'},
         'origin_of_name': "Alumina from Latin alumen (gen. aluminis) 'bitter salt alum'", 'group': '13', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '26.982', 'density': '2.70', 'melting_point': '933.47',
         'boiling_point': '2792', 'specific_heat_capacity': '0.897', 'electronegativity': '1.61',
         'abundance_in_earth_crust': '82300', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '14', 'symbol': 'Si', 'name': 'Silicon'},
         'origin_of_name': "Latin silex 'flint' (originally silicium)", 'group': '14', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '28.085', 'density': '2.3290', 'melting_point': '1687',
         'boiling_point': '3538', 'specific_heat_capacity': '0.705', 'electronegativity': '1.9',
         'abundance_in_earth_crust': '282000', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '15', 'symbol': 'P', 'name': 'Phosphorus'},
         'origin_of_name': "Greek phōsphóros 'light-bearing'", 'group': '15', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '30.974', 'density': '1.823', 'melting_point': '317.30', 'boiling_point': '550',
         'specific_heat_capacity': '0.769', 'electronegativity': '2.19', 'abundance_in_earth_crust': '1050',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '16', 'symbol': 'S', 'name': 'Sulfur'},
         'origin_of_name': "Latin sulphur 'brimstone'", 'group': '16', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '32.06', 'density': '2.07', 'melting_point': '388.36', 'boiling_point': '717.87',
         'specific_heat_capacity': '0.71', 'electronegativity': '2.58', 'abundance_in_earth_crust': '350',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '17', 'symbol': 'Cl', 'name': 'Chlorine'},
         'origin_of_name': "Greek chlōrós 'greenish yellow'", 'group': '17', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '35.45', 'density': '0.0032', 'melting_point': '171.6', 'boiling_point': '239.11',
         'specific_heat_capacity': '0.479', 'electronegativity': '3.16', 'abundance_in_earth_crust': '145',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '18', 'symbol': 'Ar', 'name': 'Argon'},
         'origin_of_name': "Greek argós 'idle' (because of its inertness)", 'group': '18', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '39.95', 'density': '0.001784', 'melting_point': '83.80',
         'boiling_point': '87.30', 'specific_heat_capacity': '0.52', 'electronegativity': '–',
         'abundance_in_earth_crust': '3.5', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '19', 'symbol': 'K', 'name': 'Potassium'},
         'origin_of_name': "New Latin potassa 'potash' itself from pot and ash\xa0· \xa0Symbol K is derived from Latin kalium",
         'group': '1', 'period': '4', 'block': 's-block', 'standard_atomic_weight': '39.098', 'density': '0.89',
         'melting_point': '336.53', 'boiling_point': '1032', 'specific_heat_capacity': '0.757',
         'electronegativity': '0.82', 'abundance_in_earth_crust': '20900', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '20', 'symbol': 'Ca', 'name': 'Calcium'}, 'origin_of_name': "Latin calx 'lime'",
         'group': '2', 'period': '4', 'block': 's-block', 'standard_atomic_weight': '40.078', 'density': '1.55',
         'melting_point': '1115', 'boiling_point': '1757', 'specific_heat_capacity': '0.647',
         'electronegativity': '1.00', 'abundance_in_earth_crust': '41500', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '21', 'symbol': 'Sc', 'name': 'Scandium'},
         'origin_of_name': "Latin Scandia 'Scandinavia'", 'group': '3', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '44.956', 'density': '2.985', 'melting_point': '1814', 'boiling_point': '3109',
         'specific_heat_capacity': '0.568', 'electronegativity': '1.36', 'abundance_in_earth_crust': '22',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '22', 'symbol': 'Ti', 'name': 'Titanium'},
         'origin_of_name': 'Titans the sons of the Earth goddess of Greek mythology', 'group': '4', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '47.867', 'density': '4.506', 'melting_point': '1941',
         'boiling_point': '3560', 'specific_heat_capacity': '0.523', 'electronegativity': '1.54',
         'abundance_in_earth_crust': '5650', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '23', 'symbol': 'V', 'name': 'Vanadium'},
         'origin_of_name': 'Vanadis an Old Norse name for the Scandinavian goddess Freyja', 'group': '5', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '50.942', 'density': '6.11', 'melting_point': '2183',
         'boiling_point': '3680', 'specific_heat_capacity': '0.489', 'electronegativity': '1.63',
         'abundance_in_earth_crust': '120', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '24', 'symbol': 'Cr', 'name': 'Chromium'},
         'origin_of_name': "Greek chróma 'colour'", 'group': '6', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '51.996', 'density': '7.15', 'melting_point': '2180', 'boiling_point': '2944',
         'specific_heat_capacity': '0.449', 'electronegativity': '1.66', 'abundance_in_earth_crust': '102',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '25', 'symbol': 'Mn', 'name': 'Manganese'},
         'origin_of_name': 'Corrupted from magnesia negra; see §\xa0magnesium', 'group': '7', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '54.938', 'density': '7.21', 'melting_point': '1519',
         'boiling_point': '2334', 'specific_heat_capacity': '0.479', 'electronegativity': '1.55',
         'abundance_in_earth_crust': '950', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '26', 'symbol': 'Fe', 'name': 'Iron'},
         'origin_of_name': "English word from Proto-Celtic *īsarnom ('iron') from a root meaning 'blood'\xa0· \xa0Symbol Fe is derived from Latin ferrum",
         'group': '8', 'period': '4', 'block': 'd-block', 'standard_atomic_weight': '55.845', 'density': '7.874',
         'melting_point': '1811', 'boiling_point': '3134', 'specific_heat_capacity': '0.449',
         'electronegativity': '1.83', 'abundance_in_earth_crust': '56300', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '27', 'symbol': 'Co', 'name': 'Cobalt'},
         'origin_of_name': "German Kobold 'goblin'", 'group': '9', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '58.933', 'density': '8.90', 'melting_point': '1768', 'boiling_point': '3200',
         'specific_heat_capacity': '0.421', 'electronegativity': '1.88', 'abundance_in_earth_crust': '25',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '28', 'symbol': 'Ni', 'name': 'Nickel'},
         'origin_of_name': 'Nickel a mischievous sprite of German miner mythology', 'group': '10', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '58.693', 'density': '8.908', 'melting_point': '1728',
         'boiling_point': '3186', 'specific_heat_capacity': '0.444', 'electronegativity': '1.91',
         'abundance_in_earth_crust': '84', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '29', 'symbol': 'Cu', 'name': 'Copper'},
         'origin_of_name': "English word from Latin cuprum from Ancient Greek Kýpros 'Cyprus'", 'group': '11',
         'period': '4', 'block': 'd-block', 'standard_atomic_weight': '63.546', 'density': '8.96',
         'melting_point': '1357.77', 'boiling_point': '2835', 'specific_heat_capacity': '0.385',
         'electronegativity': '1.90', 'abundance_in_earth_crust': '60', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '30', 'symbol': 'Zn', 'name': 'Zinc'},
         'origin_of_name': "Most likely from German Zinke 'prong' or 'tooth' though some suggest Persian sang 'stone'",
         'group': '12', 'period': '4', 'block': 'd-block', 'standard_atomic_weight': '65.38', 'density': '7.14',
         'melting_point': '692.88', 'boiling_point': '1180', 'specific_heat_capacity': '0.388',
         'electronegativity': '1.65', 'abundance_in_earth_crust': '70', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '31', 'symbol': 'Ga', 'name': 'Gallium'},
         'origin_of_name': "Latin Gallia 'France'", 'group': '13', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '69.723', 'density': '5.91', 'melting_point': '302.9146', 'boiling_point': '2673',
         'specific_heat_capacity': '0.371', 'electronegativity': '1.81', 'abundance_in_earth_crust': '19',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '32', 'symbol': 'Ge', 'name': 'Germanium'},
         'origin_of_name': "Latin Germania 'Germany'", 'group': '14', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '72.630', 'density': '5.323', 'melting_point': '1211.40', 'boiling_point': '3106',
         'specific_heat_capacity': '0.32', 'electronegativity': '2.01', 'abundance_in_earth_crust': '1.5',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '33', 'symbol': 'As', 'name': 'Arsenic'},
         'origin_of_name': "French arsenic from Greek arsenikón 'yellow arsenic' (influenced by arsenikós 'masculine' or 'virile') from a West Asian wanderword ultimately from Old Iranian *zarniya-ka 'golden'",
         'group': '15', 'period': '4', 'block': 'p-block', 'standard_atomic_weight': '74.922', 'density': '5.727',
         'melting_point': '1090[l]', 'boiling_point': '887', 'specific_heat_capacity': '0.329',
         'electronegativity': '2.18', 'abundance_in_earth_crust': '1.8', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '34', 'symbol': 'Se', 'name': 'Selenium'},
         'origin_of_name': "Greek selḗnē 'moon'", 'group': '16', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '78.971', 'density': '4.81', 'melting_point': '453', 'boiling_point': '958',
         'specific_heat_capacity': '0.321', 'electronegativity': '2.55', 'abundance_in_earth_crust': '0.05',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '35', 'symbol': 'Br', 'name': 'Bromine'},
         'origin_of_name': "Greek brômos 'stench'", 'group': '17', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '79.904', 'density': '3.1028', 'melting_point': '265.8', 'boiling_point': '332.0',
         'specific_heat_capacity': '0.474', 'electronegativity': '2.96', 'abundance_in_earth_crust': '2.4',
         'origin': 'primordial', 'phase_at_r_t': 'liquid'},
        {'element': {'atomic_number': '36', 'symbol': 'Kr', 'name': 'Krypton'},
         'origin_of_name': "Greek kryptós 'hidden'", 'group': '18', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '83.798', 'density': '0.003749', 'melting_point': '115.79',
         'boiling_point': '119.93', 'specific_heat_capacity': '0.248', 'electronegativity': '3.00',
         'abundance_in_earth_crust': '1×10−4', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '37', 'symbol': 'Rb', 'name': 'Rubidium'},
         'origin_of_name': "Latin rubidus 'deep red'", 'group': '1', 'period': '5', 'block': 's-block',
         'standard_atomic_weight': '85.468', 'density': '1.532', 'melting_point': '312.46', 'boiling_point': '961',
         'specific_heat_capacity': '0.363', 'electronegativity': '0.82', 'abundance_in_earth_crust': '90',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '38', 'symbol': 'Sr', 'name': 'Strontium'},
         'origin_of_name': 'Strontian a village in Scotland where it was found', 'group': '2', 'period': '5',
         'block': 's-block', 'standard_atomic_weight': '87.62', 'density': '2.64', 'melting_point': '1050',
         'boiling_point': '1655', 'specific_heat_capacity': '0.301', 'electronegativity': '0.95',
         'abundance_in_earth_crust': '370', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '39', 'symbol': 'Y', 'name': 'Yttrium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also terbium erbium ytterbium', 'group': '3',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '88.906', 'density': '4.472',
         'melting_point': '1799', 'boiling_point': '3609', 'specific_heat_capacity': '0.298',
         'electronegativity': '1.22', 'abundance_in_earth_crust': '33', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '40', 'symbol': 'Zr', 'name': 'Zirconium'},
         'origin_of_name': "Zircon a mineral from Persian zargun 'gold-hued'", 'group': '4', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '91.224', 'density': '6.52', 'melting_point': '2128',
         'boiling_point': '4682', 'specific_heat_capacity': '0.278', 'electronegativity': '1.33',
         'abundance_in_earth_crust': '165', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '41', 'symbol': 'Nb', 'name': 'Niobium'},
         'origin_of_name': 'Niobe daughter of king Tantalus from Greek mythology; see also tantalum', 'group': '5',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '92.906', 'density': '8.57',
         'melting_point': '2750', 'boiling_point': '5017', 'specific_heat_capacity': '0.265',
         'electronegativity': '1.6', 'abundance_in_earth_crust': '20', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '42', 'symbol': 'Mo', 'name': 'Molybdenum'},
         'origin_of_name': "Greek molýbdaina 'piece of lead' from mólybdos 'lead' due to confusion with lead ore galena (PbS)",
         'group': '6', 'period': '5', 'block': 'd-block', 'standard_atomic_weight': '95.95', 'density': '10.28',
         'melting_point': '2896', 'boiling_point': '4912', 'specific_heat_capacity': '0.251',
         'electronegativity': '2.16', 'abundance_in_earth_crust': '1.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '43', 'symbol': 'Tc', 'name': 'Technetium'},
         'origin_of_name': "Greek tekhnētós 'artificial'", 'group': '7', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '[97][a]', 'density': '11', 'melting_point': '2430', 'boiling_point': '4538',
         'specific_heat_capacity': '–', 'electronegativity': '1.9', 'abundance_in_earth_crust': '~\xa03×10−9',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '44', 'symbol': 'Ru', 'name': 'Ruthenium'},
         'origin_of_name': "New Latin Ruthenia 'Russia'", 'group': '8', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '101.07', 'density': '12.45', 'melting_point': '2607', 'boiling_point': '4423',
         'specific_heat_capacity': '0.238', 'electronegativity': '2.2', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '45', 'symbol': 'Rh', 'name': 'Rhodium'},
         'origin_of_name': "Greek rhodóeis 'rose-coloured' from rhódon 'rose'", 'group': '9', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '102.91', 'density': '12.41', 'melting_point': '2237',
         'boiling_point': '3968', 'specific_heat_capacity': '0.243', 'electronegativity': '2.28',
         'abundance_in_earth_crust': '0.001', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '46', 'symbol': 'Pd', 'name': 'Palladium'},
         'origin_of_name': 'Pallas an asteroid considered a planet at the time', 'group': '10', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '106.42', 'density': '12.023', 'melting_point': '1828.05',
         'boiling_point': '3236', 'specific_heat_capacity': '0.244', 'electronegativity': '2.20',
         'abundance_in_earth_crust': '0.015', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '47', 'symbol': 'Ag', 'name': 'Silver'},
         'origin_of_name': 'English word\xa0· \xa0Symbol Ag is derived from Latin argentum', 'group': '11',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '107.87', 'density': '10.49',
         'melting_point': '1234.93', 'boiling_point': '2435', 'specific_heat_capacity': '0.235',
         'electronegativity': '1.93', 'abundance_in_earth_crust': '0.075', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '48', 'symbol': 'Cd', 'name': 'Cadmium'},
         'origin_of_name': 'New Latin cadmia from King Kadmos', 'group': '12', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '112.41', 'density': '8.65', 'melting_point': '594.22', 'boiling_point': '1040',
         'specific_heat_capacity': '0.232', 'electronegativity': '1.69', 'abundance_in_earth_crust': '0.159',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '49', 'symbol': 'In', 'name': 'Indium'},
         'origin_of_name': "Latin indicum 'indigo' the blue colour found in its spectrum", 'group': '13', 'period': '5',
         'block': 'p-block', 'standard_atomic_weight': '114.82', 'density': '7.31', 'melting_point': '429.75',
         'boiling_point': '2345', 'specific_heat_capacity': '0.233', 'electronegativity': '1.78',
         'abundance_in_earth_crust': '0.25', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '50', 'symbol': 'Sn', 'name': 'Tin'},
         'origin_of_name': 'English word\xa0· \xa0Symbol Sn is derived from Latin stannum', 'group': '14',
         'period': '5', 'block': 'p-block', 'standard_atomic_weight': '118.71', 'density': '7.265',
         'melting_point': '505.08', 'boiling_point': '2875', 'specific_heat_capacity': '0.228',
         'electronegativity': '1.96', 'abundance_in_earth_crust': '2.3', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '51', 'symbol': 'Sb', 'name': 'Antimony'},
         'origin_of_name': "Latin antimonium the origin of which is uncertain: folk etymologies suggest it is derived from Greek antí ('against') + mónos ('alone') or Old French anti-moine 'Monk's bane' but it could plausibly be from or related to Arabic ʾiṯmid 'antimony' reformatted as a Latin word\xa0· \xa0Symbol Sb is derived from Latin stibium 'stibnite'",
         'group': '15', 'period': '5', 'block': 'p-block', 'standard_atomic_weight': '121.76', 'density': '6.697',
         'melting_point': '903.78', 'boiling_point': '1860', 'specific_heat_capacity': '0.207',
         'electronegativity': '2.05', 'abundance_in_earth_crust': '0.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '52', 'symbol': 'Te', 'name': 'Tellurium'},
         'origin_of_name': "Latin tellus 'the ground earth'", 'group': '16', 'period': '5', 'block': 'p-block',
         'standard_atomic_weight': '127.60', 'density': '6.24', 'melting_point': '722.66', 'boiling_point': '1261',
         'specific_heat_capacity': '0.202', 'electronegativity': '2.1', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '53', 'symbol': 'I', 'name': 'Iodine'},
         'origin_of_name': "French iode from Greek ioeidḗs 'violet'", 'group': '17', 'period': '5', 'block': 'p-block',
         'standard_atomic_weight': '126.90', 'density': '4.933', 'melting_point': '386.85', 'boiling_point': '457.4',
         'specific_heat_capacity': '0.214', 'electronegativity': '2.66', 'abundance_in_earth_crust': '0.45',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '54', 'symbol': 'Xe', 'name': 'Xenon'},
         'origin_of_name': "Greek xénon neuter form of xénos 'strange'", 'group': '18', 'period': '5',
         'block': 'p-block', 'standard_atomic_weight': '131.29', 'density': '0.005894', 'melting_point': '161.4',
         'boiling_point': '165.03', 'specific_heat_capacity': '0.158', 'electronegativity': '2.60',
         'abundance_in_earth_crust': '3×10−5', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '55', 'symbol': 'Cs', 'name': 'Caesium'},
         'origin_of_name': "Latin caesius 'sky-blue'", 'group': '1', 'period': '6', 'block': 's-block',
         'standard_atomic_weight': '132.91', 'density': '1.93', 'melting_point': '301.59', 'boiling_point': '944',
         'specific_heat_capacity': '0.242', 'electronegativity': '0.79', 'abundance_in_earth_crust': '3',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '56', 'symbol': 'Ba', 'name': 'Barium'}, 'origin_of_name': "Greek barýs 'heavy'",
         'group': '2', 'period': '6', 'block': 's-block', 'standard_atomic_weight': '137.33', 'density': '3.51',
         'melting_point': '1000', 'boiling_point': '2170', 'specific_heat_capacity': '0.204',
         'electronegativity': '0.89', 'abundance_in_earth_crust': '425', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '57', 'symbol': 'La', 'name': 'Lanthanum'},
         'origin_of_name': "Greek lanthánein 'to lie hidden'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '138.91', 'density': '6.162', 'melting_point': '1193', 'boiling_point': '3737',
         'specific_heat_capacity': '0.195', 'electronegativity': '1.1', 'abundance_in_earth_crust': '39',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '58', 'symbol': 'Ce', 'name': 'Cerium'},
         'origin_of_name': 'Ceres a dwarf planet considered a planet at the time', 'group': 'n/a', 'period': '6',
         'block': 'f-block', 'standard_atomic_weight': '140.12', 'density': '6.770', 'melting_point': '1068',
         'boiling_point': '3716', 'specific_heat_capacity': '0.192', 'electronegativity': '1.12',
         'abundance_in_earth_crust': '66.5', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '59', 'symbol': 'Pr', 'name': 'Praseodymium'},
         'origin_of_name': "Greek prásios dídymos 'green\xa0twin'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '140.91', 'density': '6.77', 'melting_point': '1208', 'boiling_point': '3793',
         'specific_heat_capacity': '0.193', 'electronegativity': '1.13', 'abundance_in_earth_crust': '9.2',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '60', 'symbol': 'Nd', 'name': 'Neodymium'},
         'origin_of_name': "Greek néos dídymos 'new\xa0twin'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '144.24', 'density': '7.01', 'melting_point': '1297', 'boiling_point': '3347',
         'specific_heat_capacity': '0.19', 'electronegativity': '1.14', 'abundance_in_earth_crust': '41.5',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '61', 'symbol': 'Pm', 'name': 'Promethium'},
         'origin_of_name': 'Prometheus a figure in Greek mythology', 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '[145]', 'density': '7.26', 'melting_point': '1315', 'boiling_point': '3273',
         'specific_heat_capacity': '–', 'electronegativity': '1.13', 'abundance_in_earth_crust': '2×10−19',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '62', 'symbol': 'Sm', 'name': 'Samarium'},
         'origin_of_name': 'Samarskite a mineral named after V. Samarsky-Bykhovets Russian mine official',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '150.36', 'density': '7.52',
         'melting_point': '1345', 'boiling_point': '2067', 'specific_heat_capacity': '0.197',
         'electronegativity': '1.17', 'abundance_in_earth_crust': '7.05', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '63', 'symbol': 'Eu', 'name': 'Europium'}, 'origin_of_name': 'Europe',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '151.96', 'density': '5.244',
         'melting_point': '1099', 'boiling_point': '1802', 'specific_heat_capacity': '0.182',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '2', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '64', 'symbol': 'Gd', 'name': 'Gadolinium'},
         'origin_of_name': 'Gadolinite a mineral named after Johan Gadolin Finnish chemist physicist and mineralogist',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '157.25', 'density': '7.90',
         'melting_point': '1585', 'boiling_point': '3546', 'specific_heat_capacity': '0.236',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '6.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '65', 'symbol': 'Tb', 'name': 'Terbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium erbium ytterbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '158.93', 'density': '8.23',
         'melting_point': '1629', 'boiling_point': '3503', 'specific_heat_capacity': '0.182',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '1.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '66', 'symbol': 'Dy', 'name': 'Dysprosium'},
         'origin_of_name': "Greek dysprósitos 'hard to get'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '162.50', 'density': '8.540', 'melting_point': '1680', 'boiling_point': '2840',
         'specific_heat_capacity': '0.17', 'electronegativity': '1.22', 'abundance_in_earth_crust': '5.2',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '67', 'symbol': 'Ho', 'name': 'Holmium'},
         'origin_of_name': "New Latin Holmia 'Stockholm'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '164.93', 'density': '8.79', 'melting_point': '1734', 'boiling_point': '2993',
         'specific_heat_capacity': '0.165', 'electronegativity': '1.23', 'abundance_in_earth_crust': '1.3',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '68', 'symbol': 'Er', 'name': 'Erbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium terbium ytterbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '167.26', 'density': '9.066',
         'melting_point': '1802', 'boiling_point': '3141', 'specific_heat_capacity': '0.168',
         'electronegativity': '1.24', 'abundance_in_earth_crust': '3.5', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '69', 'symbol': 'Tm', 'name': 'Thulium'},
         'origin_of_name': 'Thule the ancient name for an unclear northern location', 'group': 'n/a', 'period': '6',
         'block': 'f-block', 'standard_atomic_weight': '168.93', 'density': '9.32', 'melting_point': '1818',
         'boiling_point': '2223', 'specific_heat_capacity': '0.16', 'electronegativity': '1.25',
         'abundance_in_earth_crust': '0.52', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '70', 'symbol': 'Yb', 'name': 'Ytterbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium terbium erbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '173.05', 'density': '6.90',
         'melting_point': '1097', 'boiling_point': '1469', 'specific_heat_capacity': '0.155',
         'electronegativity': '1.1', 'abundance_in_earth_crust': '3.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '71', 'symbol': 'Lu', 'name': 'Lutetium'},
         'origin_of_name': "Latin Lutetia 'Paris'", 'group': '3', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '174.97', 'density': '9.841', 'melting_point': '1925', 'boiling_point': '3675',
         'specific_heat_capacity': '0.154', 'electronegativity': '1.27', 'abundance_in_earth_crust': '0.8',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '72', 'symbol': 'Hf', 'name': 'Hafnium'},
         'origin_of_name': "New Latin Hafnia 'Copenhagen' (from Danish havn harbour)", 'group': '4', 'period': '6',
         'block': 'd-block', 'standard_atomic_weight': '178.49', 'density': '13.31', 'melting_point': '2506',
         'boiling_point': '4876', 'specific_heat_capacity': '0.144', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '3', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '73', 'symbol': 'Ta', 'name': 'Tantalum'},
         'origin_of_name': 'King Tantalus father of Niobe from Greek mythology; see also niobium', 'group': '5',
         'period': '6', 'block': 'd-block', 'standard_atomic_weight': '180.95', 'density': '16.69',
         'melting_point': '3290', 'boiling_point': '5731', 'specific_heat_capacity': '0.14', 'electronegativity': '1.5',
         'abundance_in_earth_crust': '2', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '74', 'symbol': 'W', 'name': 'Tungsten'},
         'origin_of_name': "Swedish tung sten 'heavy stone'\xa0· \xa0Symbol W is from Wolfram originally from Middle High German wolf-rahm 'wolf's foam' describing the mineral wolframite[5]",
         'group': '6', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '183.84', 'density': '19.25',
         'melting_point': '3695', 'boiling_point': '5828', 'specific_heat_capacity': '0.132',
         'electronegativity': '2.36', 'abundance_in_earth_crust': '1.3', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '75', 'symbol': 'Re', 'name': 'Rhenium'},
         'origin_of_name': "Latin Rhenus 'the Rhine'", 'group': '7', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '186.21', 'density': '21.02', 'melting_point': '3459', 'boiling_point': '5869',
         'specific_heat_capacity': '0.137', 'electronegativity': '1.9', 'abundance_in_earth_crust': '7×10−4',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '76', 'symbol': 'Os', 'name': 'Osmium'}, 'origin_of_name': "Greek osmḗ 'smell'",
         'group': '8', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '190.23', 'density': '22.59',
         'melting_point': '3306', 'boiling_point': '5285', 'specific_heat_capacity': '0.13', 'electronegativity': '2.2',
         'abundance_in_earth_crust': '0.002', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '77', 'symbol': 'Ir', 'name': 'Iridium'},
         'origin_of_name': 'Iris the Greek goddess of the rainbow', 'group': '9', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '192.22', 'density': '22.56', 'melting_point': '2719', 'boiling_point': '4701',
         'specific_heat_capacity': '0.131', 'electronegativity': '2.20', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '78', 'symbol': 'Pt', 'name': 'Platinum'},
         'origin_of_name': "Spanish platina 'little silver' from plata 'silver'", 'group': '10', 'period': '6',
         'block': 'd-block', 'standard_atomic_weight': '195.08', 'density': '21.45', 'melting_point': '2041.4',
         'boiling_point': '4098', 'specific_heat_capacity': '0.133', 'electronegativity': '2.28',
         'abundance_in_earth_crust': '0.005', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '79', 'symbol': 'Au', 'name': 'Gold'},
         'origin_of_name': "English word from the same root as 'yellow'\xa0· \xa0Symbol Au is derived from Latin aurum",
         'group': '11', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '196.97', 'density': '19.3',
         'melting_point': '1337.33', 'boiling_point': '3129', 'specific_heat_capacity': '0.129',
         'electronegativity': '2.54', 'abundance_in_earth_crust': '0.004', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '80', 'symbol': 'Hg', 'name': 'Mercury'},
         'origin_of_name': "Mercury Roman god of commerce communication and luck known for his speed and mobility\xa0· \xa0Symbol Hg is derived from its Latin name hydrargyrum from Greek hydrárgyros 'water-silver'",
         'group': '12', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '200.59', 'density': '13.534',
         'melting_point': '234.43', 'boiling_point': '629.88', 'specific_heat_capacity': '0.14',
         'electronegativity': '2.00', 'abundance_in_earth_crust': '0.085', 'origin': 'primordial',
         'phase_at_r_t': 'liquid'},
        {'element': {'atomic_number': '81', 'symbol': 'Tl', 'name': 'Thallium'},
         'origin_of_name': "Greek thallós 'green shoot or twig'", 'group': '13', 'period': '6', 'block': 'p-block',
         'standard_atomic_weight': '204.38', 'density': '11.85', 'melting_point': '577', 'boiling_point': '1746',
         'specific_heat_capacity': '0.129', 'electronegativity': '1.62', 'abundance_in_earth_crust': '0.85',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '82', 'symbol': 'Pb', 'name': 'Lead'},
         'origin_of_name': "English word from Proto-Celtic *ɸloudom from a root meaning 'flow'\xa0· \xa0Symbol Pb is derived from Latin plumbum",
         'group': '14', 'period': '6', 'block': 'p-block', 'standard_atomic_weight': '207.2', 'density': '11.34',
         'melting_point': '600.61', 'boiling_point': '2022', 'specific_heat_capacity': '0.129',
         'electronegativity': '1.87 (2+)2.33 (4+)', 'abundance_in_earth_crust': '14', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '83', 'symbol': 'Bi', 'name': 'Bismuth'},
         'origin_of_name': "German Wismut from weiß Masse 'white mass' unless from Arabic", 'group': '15',
         'period': '6', 'block': 'p-block', 'standard_atomic_weight': '208.98', 'density': '9.78',
         'melting_point': '544.7', 'boiling_point': '1837', 'specific_heat_capacity': '0.122',
         'electronegativity': '2.02', 'abundance_in_earth_crust': '0.009', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '84', 'symbol': 'Po', 'name': 'Polonium'},
         'origin_of_name': "Latin Polonia 'Poland' home country of Marie Curie", 'group': '16', 'period': '6',
         'block': 'p-block', 'standard_atomic_weight': '[209][a]', 'density': '9.196', 'melting_point': '527',
         'boiling_point': '1235', 'specific_heat_capacity': '–', 'electronegativity': '2.0',
         'abundance_in_earth_crust': '2×10−10', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '85', 'symbol': 'At', 'name': 'Astatine'},
         'origin_of_name': "Greek ástatos 'unstable'", 'group': '17', 'period': '6', 'block': 'p-block',
         'standard_atomic_weight': '[210]', 'density': '(8.91–8.95)', 'melting_point': '575', 'boiling_point': '610',
         'specific_heat_capacity': '–', 'electronegativity': '2.2', 'abundance_in_earth_crust': '3×10−20',
         'origin': 'from decay', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '86', 'symbol': 'Rn', 'name': 'Radon'},
         'origin_of_name': 'Radium emanation originally the name of the isotope Radon-222', 'group': '18',
         'period': '6', 'block': 'p-block', 'standard_atomic_weight': '[222]', 'density': '0.00973',
         'melting_point': '202', 'boiling_point': '211.3', 'specific_heat_capacity': '0.094',
         'electronegativity': '2.2', 'abundance_in_earth_crust': '4×10−13', 'origin': 'from decay',
         'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '87', 'symbol': 'Fr', 'name': 'Francium'},
         'origin_of_name': 'France home country of discoverer Marguerite Perey', 'group': '1', 'period': '7',
         'block': 's-block', 'standard_atomic_weight': '[223]', 'density': '(2.48)', 'melting_point': '281',
         'boiling_point': '890', 'specific_heat_capacity': '–', 'electronegativity': '>0.79[6]',
         'abundance_in_earth_crust': '~\xa01×10−18', 'origin': 'from decay', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '88', 'symbol': 'Ra', 'name': 'Radium'},
         'origin_of_name': "French radium from Latin radius 'ray'", 'group': '2', 'period': '7', 'block': 's-block',
         'standard_atomic_weight': '[226]', 'density': '5.5', 'melting_point': '973', 'boiling_point': '2010',
         'specific_heat_capacity': '0.094', 'electronegativity': '0.9', 'abundance_in_earth_crust': '9×10−7',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '89', 'symbol': 'Ac', 'name': 'Actinium'}, 'origin_of_name': "Greek aktís 'ray'",
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[227]', 'density': '10',
         'melting_point': '1323', 'boiling_point': '3471', 'specific_heat_capacity': '0.12', 'electronegativity': '1.1',
         'abundance_in_earth_crust': '5.5×10−10', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '90', 'symbol': 'Th', 'name': 'Thorium'},
         'origin_of_name': 'Thor the Scandinavian god of thunder', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '232.04', 'density': '11.7', 'melting_point': '2115', 'boiling_point': '5061',
         'specific_heat_capacity': '0.113', 'electronegativity': '1.3', 'abundance_in_earth_crust': '9.6',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '91', 'symbol': 'Pa', 'name': 'Protactinium'},
         'origin_of_name': "Proto- (from Greek prôtos 'first before') + actinium since actinium is produced through the radioactive decay of protactinium",
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '231.04', 'density': '15.37',
         'melting_point': '1841', 'boiling_point': '4300', 'specific_heat_capacity': '–', 'electronegativity': '1.5',
         'abundance_in_earth_crust': '1.4×10−6', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '92', 'symbol': 'U', 'name': 'Uranium'},
         'origin_of_name': 'Uranus the seventh planet in the Solar System', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '238.03', 'density': '19.1', 'melting_point': '1405.3',
         'boiling_point': '4404', 'specific_heat_capacity': '0.116', 'electronegativity': '1.38',
         'abundance_in_earth_crust': '2.7', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '93', 'symbol': 'Np', 'name': 'Neptunium'},
         'origin_of_name': 'Neptune the eighth planet in the Solar System', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[237]', 'density': '20.45', 'melting_point': '917',
         'boiling_point': '4273', 'specific_heat_capacity': '–', 'electronegativity': '1.36',
         'abundance_in_earth_crust': '≤\xa03×10−12', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '94', 'symbol': 'Pu', 'name': 'Plutonium'},
         'origin_of_name': 'Pluto a dwarf planet considered a planet in the Solar System at the time', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[244]', 'density': '19.85',
         'melting_point': '912.5', 'boiling_point': '3501', 'specific_heat_capacity': '–', 'electronegativity': '1.28',
         'abundance_in_earth_crust': '≤\xa03×10−11', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '95', 'symbol': 'Am', 'name': 'Americium'},
         'origin_of_name': 'The Americas where the element was first synthesised by analogy with its homologue §\xa0europium',
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[243]', 'density': '12',
         'melting_point': '1449', 'boiling_point': '2880', 'specific_heat_capacity': '–', 'electronegativity': '1.13',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '96', 'symbol': 'Cm', 'name': 'Curium'},
         'origin_of_name': 'Pierre Curie and Marie Curie French physicists and chemists', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[247]', 'density': '13.51', 'melting_point': '1613',
         'boiling_point': '3383', 'specific_heat_capacity': '–', 'electronegativity': '1.28',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '97', 'symbol': 'Bk', 'name': 'Berkelium'},
         'origin_of_name': 'Berkeley California where the element was first synthesised', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[247]', 'density': '14.78', 'melting_point': '1259',
         'boiling_point': '2900', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '98', 'symbol': 'Cf', 'name': 'Californium'},
         'origin_of_name': 'California where the element was first synthesised in the LBNL laboratory', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[251]', 'density': '15.1',
         'melting_point': '1173', 'boiling_point': '(1743)[b]', 'specific_heat_capacity': '–',
         'electronegativity': '1.3', 'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '99', 'symbol': 'Es', 'name': 'Einsteinium'},
         'origin_of_name': 'Albert Einstein German physicist', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '[252]', 'density': '8.84', 'melting_point': '1133', 'boiling_point': '(1269)',
         'specific_heat_capacity': '–', 'electronegativity': '1.3', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '100', 'symbol': 'Fm', 'name': 'Fermium'},
         'origin_of_name': 'Enrico Fermi Italian physicist', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '[257]', 'density': '(9.7)[b]', 'melting_point': '(1125)[7](1800)[8]',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '101', 'symbol': 'Md', 'name': 'Mendelevium'},
         'origin_of_name': 'Dmitri Mendeleev Russian chemist who proposed the periodic table', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[258]', 'density': '(10.3)',
         'melting_point': '(1100)', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '102', 'symbol': 'No', 'name': 'Nobelium'},
         'origin_of_name': 'Alfred Nobel Swedish chemist and engineer', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[259]', 'density': '(9.9)', 'melting_point': '(1100)',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '103', 'symbol': 'Lr', 'name': 'Lawrencium'},
         'origin_of_name': 'Ernest Lawrence American physicist', 'group': '3', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[266]', 'density': '(14.4)', 'melting_point': '(1900)', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '1.3', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '104', 'symbol': 'Rf', 'name': 'Rutherfordium'},
         'origin_of_name': 'Ernest Rutherford chemist and physicist from New Zealand', 'group': '4', 'period': '7',
         'block': 'd-block', 'standard_atomic_weight': '[267]', 'density': '(17)', 'melting_point': '(2400)',
         'boiling_point': '(5800)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '105', 'symbol': 'Db', 'name': 'Dubnium'},
         'origin_of_name': 'Dubna Russia where the element was discovered in the JINR laboratory', 'group': '5',
         'period': '7', 'block': 'd-block', 'standard_atomic_weight': '[268]', 'density': '(21.6)',
         'melting_point': '–', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '106', 'symbol': 'Sg', 'name': 'Seaborgium'},
         'origin_of_name': 'Glenn T. Seaborg American chemist', 'group': '6', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[269]', 'density': '(23–24)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '107', 'symbol': 'Bh', 'name': 'Bohrium'},
         'origin_of_name': 'Niels Bohr Danish physicist', 'group': '7', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[270]', 'density': '(26–27)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '108', 'symbol': 'Hs', 'name': 'Hassium'},
         'origin_of_name': "New Latin Hassia 'Hesse' a state in Germany", 'group': '8', 'period': '7',
         'block': 'd-block', 'standard_atomic_weight': '[269]', 'density': '(27–29)', 'melting_point': '–',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '109', 'symbol': 'Mt', 'name': 'Meitnerium'},
         'origin_of_name': 'Lise Meitner Austrian physicist', 'group': '9', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[278]', 'density': '(27–28)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '110', 'symbol': 'Ds', 'name': 'Darmstadtium'},
         'origin_of_name': 'Darmstadt Germany where the element was first synthesised in the GSI laboratories',
         'group': '10', 'period': '7', 'block': 'd-block', 'standard_atomic_weight': '[281]', 'density': '(26–27)',
         'melting_point': '–', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '111', 'symbol': 'Rg', 'name': 'Roentgenium'},
         'origin_of_name': 'Wilhelm Conrad Röntgen German physicist', 'group': '11', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[282]', 'density': '(22–24)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '112', 'symbol': 'Cn', 'name': 'Copernicium'},
         'origin_of_name': 'Nicolaus Copernicus Polish astronomer', 'group': '12', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[285]', 'density': '(14.0)', 'melting_point': '(283)', 'boiling_point': '(340)[b]',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '113', 'symbol': 'Nh', 'name': 'Nihonium'},
         'origin_of_name': "Japanese Nihon 'Japan' where the element was first synthesised in the Riken laboratories",
         'group': '13', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[286]', 'density': '(16)',
         'melting_point': '(700)', 'boiling_point': '(1400)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '114', 'symbol': 'Fl', 'name': 'Flerovium'},
         'origin_of_name': 'Flerov Laboratory of Nuclear Reactions part of JINR where the element was synthesised; itself named after Georgy Flyorov Russian physicist',
         'group': '14', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[289]', 'density': '(9.928)',
         'melting_point': '(200)[b]', 'boiling_point': '(380)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '115', 'symbol': 'Mc', 'name': 'Moscovium'},
         'origin_of_name': 'Moscow Russia where the element was first synthesised in the JINR laboratories',
         'group': '15', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[290]', 'density': '(13.5)',
         'melting_point': '(700)', 'boiling_point': '(1400)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '116', 'symbol': 'Lv', 'name': 'Livermorium'},
         'origin_of_name': 'Lawrence Livermore National Laboratory in Livermore California', 'group': '16',
         'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[293]', 'density': '(12.9)',
         'melting_point': '(700)', 'boiling_point': '(1100)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '117', 'symbol': 'Ts', 'name': 'Tennessine'},
         'origin_of_name': 'Tennessee United States where Oak Ridge National Laboratory is located', 'group': '17',
         'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[294]', 'density': '(7.1–7.3)',
         'melting_point': '(700)', 'boiling_point': '(883)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '118', 'symbol': 'Og', 'name': 'Oganesson'},
         'origin_of_name': 'Yuri Oganessian Russian physicist', 'group': '18', 'period': '7', 'block': 'p-block',
         'standard_atomic_weight': '[294]', 'density': '(6.6–7.4)', 'melting_point': '(325)', 'boiling_point': '(450)',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
    ]

    return data


# Get the abundance of elements in Earth's crust
def get_the_abundance_of_elements_in_earth_crust():
    data = [
     {'element': {'z': '8', 'name': 'oxygen', 'symbol': 'O'},
      'abundance_by_source_in_ppm': {'darling': '466000', 'barbalace': '474000', 'webelements': '460000',
                                     'israel_science_and_technology': '467100', 'crc': '461000 (46.1%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '14', 'name': 'silicon', 'symbol': 'Si'},
      'abundance_by_source_in_ppm': {'darling': '277200', 'barbalace': '277100', 'webelements': '270000',
                                     'israel_science_and_technology': '276900', 'crc': '282000 (28.2%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '7200000'},
     {'element': {'z': '13', 'name': 'aluminium', 'symbol': 'Al'},
      'abundance_by_source_in_ppm': {'darling': '81300', 'barbalace': '82000', 'webelements': '82000',
                                     'israel_science_and_technology': '80700', 'crc': '82300 (8.23%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '57600000'},
     {'element': {'z': '26', 'name': 'iron', 'symbol': 'Fe'},
      'abundance_by_source_in_ppm': {'darling': '50000', 'barbalace': '41000', 'webelements': '63000',
                                     'israel_science_and_technology': '50500', 'crc': '56300 (5.63%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '1150000000'},
     {'element': {'z': '20', 'name': 'calcium', 'symbol': 'Ca'},
      'abundance_by_source_in_ppm': {'darling': '36300', 'barbalace': '41000', 'webelements': '50000',
                                     'israel_science_and_technology': '36500', 'crc': '41500 (4.15%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '11', 'name': 'sodium', 'symbol': 'Na'},
      'abundance_by_source_in_ppm': {'darling': '28300', 'barbalace': '23000', 'webelements': '23000',
                                     'israel_science_and_technology': '27500', 'crc': '23600 (2.36%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '255000000'},
     {'element': {'z': '12', 'name': 'magnesium', 'symbol': 'Mg'},
      'abundance_by_source_in_ppm': {'darling': '20900', 'barbalace': '23000', 'webelements': '29000',
                                     'israel_science_and_technology': '20800', 'crc': '23300 (2.33%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '27700000'},
     {'element': {'z': '19', 'name': 'potassium', 'symbol': 'K'},
      'abundance_by_source_in_ppm': {'darling': '25900', 'barbalace': '21000', 'webelements': '15000',
                                     'israel_science_and_technology': '25800', 'crc': '20900 (2.09%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '22', 'name': 'titanium', 'symbol': 'Ti'},
      'abundance_by_source_in_ppm': {'darling': '4400', 'barbalace': '5600', 'webelements': '6600',
                                     'israel_science_and_technology': '6200', 'crc': '5650 (0.565%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '6600000'},
     {'element': {'z': '1', 'name': 'hydrogen', 'symbol': 'H'},
      'abundance_by_source_in_ppm': {'darling': '1400', 'barbalace': '', 'webelements': '1500',
                                     'israel_science_and_technology': '1400', 'crc': '1400 (0.14%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '15', 'name': 'phosphorus', 'symbol': 'P'},
      'abundance_by_source_in_ppm': {'darling': '1200', 'barbalace': '1000', 'webelements': '1000',
                                     'israel_science_and_technology': '1300', 'crc': '1050 (0.105%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '25', 'name': 'manganese', 'symbol': 'Mn'},
      'abundance_by_source_in_ppm': {'darling': '1000', 'barbalace': '950', 'webelements': '1100',
                                     'israel_science_and_technology': '900', 'crc': '950 (0.095%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '16000000'},
     {'element': {'z': '9', 'name': 'fluorine', 'symbol': 'F'},
      'abundance_by_source_in_ppm': {'darling': '800', 'barbalace': '950', 'webelements': '540',
                                     'israel_science_and_technology': '290', 'crc': '585 (0.0585%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '56', 'name': 'barium', 'symbol': 'Ba'},
      'abundance_by_source_in_ppm': {'darling': '500', 'barbalace': '340', 'webelements': '340',
                                     'israel_science_and_technology': '500', 'crc': '425 (0.0425%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '38', 'name': 'strontium', 'symbol': 'Sr'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '370', 'webelements': '360',
                                     'israel_science_and_technology': '', 'crc': '370 (0.037%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '350000'},
     {'element': {'z': '16', 'name': 'sulphur', 'symbol': 'S'},
      'abundance_by_source_in_ppm': {'darling': '500', 'barbalace': '260', 'webelements': '420',
                                     'israel_science_and_technology': '520', 'crc': '350 (0.035%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '69300000'},
     {'element': {'z': '6', 'name': 'carbon', 'symbol': 'C'},
      'abundance_by_source_in_ppm': {'darling': '300', 'barbalace': '480', 'webelements': '1800',
                                     'israel_science_and_technology': '940', 'crc': '200 (0.02%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '40', 'name': 'zirconium', 'symbol': 'Zr'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '190', 'webelements': '130',
                                     'israel_science_and_technology': '250', 'crc': '165 (0.0165%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '1460000'},
     {'element': {'z': '17', 'name': 'chlorine', 'symbol': 'Cl'},
      'abundance_by_source_in_ppm': {'darling': '500', 'barbalace': '130', 'webelements': '170',
                                     'israel_science_and_technology': '450', 'crc': '145 (0.0145%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '23', 'name': 'vanadium', 'symbol': 'V'},
      'abundance_by_source_in_ppm': {'darling': '100', 'barbalace': '160', 'webelements': '190',
                                     'israel_science_and_technology': '', 'crc': '120 (0.012%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '76000'},
     {'element': {'z': '24', 'name': 'chromium', 'symbol': 'Cr'},
      'abundance_by_source_in_ppm': {'darling': '100', 'barbalace': '100', 'webelements': '140',
                                     'israel_science_and_technology': '350', 'crc': '102 (0.0102%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '26000000'},
     {'element': {'z': '37', 'name': 'rubidium', 'symbol': 'Rb'},
      'abundance_by_source_in_ppm': {'darling': '300', 'barbalace': '90', 'webelements': '60',
                                     'israel_science_and_technology': '', 'crc': '90 (0.009%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '28', 'name': 'nickel', 'symbol': 'Ni'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '80', 'webelements': '90',
                                     'israel_science_and_technology': '190', 'crc': '84 (0.0084%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '2250000'},
     {'element': {'z': '30', 'name': 'zinc', 'symbol': 'Zn'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '75', 'webelements': '79',
                                     'israel_science_and_technology': '', 'crc': '70 (0.007%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '11900000'},
     {'element': {'z': '58', 'name': 'cerium', 'symbol': 'Ce'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '68', 'webelements': '60',
                                     'israel_science_and_technology': '', 'crc': '66.5 (0.00665%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '29', 'name': 'copper', 'symbol': 'Cu'},
      'abundance_by_source_in_ppm': {'darling': '100', 'barbalace': '50', 'webelements': '68',
                                     'israel_science_and_technology': '', 'crc': '60 (0.006%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '19400000'},
     {'element': {'z': '60', 'name': 'neodymium', 'symbol': 'Nd'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '38', 'webelements': '33',
                                     'israel_science_and_technology': '', 'crc': '41.5 (0.00415%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '57', 'name': 'lanthanum', 'symbol': 'La'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '32', 'webelements': '34',
                                     'israel_science_and_technology': '', 'crc': '39 (0.0039%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '39', 'name': 'yttrium', 'symbol': 'Y'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '30', 'webelements': '29',
                                     'israel_science_and_technology': '', 'crc': '33 (0.0033%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '6000'},
     {'element': {'z': '7', 'name': 'nitrogen', 'symbol': 'N'},
      'abundance_by_source_in_ppm': {'darling': '50', 'barbalace': '25', 'webelements': '20',
                                     'israel_science_and_technology': '', 'crc': '19 (0.0019%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '140000000'},
     {'element': {'z': '27', 'name': 'cobalt', 'symbol': 'Co'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '20', 'webelements': '30',
                                     'israel_science_and_technology': '', 'crc': '25 (0.0025%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '123000'},
     {'element': {'z': '21', 'name': 'scandium', 'symbol': 'Sc'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '16', 'webelements': '26',
                                     'israel_science_and_technology': '', 'crc': '22 (0.0022%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '3', 'name': 'lithium', 'symbol': 'Li'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '20', 'webelements': '17',
                                     'israel_science_and_technology': '', 'crc': '20 (0.002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '35000'},
     {'element': {'z': '41', 'name': 'niobium', 'symbol': 'Nb'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '20', 'webelements': '17',
                                     'israel_science_and_technology': '', 'crc': '20 (0.002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '64000'},
     {'element': {'z': '31', 'name': 'gallium', 'symbol': 'Ga'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '18', 'webelements': '19',
                                     'israel_science_and_technology': '', 'crc': '19 (0.0019%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '315'},
     {'element': {'z': '82', 'name': 'lead', 'symbol': 'Pb'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '14', 'webelements': '10',
                                     'israel_science_and_technology': '', 'crc': '14 (0.0014%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '4820000'},
     {'element': {'z': '5', 'name': 'boron', 'symbol': 'B'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '950[dubious  – discuss]', 'webelements': '8.7',
                                     'israel_science_and_technology': '', 'crc': '10 (0.001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '9400000'},
     {'element': {'z': '90', 'name': 'thorium', 'symbol': 'Th'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '12', 'webelements': '6',
                                     'israel_science_and_technology': '', 'crc': '9.6 (0.00096%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '59', 'name': 'praseodymium', 'symbol': 'Pr'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '9.5', 'webelements': '8.7',
                                     'israel_science_and_technology': '', 'crc': '9.2 (0.00092%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '62', 'name': 'samarium', 'symbol': 'Sm'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '7.9', 'webelements': '6',
                                     'israel_science_and_technology': '', 'crc': '7.05 (0.000705%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '64', 'name': 'gadolinium', 'symbol': 'Gd'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '7.7', 'webelements': '5.2',
                                     'israel_science_and_technology': '', 'crc': '6.2 (0.00062%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '66', 'name': 'dysprosium', 'symbol': 'Dy'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '6', 'webelements': '6.2',
                                     'israel_science_and_technology': '', 'crc': '5.2 (0.00052%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '68', 'name': 'erbium', 'symbol': 'Er'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '3.8', 'webelements': '3.0',
                                     'israel_science_and_technology': '', 'crc': '3.5 (0.00035%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '18', 'name': 'argon', 'symbol': 'Ar'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '3.5 (0.00035%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '70', 'name': 'ytterbium', 'symbol': 'Yb'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '3.3', 'webelements': '2.8',
                                     'israel_science_and_technology': '', 'crc': '3.2 (0.00032%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '72', 'name': 'hafnium', 'symbol': 'Hf'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '5.3', 'webelements': '3.3',
                                     'israel_science_and_technology': '', 'crc': '3.0 (0.0003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '55', 'name': 'caesium', 'symbol': 'Cs'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '3', 'webelements': '1.9',
                                     'israel_science_and_technology': '', 'crc': '3.0 (0.0003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '4', 'name': 'beryllium', 'symbol': 'Be'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '2.6', 'webelements': '1.9',
                                     'israel_science_and_technology': '', 'crc': '2.8 (0.00028%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '220'},
     {'element': {'z': '92', 'name': 'uranium', 'symbol': 'U'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0', 'webelements': '1.8',
                                     'israel_science_and_technology': '', 'crc': '2.7 (0.00027%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '74119'},
     {'element': {'z': '35', 'name': 'bromine', 'symbol': 'Br'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.3700', 'webelements': '3',
                                     'israel_science_and_technology': '', 'crc': '2.4 (0.00024%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '391000'},
     {'element': {'z': '50', 'name': 'tin', 'symbol': 'Sn'},
      'abundance_by_source_in_ppm': {'darling': '0', 'barbalace': '2.2', 'webelements': '2.2',
                                     'israel_science_and_technology': '', 'crc': '2.3 (0.00023%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '280000'},
     {'element': {'z': '73', 'name': 'tantalum', 'symbol': 'Ta'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '2', 'webelements': '1.7',
                                     'israel_science_and_technology': '', 'crc': '2.0 (0.0002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '1100'},
     {'element': {'z': '63', 'name': 'europium', 'symbol': 'Eu'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '2.1', 'webelements': '1.8',
                                     'israel_science_and_technology': '', 'crc': '2.0 (0.0002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '33', 'name': 'arsenic', 'symbol': 'As'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '1.5', 'webelements': '2.1',
                                     'israel_science_and_technology': '', 'crc': '1.8 (0.00018%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '36500'},
     {'element': {'z': '32', 'name': 'germanium', 'symbol': 'Ge'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '1.8', 'webelements': '1.4',
                                     'israel_science_and_technology': '', 'crc': '1.5 (0.00015%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '155'},
     {'element': {'z': '74', 'name': 'tungsten', 'symbol': 'W'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '160.6[dubious  – discuss]', 'webelements': '1.1',
                                     'israel_science_and_technology': '', 'crc': '1.25 (0.000125%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '86400'},
     {'element': {'z': '67', 'name': 'holmium', 'symbol': 'Ho'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '1.4', 'webelements': '1.2',
                                     'israel_science_and_technology': '', 'crc': '1.3 (0.00013%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '42', 'name': 'molybdenum', 'symbol': 'Mo'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '1.5', 'webelements': '1.1',
                                     'israel_science_and_technology': '', 'crc': '1.2 (0.00012%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '227000'},
     {'element': {'z': '65', 'name': 'terbium', 'symbol': 'Tb'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '1.1', 'webelements': '0.9400',
                                     'israel_science_and_technology': '', 'crc': '1.2 (0.00012%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '81', 'name': 'thallium', 'symbol': 'Tl'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.6000', 'webelements': '0.5300',
                                     'israel_science_and_technology': '', 'crc': '0.85 (0.000085%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '10'},
     {'element': {'z': '71', 'name': 'lutetium', 'symbol': 'Lu'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.8 (0.00008%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '69', 'name': 'thulium', 'symbol': 'Tm'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.4800', 'webelements': '0.4500',
                                     'israel_science_and_technology': '', 'crc': '0.52 (0.000052%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '53', 'name': 'iodine', 'symbol': 'I'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.1400', 'webelements': '0.4900',
                                     'israel_science_and_technology': '', 'crc': '0.45 (0.000045%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '31600'},
     {'element': {'z': '49', 'name': 'indium', 'symbol': 'In'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0490', 'webelements': '0.1600',
                                     'israel_science_and_technology': '', 'crc': '0.25 (0.000025%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '655'},
     {'element': {'z': '51', 'name': 'antimony', 'symbol': 'Sb'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.2000', 'webelements': '0.2000',
                                     'israel_science_and_technology': '', 'crc': '0.2 (0.00002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '130000'},
     {'element': {'z': '48', 'name': 'cadmium', 'symbol': 'Cd'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.1100', 'webelements': '0.1500',
                                     'israel_science_and_technology': '', 'crc': '0.15 (0.000015%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '23000'},
     {'element': {'z': '80', 'name': 'mercury', 'symbol': 'Hg'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0500', 'webelements': '0.0670',
                                     'israel_science_and_technology': '', 'crc': '0.085 (0.0000085%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '4500'},
     {'element': {'z': '47', 'name': 'silver', 'symbol': 'Ag'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0700', 'webelements': '0.0800',
                                     'israel_science_and_technology': '', 'crc': '0.075 (0.0000075%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '27000'},
     {'element': {'z': '34', 'name': 'selenium', 'symbol': 'Se'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0500', 'webelements': '0.0500',
                                     'israel_science_and_technology': '', 'crc': '0.05 (0.000005%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '2200'},
     {'element': {'z': '46', 'name': 'palladium', 'symbol': 'Pd'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0006', 'webelements': '0.0063',
                                     'israel_science_and_technology': '', 'crc': '0.015 (0.0000015%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '208'},
     {'element': {'z': '83', 'name': 'bismuth', 'symbol': 'Bi'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0480', 'webelements': '0.0250',
                                     'israel_science_and_technology': '', 'crc': '0.0085 (0.00000085%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '10200'},
     {'element': {'z': '2', 'name': 'helium', 'symbol': 'He'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.008 (0.0000008%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '10', 'name': 'neon', 'symbol': 'Ne'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.0051 (0.00000051%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '78', 'name': 'platinum', 'symbol': 'Pt'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0030', 'webelements': '0.0037',
                                     'israel_science_and_technology': '', 'crc': '0.005 (0.0000005%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '172'},
     {'element': {'z': '79', 'name': 'gold', 'symbol': 'Au'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0011', 'webelements': '0.0031',
                                     'israel_science_and_technology': '', 'crc': '0.004 (0.0000004%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '3100'},
     {'element': {'z': '76', 'name': 'osmium', 'symbol': 'Os'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0001', 'webelements': '0.0018',
                                     'israel_science_and_technology': '', 'crc': '0.0015 (0.00000015%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '52', 'name': 'tellurium', 'symbol': 'Te'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0050', 'webelements': '0.0010',
                                     'israel_science_and_technology': '', 'crc': '0.001 (0.0000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '2200'},
     {'element': {'z': '44', 'name': 'ruthenium', 'symbol': 'Ru'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0010', 'webelements': '0.0010',
                                     'israel_science_and_technology': '', 'crc': '0.001(0.0000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '77', 'name': 'iridium', 'symbol': 'Ir'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0003', 'webelements': '0.0004',
                                     'israel_science_and_technology': '', 'crc': '0.001(0.0000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '45', 'name': 'rhodium', 'symbol': 'Rh'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0002', 'webelements': '0.0007',
                                     'israel_science_and_technology': '', 'crc': '0.001(0.0000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '75', 'name': 'rhenium', 'symbol': 'Re'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '0.0004', 'webelements': '0.0026',
                                     'israel_science_and_technology': '', 'crc': '0.0007 (0.00000007%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': '47.2'},
     {'element': {'z': '36', 'name': 'krypton', 'symbol': 'Kr'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.0001 (0.00000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '54', 'name': 'xenon', 'symbol': 'Xe'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.00003 (0.000000003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '91', 'name': 'protactinium', 'symbol': 'Pa'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.0000014 (0.00000000014%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '88', 'name': 'radium', 'symbol': 'Ra'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.0000009 (0.00000000009%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '84', 'name': 'polonium', 'symbol': 'Po'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.0000000002 (0.00000000000002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '94', 'name': 'plutonium', 'symbol': 'Pu'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '', 'crc': '0.00000000003 (0.000000000000003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '93', 'name': 'neptunium', 'symbol': 'Np'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.000000000003 (0.0000000000000003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '43', 'name': 'technetium', 'symbol': 'Tc'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.00000000000135 (0.000000000000000135%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '89', 'name': 'actinium', 'symbol': 'Ac'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.0000000000006 (0.00000000000000006%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '86', 'name': 'radon', 'symbol': 'Rn'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.0000000000004 (0.00000000000000004%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '61', 'name': 'promethium', 'symbol': 'Pm'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.00000000000000002 (0.000000000000000000002%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '87', 'name': 'francium', 'symbol': 'Fr'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.000000000000000001 (0.0000000000000000000001%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
     {'element': {'z': '85', 'name': 'astatine', 'symbol': 'At'},
      'abundance_by_source_in_ppm': {'darling': '', 'barbalace': '', 'webelements': '',
                                     'israel_science_and_technology': '',
                                     'crc': '0.00000000000000000003 (0.000000000000000000000003%)'},
      'annual_production_by_extraction_in_2016_in_tonnes': ''},
    ]

    return data
