# Get the list of chemical elements
def get_the_list_of_chemical_elements():
    data = [
        {'element': {'atomic_number': '1', 'symbol': 'H', 'name': 'Hydrogen'},
         'origin_of_name': "Greek elements hydro- and -gen 'water-forming'", 'group': '1', 'period': '1',
         'block': 's-block', 'standard_atomic_weight': '1.0080', 'density': '0.00008988', 'melting_point': '14.01',
         'boiling_point': '20.28', 'specific_heat_capacity': '14.304', 'electronegativity': '2.20',
         'abundance_in_earth_crust': '1400', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '2', 'symbol': 'He', 'name': 'Helium'}, 'origin_of_name': "Greek hḗlios 'sun'",
         'group': '18', 'period': '1', 'block': 's-block', 'standard_atomic_weight': '4.0026', 'density': '0.0001785',
         'melting_point': '–[k]', 'boiling_point': '4.22', 'specific_heat_capacity': '5.193', 'electronegativity': '–',
         'abundance_in_earth_crust': '0.008', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '3', 'symbol': 'Li', 'name': 'Lithium'}, 'origin_of_name': "Greek líthos 'stone'",
         'group': '1', 'period': '2', 'block': 's-block', 'standard_atomic_weight': '6.94', 'density': '0.534',
         'melting_point': '453.69', 'boiling_point': '1560', 'specific_heat_capacity': '3.582',
         'electronegativity': '0.98', 'abundance_in_earth_crust': '20', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '4', 'symbol': 'Be', 'name': 'Beryllium'},
         'origin_of_name': 'Beryl a mineral (ultimately from the name of Belur in southern India)[4]', 'group': '2',
         'period': '2', 'block': 's-block', 'standard_atomic_weight': '9.0122', 'density': '1.85',
         'melting_point': '1560', 'boiling_point': '2742', 'specific_heat_capacity': '1.825',
         'electronegativity': '1.57', 'abundance_in_earth_crust': '2.8', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '5', 'symbol': 'B', 'name': 'Boron'},
         'origin_of_name': 'Borax a mineral (from Arabic bawraq Middle Persian *bōrag)', 'group': '13', 'period': '2',
         'block': 'p-block', 'standard_atomic_weight': '10.81', 'density': '2.34', 'melting_point': '2349',
         'boiling_point': '4200', 'specific_heat_capacity': '1.026', 'electronegativity': '2.04',
         'abundance_in_earth_crust': '10', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '6', 'symbol': 'C', 'name': 'Carbon'}, 'origin_of_name': "Latin carbo 'coal'",
         'group': '14', 'period': '2', 'block': 'p-block', 'standard_atomic_weight': '12.011', 'density': '2.267',
         'melting_point': '>4000', 'boiling_point': '4300', 'specific_heat_capacity': '0.709',
         'electronegativity': '2.55', 'abundance_in_earth_crust': '200', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '7', 'symbol': 'N', 'name': 'Nitrogen'},
         'origin_of_name': "Greek nítron and -gen 'niter-forming'", 'group': '15', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '14.007', 'density': '0.0012506', 'melting_point': '63.15', 'boiling_point': '77.36',
         'specific_heat_capacity': '1.04', 'electronegativity': '3.04', 'abundance_in_earth_crust': '19',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '8', 'symbol': 'O', 'name': 'Oxygen'},
         'origin_of_name': "Greek oxy- and -gen 'acid-forming'", 'group': '16', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '15.999', 'density': '0.001429', 'melting_point': '54.36', 'boiling_point': '90.20',
         'specific_heat_capacity': '0.918', 'electronegativity': '3.44', 'abundance_in_earth_crust': '461000',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '9', 'symbol': 'F', 'name': 'Fluorine'},
         'origin_of_name': "Latin fluere 'to flow'", 'group': '17', 'period': '2', 'block': 'p-block',
         'standard_atomic_weight': '18.998', 'density': '0.001696', 'melting_point': '53.53', 'boiling_point': '85.03',
         'specific_heat_capacity': '0.824', 'electronegativity': '3.98', 'abundance_in_earth_crust': '585',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '10', 'symbol': 'Ne', 'name': 'Neon'}, 'origin_of_name': "Greek néon 'new'",
         'group': '18', 'period': '2', 'block': 'p-block', 'standard_atomic_weight': '20.180', 'density': '0.0009002',
         'melting_point': '24.56', 'boiling_point': '27.07', 'specific_heat_capacity': '1.03', 'electronegativity': '–',
         'abundance_in_earth_crust': '0.005', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '11', 'symbol': 'Na', 'name': 'Sodium'},
         'origin_of_name': "English (from medieval Latin) soda\xa0· \xa0Symbol Na is derived from New Latin natrium coined from German Natron 'natron'",
         'group': '1', 'period': '3', 'block': 's-block', 'standard_atomic_weight': '22.990', 'density': '0.968',
         'melting_point': '370.87', 'boiling_point': '1156', 'specific_heat_capacity': '1.228',
         'electronegativity': '0.93', 'abundance_in_earth_crust': '23600', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '12', 'symbol': 'Mg', 'name': 'Magnesium'},
         'origin_of_name': 'Magnesia a district of Eastern Thessaly in Greece', 'group': '2', 'period': '3',
         'block': 's-block', 'standard_atomic_weight': '24.305', 'density': '1.738', 'melting_point': '923',
         'boiling_point': '1363', 'specific_heat_capacity': '1.023', 'electronegativity': '1.31',
         'abundance_in_earth_crust': '23300', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '13', 'symbol': 'Al', 'name': 'Aluminium'},
         'origin_of_name': "Alumina from Latin alumen (gen. aluminis) 'bitter salt alum'", 'group': '13', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '26.982', 'density': '2.70', 'melting_point': '933.47',
         'boiling_point': '2792', 'specific_heat_capacity': '0.897', 'electronegativity': '1.61',
         'abundance_in_earth_crust': '82300', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '14', 'symbol': 'Si', 'name': 'Silicon'},
         'origin_of_name': "Latin silex 'flint' (originally silicium)", 'group': '14', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '28.085', 'density': '2.3290', 'melting_point': '1687',
         'boiling_point': '3538', 'specific_heat_capacity': '0.705', 'electronegativity': '1.9',
         'abundance_in_earth_crust': '282000', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '15', 'symbol': 'P', 'name': 'Phosphorus'},
         'origin_of_name': "Greek phōsphóros 'light-bearing'", 'group': '15', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '30.974', 'density': '1.823', 'melting_point': '317.30', 'boiling_point': '550',
         'specific_heat_capacity': '0.769', 'electronegativity': '2.19', 'abundance_in_earth_crust': '1050',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '16', 'symbol': 'S', 'name': 'Sulfur'},
         'origin_of_name': "Latin sulphur 'brimstone'", 'group': '16', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '32.06', 'density': '2.07', 'melting_point': '388.36', 'boiling_point': '717.87',
         'specific_heat_capacity': '0.71', 'electronegativity': '2.58', 'abundance_in_earth_crust': '350',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '17', 'symbol': 'Cl', 'name': 'Chlorine'},
         'origin_of_name': "Greek chlōrós 'greenish yellow'", 'group': '17', 'period': '3', 'block': 'p-block',
         'standard_atomic_weight': '35.45', 'density': '0.0032', 'melting_point': '171.6', 'boiling_point': '239.11',
         'specific_heat_capacity': '0.479', 'electronegativity': '3.16', 'abundance_in_earth_crust': '145',
         'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '18', 'symbol': 'Ar', 'name': 'Argon'},
         'origin_of_name': "Greek argós 'idle' (because of its inertness)", 'group': '18', 'period': '3',
         'block': 'p-block', 'standard_atomic_weight': '39.95', 'density': '0.001784', 'melting_point': '83.80',
         'boiling_point': '87.30', 'specific_heat_capacity': '0.52', 'electronegativity': '–',
         'abundance_in_earth_crust': '3.5', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '19', 'symbol': 'K', 'name': 'Potassium'},
         'origin_of_name': "New Latin potassa 'potash' itself from pot and ash\xa0· \xa0Symbol K is derived from Latin kalium",
         'group': '1', 'period': '4', 'block': 's-block', 'standard_atomic_weight': '39.098', 'density': '0.89',
         'melting_point': '336.53', 'boiling_point': '1032', 'specific_heat_capacity': '0.757',
         'electronegativity': '0.82', 'abundance_in_earth_crust': '20900', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '20', 'symbol': 'Ca', 'name': 'Calcium'}, 'origin_of_name': "Latin calx 'lime'",
         'group': '2', 'period': '4', 'block': 's-block', 'standard_atomic_weight': '40.078', 'density': '1.55',
         'melting_point': '1115', 'boiling_point': '1757', 'specific_heat_capacity': '0.647',
         'electronegativity': '1.00', 'abundance_in_earth_crust': '41500', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '21', 'symbol': 'Sc', 'name': 'Scandium'},
         'origin_of_name': "Latin Scandia 'Scandinavia'", 'group': '3', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '44.956', 'density': '2.985', 'melting_point': '1814', 'boiling_point': '3109',
         'specific_heat_capacity': '0.568', 'electronegativity': '1.36', 'abundance_in_earth_crust': '22',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '22', 'symbol': 'Ti', 'name': 'Titanium'},
         'origin_of_name': 'Titans the sons of the Earth goddess of Greek mythology', 'group': '4', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '47.867', 'density': '4.506', 'melting_point': '1941',
         'boiling_point': '3560', 'specific_heat_capacity': '0.523', 'electronegativity': '1.54',
         'abundance_in_earth_crust': '5650', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '23', 'symbol': 'V', 'name': 'Vanadium'},
         'origin_of_name': 'Vanadis an Old Norse name for the Scandinavian goddess Freyja', 'group': '5', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '50.942', 'density': '6.11', 'melting_point': '2183',
         'boiling_point': '3680', 'specific_heat_capacity': '0.489', 'electronegativity': '1.63',
         'abundance_in_earth_crust': '120', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '24', 'symbol': 'Cr', 'name': 'Chromium'},
         'origin_of_name': "Greek chróma 'colour'", 'group': '6', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '51.996', 'density': '7.15', 'melting_point': '2180', 'boiling_point': '2944',
         'specific_heat_capacity': '0.449', 'electronegativity': '1.66', 'abundance_in_earth_crust': '102',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '25', 'symbol': 'Mn', 'name': 'Manganese'},
         'origin_of_name': 'Corrupted from magnesia negra; see §\xa0magnesium', 'group': '7', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '54.938', 'density': '7.21', 'melting_point': '1519',
         'boiling_point': '2334', 'specific_heat_capacity': '0.479', 'electronegativity': '1.55',
         'abundance_in_earth_crust': '950', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '26', 'symbol': 'Fe', 'name': 'Iron'},
         'origin_of_name': "English word from Proto-Celtic *īsarnom ('iron') from a root meaning 'blood'\xa0· \xa0Symbol Fe is derived from Latin ferrum",
         'group': '8', 'period': '4', 'block': 'd-block', 'standard_atomic_weight': '55.845', 'density': '7.874',
         'melting_point': '1811', 'boiling_point': '3134', 'specific_heat_capacity': '0.449',
         'electronegativity': '1.83', 'abundance_in_earth_crust': '56300', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '27', 'symbol': 'Co', 'name': 'Cobalt'},
         'origin_of_name': "German Kobold 'goblin'", 'group': '9', 'period': '4', 'block': 'd-block',
         'standard_atomic_weight': '58.933', 'density': '8.90', 'melting_point': '1768', 'boiling_point': '3200',
         'specific_heat_capacity': '0.421', 'electronegativity': '1.88', 'abundance_in_earth_crust': '25',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '28', 'symbol': 'Ni', 'name': 'Nickel'},
         'origin_of_name': 'Nickel a mischievous sprite of German miner mythology', 'group': '10', 'period': '4',
         'block': 'd-block', 'standard_atomic_weight': '58.693', 'density': '8.908', 'melting_point': '1728',
         'boiling_point': '3186', 'specific_heat_capacity': '0.444', 'electronegativity': '1.91',
         'abundance_in_earth_crust': '84', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '29', 'symbol': 'Cu', 'name': 'Copper'},
         'origin_of_name': "English word from Latin cuprum from Ancient Greek Kýpros 'Cyprus'", 'group': '11',
         'period': '4', 'block': 'd-block', 'standard_atomic_weight': '63.546', 'density': '8.96',
         'melting_point': '1357.77', 'boiling_point': '2835', 'specific_heat_capacity': '0.385',
         'electronegativity': '1.90', 'abundance_in_earth_crust': '60', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '30', 'symbol': 'Zn', 'name': 'Zinc'},
         'origin_of_name': "Most likely from German Zinke 'prong' or 'tooth' though some suggest Persian sang 'stone'",
         'group': '12', 'period': '4', 'block': 'd-block', 'standard_atomic_weight': '65.38', 'density': '7.14',
         'melting_point': '692.88', 'boiling_point': '1180', 'specific_heat_capacity': '0.388',
         'electronegativity': '1.65', 'abundance_in_earth_crust': '70', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '31', 'symbol': 'Ga', 'name': 'Gallium'},
         'origin_of_name': "Latin Gallia 'France'", 'group': '13', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '69.723', 'density': '5.91', 'melting_point': '302.9146', 'boiling_point': '2673',
         'specific_heat_capacity': '0.371', 'electronegativity': '1.81', 'abundance_in_earth_crust': '19',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '32', 'symbol': 'Ge', 'name': 'Germanium'},
         'origin_of_name': "Latin Germania 'Germany'", 'group': '14', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '72.630', 'density': '5.323', 'melting_point': '1211.40', 'boiling_point': '3106',
         'specific_heat_capacity': '0.32', 'electronegativity': '2.01', 'abundance_in_earth_crust': '1.5',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '33', 'symbol': 'As', 'name': 'Arsenic'},
         'origin_of_name': "French arsenic from Greek arsenikón 'yellow arsenic' (influenced by arsenikós 'masculine' or 'virile') from a West Asian wanderword ultimately from Old Iranian *zarniya-ka 'golden'",
         'group': '15', 'period': '4', 'block': 'p-block', 'standard_atomic_weight': '74.922', 'density': '5.727',
         'melting_point': '1090[l]', 'boiling_point': '887', 'specific_heat_capacity': '0.329',
         'electronegativity': '2.18', 'abundance_in_earth_crust': '1.8', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '34', 'symbol': 'Se', 'name': 'Selenium'},
         'origin_of_name': "Greek selḗnē 'moon'", 'group': '16', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '78.971', 'density': '4.81', 'melting_point': '453', 'boiling_point': '958',
         'specific_heat_capacity': '0.321', 'electronegativity': '2.55', 'abundance_in_earth_crust': '0.05',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '35', 'symbol': 'Br', 'name': 'Bromine'},
         'origin_of_name': "Greek brômos 'stench'", 'group': '17', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '79.904', 'density': '3.1028', 'melting_point': '265.8', 'boiling_point': '332.0',
         'specific_heat_capacity': '0.474', 'electronegativity': '2.96', 'abundance_in_earth_crust': '2.4',
         'origin': 'primordial', 'phase_at_r_t': 'liquid'},
        {'element': {'atomic_number': '36', 'symbol': 'Kr', 'name': 'Krypton'},
         'origin_of_name': "Greek kryptós 'hidden'", 'group': '18', 'period': '4', 'block': 'p-block',
         'standard_atomic_weight': '83.798', 'density': '0.003749', 'melting_point': '115.79',
         'boiling_point': '119.93', 'specific_heat_capacity': '0.248', 'electronegativity': '3.00',
         'abundance_in_earth_crust': '1×10−4', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '37', 'symbol': 'Rb', 'name': 'Rubidium'},
         'origin_of_name': "Latin rubidus 'deep red'", 'group': '1', 'period': '5', 'block': 's-block',
         'standard_atomic_weight': '85.468', 'density': '1.532', 'melting_point': '312.46', 'boiling_point': '961',
         'specific_heat_capacity': '0.363', 'electronegativity': '0.82', 'abundance_in_earth_crust': '90',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '38', 'symbol': 'Sr', 'name': 'Strontium'},
         'origin_of_name': 'Strontian a village in Scotland where it was found', 'group': '2', 'period': '5',
         'block': 's-block', 'standard_atomic_weight': '87.62', 'density': '2.64', 'melting_point': '1050',
         'boiling_point': '1655', 'specific_heat_capacity': '0.301', 'electronegativity': '0.95',
         'abundance_in_earth_crust': '370', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '39', 'symbol': 'Y', 'name': 'Yttrium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also terbium erbium ytterbium', 'group': '3',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '88.906', 'density': '4.472',
         'melting_point': '1799', 'boiling_point': '3609', 'specific_heat_capacity': '0.298',
         'electronegativity': '1.22', 'abundance_in_earth_crust': '33', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '40', 'symbol': 'Zr', 'name': 'Zirconium'},
         'origin_of_name': "Zircon a mineral from Persian zargun 'gold-hued'", 'group': '4', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '91.224', 'density': '6.52', 'melting_point': '2128',
         'boiling_point': '4682', 'specific_heat_capacity': '0.278', 'electronegativity': '1.33',
         'abundance_in_earth_crust': '165', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '41', 'symbol': 'Nb', 'name': 'Niobium'},
         'origin_of_name': 'Niobe daughter of king Tantalus from Greek mythology; see also tantalum', 'group': '5',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '92.906', 'density': '8.57',
         'melting_point': '2750', 'boiling_point': '5017', 'specific_heat_capacity': '0.265',
         'electronegativity': '1.6', 'abundance_in_earth_crust': '20', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '42', 'symbol': 'Mo', 'name': 'Molybdenum'},
         'origin_of_name': "Greek molýbdaina 'piece of lead' from mólybdos 'lead' due to confusion with lead ore galena (PbS)",
         'group': '6', 'period': '5', 'block': 'd-block', 'standard_atomic_weight': '95.95', 'density': '10.28',
         'melting_point': '2896', 'boiling_point': '4912', 'specific_heat_capacity': '0.251',
         'electronegativity': '2.16', 'abundance_in_earth_crust': '1.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '43', 'symbol': 'Tc', 'name': 'Technetium'},
         'origin_of_name': "Greek tekhnētós 'artificial'", 'group': '7', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '[97][a]', 'density': '11', 'melting_point': '2430', 'boiling_point': '4538',
         'specific_heat_capacity': '–', 'electronegativity': '1.9', 'abundance_in_earth_crust': '~\xa03×10−9',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '44', 'symbol': 'Ru', 'name': 'Ruthenium'},
         'origin_of_name': "New Latin Ruthenia 'Russia'", 'group': '8', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '101.07', 'density': '12.45', 'melting_point': '2607', 'boiling_point': '4423',
         'specific_heat_capacity': '0.238', 'electronegativity': '2.2', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '45', 'symbol': 'Rh', 'name': 'Rhodium'},
         'origin_of_name': "Greek rhodóeis 'rose-coloured' from rhódon 'rose'", 'group': '9', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '102.91', 'density': '12.41', 'melting_point': '2237',
         'boiling_point': '3968', 'specific_heat_capacity': '0.243', 'electronegativity': '2.28',
         'abundance_in_earth_crust': '0.001', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '46', 'symbol': 'Pd', 'name': 'Palladium'},
         'origin_of_name': 'Pallas an asteroid considered a planet at the time', 'group': '10', 'period': '5',
         'block': 'd-block', 'standard_atomic_weight': '106.42', 'density': '12.023', 'melting_point': '1828.05',
         'boiling_point': '3236', 'specific_heat_capacity': '0.244', 'electronegativity': '2.20',
         'abundance_in_earth_crust': '0.015', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '47', 'symbol': 'Ag', 'name': 'Silver'},
         'origin_of_name': 'English word\xa0· \xa0Symbol Ag is derived from Latin argentum', 'group': '11',
         'period': '5', 'block': 'd-block', 'standard_atomic_weight': '107.87', 'density': '10.49',
         'melting_point': '1234.93', 'boiling_point': '2435', 'specific_heat_capacity': '0.235',
         'electronegativity': '1.93', 'abundance_in_earth_crust': '0.075', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '48', 'symbol': 'Cd', 'name': 'Cadmium'},
         'origin_of_name': 'New Latin cadmia from King Kadmos', 'group': '12', 'period': '5', 'block': 'd-block',
         'standard_atomic_weight': '112.41', 'density': '8.65', 'melting_point': '594.22', 'boiling_point': '1040',
         'specific_heat_capacity': '0.232', 'electronegativity': '1.69', 'abundance_in_earth_crust': '0.159',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '49', 'symbol': 'In', 'name': 'Indium'},
         'origin_of_name': "Latin indicum 'indigo' the blue colour found in its spectrum", 'group': '13', 'period': '5',
         'block': 'p-block', 'standard_atomic_weight': '114.82', 'density': '7.31', 'melting_point': '429.75',
         'boiling_point': '2345', 'specific_heat_capacity': '0.233', 'electronegativity': '1.78',
         'abundance_in_earth_crust': '0.25', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '50', 'symbol': 'Sn', 'name': 'Tin'},
         'origin_of_name': 'English word\xa0· \xa0Symbol Sn is derived from Latin stannum', 'group': '14',
         'period': '5', 'block': 'p-block', 'standard_atomic_weight': '118.71', 'density': '7.265',
         'melting_point': '505.08', 'boiling_point': '2875', 'specific_heat_capacity': '0.228',
         'electronegativity': '1.96', 'abundance_in_earth_crust': '2.3', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '51', 'symbol': 'Sb', 'name': 'Antimony'},
         'origin_of_name': "Latin antimonium the origin of which is uncertain: folk etymologies suggest it is derived from Greek antí ('against') + mónos ('alone') or Old French anti-moine 'Monk's bane' but it could plausibly be from or related to Arabic ʾiṯmid 'antimony' reformatted as a Latin word\xa0· \xa0Symbol Sb is derived from Latin stibium 'stibnite'",
         'group': '15', 'period': '5', 'block': 'p-block', 'standard_atomic_weight': '121.76', 'density': '6.697',
         'melting_point': '903.78', 'boiling_point': '1860', 'specific_heat_capacity': '0.207',
         'electronegativity': '2.05', 'abundance_in_earth_crust': '0.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '52', 'symbol': 'Te', 'name': 'Tellurium'},
         'origin_of_name': "Latin tellus 'the ground earth'", 'group': '16', 'period': '5', 'block': 'p-block',
         'standard_atomic_weight': '127.60', 'density': '6.24', 'melting_point': '722.66', 'boiling_point': '1261',
         'specific_heat_capacity': '0.202', 'electronegativity': '2.1', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '53', 'symbol': 'I', 'name': 'Iodine'},
         'origin_of_name': "French iode from Greek ioeidḗs 'violet'", 'group': '17', 'period': '5', 'block': 'p-block',
         'standard_atomic_weight': '126.90', 'density': '4.933', 'melting_point': '386.85', 'boiling_point': '457.4',
         'specific_heat_capacity': '0.214', 'electronegativity': '2.66', 'abundance_in_earth_crust': '0.45',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '54', 'symbol': 'Xe', 'name': 'Xenon'},
         'origin_of_name': "Greek xénon neuter form of xénos 'strange'", 'group': '18', 'period': '5',
         'block': 'p-block', 'standard_atomic_weight': '131.29', 'density': '0.005894', 'melting_point': '161.4',
         'boiling_point': '165.03', 'specific_heat_capacity': '0.158', 'electronegativity': '2.60',
         'abundance_in_earth_crust': '3×10−5', 'origin': 'primordial', 'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '55', 'symbol': 'Cs', 'name': 'Caesium'},
         'origin_of_name': "Latin caesius 'sky-blue'", 'group': '1', 'period': '6', 'block': 's-block',
         'standard_atomic_weight': '132.91', 'density': '1.93', 'melting_point': '301.59', 'boiling_point': '944',
         'specific_heat_capacity': '0.242', 'electronegativity': '0.79', 'abundance_in_earth_crust': '3',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '56', 'symbol': 'Ba', 'name': 'Barium'}, 'origin_of_name': "Greek barýs 'heavy'",
         'group': '2', 'period': '6', 'block': 's-block', 'standard_atomic_weight': '137.33', 'density': '3.51',
         'melting_point': '1000', 'boiling_point': '2170', 'specific_heat_capacity': '0.204',
         'electronegativity': '0.89', 'abundance_in_earth_crust': '425', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '57', 'symbol': 'La', 'name': 'Lanthanum'},
         'origin_of_name': "Greek lanthánein 'to lie hidden'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '138.91', 'density': '6.162', 'melting_point': '1193', 'boiling_point': '3737',
         'specific_heat_capacity': '0.195', 'electronegativity': '1.1', 'abundance_in_earth_crust': '39',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '58', 'symbol': 'Ce', 'name': 'Cerium'},
         'origin_of_name': 'Ceres a dwarf planet considered a planet at the time', 'group': 'n/a', 'period': '6',
         'block': 'f-block', 'standard_atomic_weight': '140.12', 'density': '6.770', 'melting_point': '1068',
         'boiling_point': '3716', 'specific_heat_capacity': '0.192', 'electronegativity': '1.12',
         'abundance_in_earth_crust': '66.5', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '59', 'symbol': 'Pr', 'name': 'Praseodymium'},
         'origin_of_name': "Greek prásios dídymos 'green\xa0twin'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '140.91', 'density': '6.77', 'melting_point': '1208', 'boiling_point': '3793',
         'specific_heat_capacity': '0.193', 'electronegativity': '1.13', 'abundance_in_earth_crust': '9.2',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '60', 'symbol': 'Nd', 'name': 'Neodymium'},
         'origin_of_name': "Greek néos dídymos 'new\xa0twin'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '144.24', 'density': '7.01', 'melting_point': '1297', 'boiling_point': '3347',
         'specific_heat_capacity': '0.19', 'electronegativity': '1.14', 'abundance_in_earth_crust': '41.5',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '61', 'symbol': 'Pm', 'name': 'Promethium'},
         'origin_of_name': 'Prometheus a figure in Greek mythology', 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '[145]', 'density': '7.26', 'melting_point': '1315', 'boiling_point': '3273',
         'specific_heat_capacity': '–', 'electronegativity': '1.13', 'abundance_in_earth_crust': '2×10−19',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '62', 'symbol': 'Sm', 'name': 'Samarium'},
         'origin_of_name': 'Samarskite a mineral named after V. Samarsky-Bykhovets Russian mine official',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '150.36', 'density': '7.52',
         'melting_point': '1345', 'boiling_point': '2067', 'specific_heat_capacity': '0.197',
         'electronegativity': '1.17', 'abundance_in_earth_crust': '7.05', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '63', 'symbol': 'Eu', 'name': 'Europium'}, 'origin_of_name': 'Europe',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '151.96', 'density': '5.244',
         'melting_point': '1099', 'boiling_point': '1802', 'specific_heat_capacity': '0.182',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '2', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '64', 'symbol': 'Gd', 'name': 'Gadolinium'},
         'origin_of_name': 'Gadolinite a mineral named after Johan Gadolin Finnish chemist physicist and mineralogist',
         'group': 'n/a', 'period': '6', 'block': 'f-block', 'standard_atomic_weight': '157.25', 'density': '7.90',
         'melting_point': '1585', 'boiling_point': '3546', 'specific_heat_capacity': '0.236',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '6.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '65', 'symbol': 'Tb', 'name': 'Terbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium erbium ytterbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '158.93', 'density': '8.23',
         'melting_point': '1629', 'boiling_point': '3503', 'specific_heat_capacity': '0.182',
         'electronegativity': '1.2', 'abundance_in_earth_crust': '1.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '66', 'symbol': 'Dy', 'name': 'Dysprosium'},
         'origin_of_name': "Greek dysprósitos 'hard to get'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '162.50', 'density': '8.540', 'melting_point': '1680', 'boiling_point': '2840',
         'specific_heat_capacity': '0.17', 'electronegativity': '1.22', 'abundance_in_earth_crust': '5.2',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '67', 'symbol': 'Ho', 'name': 'Holmium'},
         'origin_of_name': "New Latin Holmia 'Stockholm'", 'group': 'n/a', 'period': '6', 'block': 'f-block',
         'standard_atomic_weight': '164.93', 'density': '8.79', 'melting_point': '1734', 'boiling_point': '2993',
         'specific_heat_capacity': '0.165', 'electronegativity': '1.23', 'abundance_in_earth_crust': '1.3',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '68', 'symbol': 'Er', 'name': 'Erbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium terbium ytterbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '167.26', 'density': '9.066',
         'melting_point': '1802', 'boiling_point': '3141', 'specific_heat_capacity': '0.168',
         'electronegativity': '1.24', 'abundance_in_earth_crust': '3.5', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '69', 'symbol': 'Tm', 'name': 'Thulium'},
         'origin_of_name': 'Thule the ancient name for an unclear northern location', 'group': 'n/a', 'period': '6',
         'block': 'f-block', 'standard_atomic_weight': '168.93', 'density': '9.32', 'melting_point': '1818',
         'boiling_point': '2223', 'specific_heat_capacity': '0.16', 'electronegativity': '1.25',
         'abundance_in_earth_crust': '0.52', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '70', 'symbol': 'Yb', 'name': 'Ytterbium'},
         'origin_of_name': 'Ytterby Sweden where it was found; see also yttrium terbium erbium', 'group': 'n/a',
         'period': '6', 'block': 'f-block', 'standard_atomic_weight': '173.05', 'density': '6.90',
         'melting_point': '1097', 'boiling_point': '1469', 'specific_heat_capacity': '0.155',
         'electronegativity': '1.1', 'abundance_in_earth_crust': '3.2', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '71', 'symbol': 'Lu', 'name': 'Lutetium'},
         'origin_of_name': "Latin Lutetia 'Paris'", 'group': '3', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '174.97', 'density': '9.841', 'melting_point': '1925', 'boiling_point': '3675',
         'specific_heat_capacity': '0.154', 'electronegativity': '1.27', 'abundance_in_earth_crust': '0.8',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '72', 'symbol': 'Hf', 'name': 'Hafnium'},
         'origin_of_name': "New Latin Hafnia 'Copenhagen' (from Danish havn harbour)", 'group': '4', 'period': '6',
         'block': 'd-block', 'standard_atomic_weight': '178.49', 'density': '13.31', 'melting_point': '2506',
         'boiling_point': '4876', 'specific_heat_capacity': '0.144', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '3', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '73', 'symbol': 'Ta', 'name': 'Tantalum'},
         'origin_of_name': 'King Tantalus father of Niobe from Greek mythology; see also niobium', 'group': '5',
         'period': '6', 'block': 'd-block', 'standard_atomic_weight': '180.95', 'density': '16.69',
         'melting_point': '3290', 'boiling_point': '5731', 'specific_heat_capacity': '0.14', 'electronegativity': '1.5',
         'abundance_in_earth_crust': '2', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '74', 'symbol': 'W', 'name': 'Tungsten'},
         'origin_of_name': "Swedish tung sten 'heavy stone'\xa0· \xa0Symbol W is from Wolfram originally from Middle High German wolf-rahm 'wolf's foam' describing the mineral wolframite[5]",
         'group': '6', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '183.84', 'density': '19.25',
         'melting_point': '3695', 'boiling_point': '5828', 'specific_heat_capacity': '0.132',
         'electronegativity': '2.36', 'abundance_in_earth_crust': '1.3', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '75', 'symbol': 'Re', 'name': 'Rhenium'},
         'origin_of_name': "Latin Rhenus 'the Rhine'", 'group': '7', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '186.21', 'density': '21.02', 'melting_point': '3459', 'boiling_point': '5869',
         'specific_heat_capacity': '0.137', 'electronegativity': '1.9', 'abundance_in_earth_crust': '7×10−4',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '76', 'symbol': 'Os', 'name': 'Osmium'}, 'origin_of_name': "Greek osmḗ 'smell'",
         'group': '8', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '190.23', 'density': '22.59',
         'melting_point': '3306', 'boiling_point': '5285', 'specific_heat_capacity': '0.13', 'electronegativity': '2.2',
         'abundance_in_earth_crust': '0.002', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '77', 'symbol': 'Ir', 'name': 'Iridium'},
         'origin_of_name': 'Iris the Greek goddess of the rainbow', 'group': '9', 'period': '6', 'block': 'd-block',
         'standard_atomic_weight': '192.22', 'density': '22.56', 'melting_point': '2719', 'boiling_point': '4701',
         'specific_heat_capacity': '0.131', 'electronegativity': '2.20', 'abundance_in_earth_crust': '0.001',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '78', 'symbol': 'Pt', 'name': 'Platinum'},
         'origin_of_name': "Spanish platina 'little silver' from plata 'silver'", 'group': '10', 'period': '6',
         'block': 'd-block', 'standard_atomic_weight': '195.08', 'density': '21.45', 'melting_point': '2041.4',
         'boiling_point': '4098', 'specific_heat_capacity': '0.133', 'electronegativity': '2.28',
         'abundance_in_earth_crust': '0.005', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '79', 'symbol': 'Au', 'name': 'Gold'},
         'origin_of_name': "English word from the same root as 'yellow'\xa0· \xa0Symbol Au is derived from Latin aurum",
         'group': '11', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '196.97', 'density': '19.3',
         'melting_point': '1337.33', 'boiling_point': '3129', 'specific_heat_capacity': '0.129',
         'electronegativity': '2.54', 'abundance_in_earth_crust': '0.004', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '80', 'symbol': 'Hg', 'name': 'Mercury'},
         'origin_of_name': "Mercury Roman god of commerce communication and luck known for his speed and mobility\xa0· \xa0Symbol Hg is derived from its Latin name hydrargyrum from Greek hydrárgyros 'water-silver'",
         'group': '12', 'period': '6', 'block': 'd-block', 'standard_atomic_weight': '200.59', 'density': '13.534',
         'melting_point': '234.43', 'boiling_point': '629.88', 'specific_heat_capacity': '0.14',
         'electronegativity': '2.00', 'abundance_in_earth_crust': '0.085', 'origin': 'primordial',
         'phase_at_r_t': 'liquid'},
        {'element': {'atomic_number': '81', 'symbol': 'Tl', 'name': 'Thallium'},
         'origin_of_name': "Greek thallós 'green shoot or twig'", 'group': '13', 'period': '6', 'block': 'p-block',
         'standard_atomic_weight': '204.38', 'density': '11.85', 'melting_point': '577', 'boiling_point': '1746',
         'specific_heat_capacity': '0.129', 'electronegativity': '1.62', 'abundance_in_earth_crust': '0.85',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '82', 'symbol': 'Pb', 'name': 'Lead'},
         'origin_of_name': "English word from Proto-Celtic *ɸloudom from a root meaning 'flow'\xa0· \xa0Symbol Pb is derived from Latin plumbum",
         'group': '14', 'period': '6', 'block': 'p-block', 'standard_atomic_weight': '207.2', 'density': '11.34',
         'melting_point': '600.61', 'boiling_point': '2022', 'specific_heat_capacity': '0.129',
         'electronegativity': '1.87 (2+)2.33 (4+)', 'abundance_in_earth_crust': '14', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '83', 'symbol': 'Bi', 'name': 'Bismuth'},
         'origin_of_name': "German Wismut from weiß Masse 'white mass' unless from Arabic", 'group': '15',
         'period': '6', 'block': 'p-block', 'standard_atomic_weight': '208.98', 'density': '9.78',
         'melting_point': '544.7', 'boiling_point': '1837', 'specific_heat_capacity': '0.122',
         'electronegativity': '2.02', 'abundance_in_earth_crust': '0.009', 'origin': 'primordial',
         'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '84', 'symbol': 'Po', 'name': 'Polonium'},
         'origin_of_name': "Latin Polonia 'Poland' home country of Marie Curie", 'group': '16', 'period': '6',
         'block': 'p-block', 'standard_atomic_weight': '[209][a]', 'density': '9.196', 'melting_point': '527',
         'boiling_point': '1235', 'specific_heat_capacity': '–', 'electronegativity': '2.0',
         'abundance_in_earth_crust': '2×10−10', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '85', 'symbol': 'At', 'name': 'Astatine'},
         'origin_of_name': "Greek ástatos 'unstable'", 'group': '17', 'period': '6', 'block': 'p-block',
         'standard_atomic_weight': '[210]', 'density': '(8.91–8.95)', 'melting_point': '575', 'boiling_point': '610',
         'specific_heat_capacity': '–', 'electronegativity': '2.2', 'abundance_in_earth_crust': '3×10−20',
         'origin': 'from decay', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '86', 'symbol': 'Rn', 'name': 'Radon'},
         'origin_of_name': 'Radium emanation originally the name of the isotope Radon-222', 'group': '18',
         'period': '6', 'block': 'p-block', 'standard_atomic_weight': '[222]', 'density': '0.00973',
         'melting_point': '202', 'boiling_point': '211.3', 'specific_heat_capacity': '0.094',
         'electronegativity': '2.2', 'abundance_in_earth_crust': '4×10−13', 'origin': 'from decay',
         'phase_at_r_t': 'gas'},
        {'element': {'atomic_number': '87', 'symbol': 'Fr', 'name': 'Francium'},
         'origin_of_name': 'France home country of discoverer Marguerite Perey', 'group': '1', 'period': '7',
         'block': 's-block', 'standard_atomic_weight': '[223]', 'density': '(2.48)', 'melting_point': '281',
         'boiling_point': '890', 'specific_heat_capacity': '–', 'electronegativity': '>0.79[6]',
         'abundance_in_earth_crust': '~\xa01×10−18', 'origin': 'from decay', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '88', 'symbol': 'Ra', 'name': 'Radium'},
         'origin_of_name': "French radium from Latin radius 'ray'", 'group': '2', 'period': '7', 'block': 's-block',
         'standard_atomic_weight': '[226]', 'density': '5.5', 'melting_point': '973', 'boiling_point': '2010',
         'specific_heat_capacity': '0.094', 'electronegativity': '0.9', 'abundance_in_earth_crust': '9×10−7',
         'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '89', 'symbol': 'Ac', 'name': 'Actinium'}, 'origin_of_name': "Greek aktís 'ray'",
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[227]', 'density': '10',
         'melting_point': '1323', 'boiling_point': '3471', 'specific_heat_capacity': '0.12', 'electronegativity': '1.1',
         'abundance_in_earth_crust': '5.5×10−10', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '90', 'symbol': 'Th', 'name': 'Thorium'},
         'origin_of_name': 'Thor the Scandinavian god of thunder', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '232.04', 'density': '11.7', 'melting_point': '2115', 'boiling_point': '5061',
         'specific_heat_capacity': '0.113', 'electronegativity': '1.3', 'abundance_in_earth_crust': '9.6',
         'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '91', 'symbol': 'Pa', 'name': 'Protactinium'},
         'origin_of_name': "Proto- (from Greek prôtos 'first before') + actinium since actinium is produced through the radioactive decay of protactinium",
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '231.04', 'density': '15.37',
         'melting_point': '1841', 'boiling_point': '4300', 'specific_heat_capacity': '–', 'electronegativity': '1.5',
         'abundance_in_earth_crust': '1.4×10−6', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '92', 'symbol': 'U', 'name': 'Uranium'},
         'origin_of_name': 'Uranus the seventh planet in the Solar System', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '238.03', 'density': '19.1', 'melting_point': '1405.3',
         'boiling_point': '4404', 'specific_heat_capacity': '0.116', 'electronegativity': '1.38',
         'abundance_in_earth_crust': '2.7', 'origin': 'primordial', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '93', 'symbol': 'Np', 'name': 'Neptunium'},
         'origin_of_name': 'Neptune the eighth planet in the Solar System', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[237]', 'density': '20.45', 'melting_point': '917',
         'boiling_point': '4273', 'specific_heat_capacity': '–', 'electronegativity': '1.36',
         'abundance_in_earth_crust': '≤\xa03×10−12', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '94', 'symbol': 'Pu', 'name': 'Plutonium'},
         'origin_of_name': 'Pluto a dwarf planet considered a planet in the Solar System at the time', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[244]', 'density': '19.85',
         'melting_point': '912.5', 'boiling_point': '3501', 'specific_heat_capacity': '–', 'electronegativity': '1.28',
         'abundance_in_earth_crust': '≤\xa03×10−11', 'origin': 'from decay', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '95', 'symbol': 'Am', 'name': 'Americium'},
         'origin_of_name': 'The Americas where the element was first synthesised by analogy with its homologue §\xa0europium',
         'group': 'n/a', 'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[243]', 'density': '12',
         'melting_point': '1449', 'boiling_point': '2880', 'specific_heat_capacity': '–', 'electronegativity': '1.13',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '96', 'symbol': 'Cm', 'name': 'Curium'},
         'origin_of_name': 'Pierre Curie and Marie Curie French physicists and chemists', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[247]', 'density': '13.51', 'melting_point': '1613',
         'boiling_point': '3383', 'specific_heat_capacity': '–', 'electronegativity': '1.28',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '97', 'symbol': 'Bk', 'name': 'Berkelium'},
         'origin_of_name': 'Berkeley California where the element was first synthesised', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[247]', 'density': '14.78', 'melting_point': '1259',
         'boiling_point': '2900', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '98', 'symbol': 'Cf', 'name': 'Californium'},
         'origin_of_name': 'California where the element was first synthesised in the LBNL laboratory', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[251]', 'density': '15.1',
         'melting_point': '1173', 'boiling_point': '(1743)[b]', 'specific_heat_capacity': '–',
         'electronegativity': '1.3', 'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '99', 'symbol': 'Es', 'name': 'Einsteinium'},
         'origin_of_name': 'Albert Einstein German physicist', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '[252]', 'density': '8.84', 'melting_point': '1133', 'boiling_point': '(1269)',
         'specific_heat_capacity': '–', 'electronegativity': '1.3', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'solid'},
        {'element': {'atomic_number': '100', 'symbol': 'Fm', 'name': 'Fermium'},
         'origin_of_name': 'Enrico Fermi Italian physicist', 'group': 'n/a', 'period': '7', 'block': 'f-block',
         'standard_atomic_weight': '[257]', 'density': '(9.7)[b]', 'melting_point': '(1125)[7](1800)[8]',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '101', 'symbol': 'Md', 'name': 'Mendelevium'},
         'origin_of_name': 'Dmitri Mendeleev Russian chemist who proposed the periodic table', 'group': 'n/a',
         'period': '7', 'block': 'f-block', 'standard_atomic_weight': '[258]', 'density': '(10.3)',
         'melting_point': '(1100)', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '102', 'symbol': 'No', 'name': 'Nobelium'},
         'origin_of_name': 'Alfred Nobel Swedish chemist and engineer', 'group': 'n/a', 'period': '7',
         'block': 'f-block', 'standard_atomic_weight': '[259]', 'density': '(9.9)', 'melting_point': '(1100)',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '1.3',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '103', 'symbol': 'Lr', 'name': 'Lawrencium'},
         'origin_of_name': 'Ernest Lawrence American physicist', 'group': '3', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[266]', 'density': '(14.4)', 'melting_point': '(1900)', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '1.3', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '104', 'symbol': 'Rf', 'name': 'Rutherfordium'},
         'origin_of_name': 'Ernest Rutherford chemist and physicist from New Zealand', 'group': '4', 'period': '7',
         'block': 'd-block', 'standard_atomic_weight': '[267]', 'density': '(17)', 'melting_point': '(2400)',
         'boiling_point': '(5800)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '105', 'symbol': 'Db', 'name': 'Dubnium'},
         'origin_of_name': 'Dubna Russia where the element was discovered in the JINR laboratory', 'group': '5',
         'period': '7', 'block': 'd-block', 'standard_atomic_weight': '[268]', 'density': '(21.6)',
         'melting_point': '–', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '106', 'symbol': 'Sg', 'name': 'Seaborgium'},
         'origin_of_name': 'Glenn T. Seaborg American chemist', 'group': '6', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[269]', 'density': '(23–24)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '107', 'symbol': 'Bh', 'name': 'Bohrium'},
         'origin_of_name': 'Niels Bohr Danish physicist', 'group': '7', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[270]', 'density': '(26–27)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '108', 'symbol': 'Hs', 'name': 'Hassium'},
         'origin_of_name': "New Latin Hassia 'Hesse' a state in Germany", 'group': '8', 'period': '7',
         'block': 'd-block', 'standard_atomic_weight': '[269]', 'density': '(27–29)', 'melting_point': '–',
         'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '109', 'symbol': 'Mt', 'name': 'Meitnerium'},
         'origin_of_name': 'Lise Meitner Austrian physicist', 'group': '9', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[278]', 'density': '(27–28)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '110', 'symbol': 'Ds', 'name': 'Darmstadtium'},
         'origin_of_name': 'Darmstadt Germany where the element was first synthesised in the GSI laboratories',
         'group': '10', 'period': '7', 'block': 'd-block', 'standard_atomic_weight': '[281]', 'density': '(26–27)',
         'melting_point': '–', 'boiling_point': '–', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '111', 'symbol': 'Rg', 'name': 'Roentgenium'},
         'origin_of_name': 'Wilhelm Conrad Röntgen German physicist', 'group': '11', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[282]', 'density': '(22–24)', 'melting_point': '–', 'boiling_point': '–',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '112', 'symbol': 'Cn', 'name': 'Copernicium'},
         'origin_of_name': 'Nicolaus Copernicus Polish astronomer', 'group': '12', 'period': '7', 'block': 'd-block',
         'standard_atomic_weight': '[285]', 'density': '(14.0)', 'melting_point': '(283)', 'boiling_point': '(340)[b]',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '113', 'symbol': 'Nh', 'name': 'Nihonium'},
         'origin_of_name': "Japanese Nihon 'Japan' where the element was first synthesised in the Riken laboratories",
         'group': '13', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[286]', 'density': '(16)',
         'melting_point': '(700)', 'boiling_point': '(1400)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '114', 'symbol': 'Fl', 'name': 'Flerovium'},
         'origin_of_name': 'Flerov Laboratory of Nuclear Reactions part of JINR where the element was synthesised; itself named after Georgy Flyorov Russian physicist',
         'group': '14', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[289]', 'density': '(9.928)',
         'melting_point': '(200)[b]', 'boiling_point': '(380)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '115', 'symbol': 'Mc', 'name': 'Moscovium'},
         'origin_of_name': 'Moscow Russia where the element was first synthesised in the JINR laboratories',
         'group': '15', 'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[290]', 'density': '(13.5)',
         'melting_point': '(700)', 'boiling_point': '(1400)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '116', 'symbol': 'Lv', 'name': 'Livermorium'},
         'origin_of_name': 'Lawrence Livermore National Laboratory in Livermore California', 'group': '16',
         'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[293]', 'density': '(12.9)',
         'melting_point': '(700)', 'boiling_point': '(1100)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '117', 'symbol': 'Ts', 'name': 'Tennessine'},
         'origin_of_name': 'Tennessee United States where Oak Ridge National Laboratory is located', 'group': '17',
         'period': '7', 'block': 'p-block', 'standard_atomic_weight': '[294]', 'density': '(7.1–7.3)',
         'melting_point': '(700)', 'boiling_point': '(883)', 'specific_heat_capacity': '–', 'electronegativity': '–',
         'abundance_in_earth_crust': '–', 'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
        {'element': {'atomic_number': '118', 'symbol': 'Og', 'name': 'Oganesson'},
         'origin_of_name': 'Yuri Oganessian Russian physicist', 'group': '18', 'period': '7', 'block': 'p-block',
         'standard_atomic_weight': '[294]', 'density': '(6.6–7.4)', 'melting_point': '(325)', 'boiling_point': '(450)',
         'specific_heat_capacity': '–', 'electronegativity': '–', 'abundance_in_earth_crust': '–',
         'origin': 'synthetic', 'phase_at_r_t': 'unknown phase'},
    ]

    return data
