# Get the list of countries by uranium proven reserves
def get_the_list_of_countries_by_uranium_proven_reserves():
    data = [
        {'country_region': 'Algeria', 'reserves_as_of_2019': '19500', 'historical_production_to_2014': '0'},
        {'country_region': 'Argentina', 'reserves_as_of_2019': '39800', 'historical_production_to_2014': '2582'},
        {'country_region': 'Australia', 'reserves_as_of_2019': '2049400', 'historical_production_to_2014': '194646'},
        {'country_region': 'Belgium', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '686'},
        {'country_region': 'Botswana', 'reserves_as_of_2019': '87200', 'historical_production_to_2014': '0'},
        {'country_region': 'Brazil', 'reserves_as_of_2019': '276800', 'historical_production_to_2014': '4172'},
        {'country_region': 'Bulgaria', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '16364'},
        {'country_region': 'Canada', 'reserves_as_of_2019': '873000', 'historical_production_to_2014': '483957'},
        {'country_region': 'Central African Republic', 'reserves_as_of_2019': '32000',
         'historical_production_to_2014': '0'},
        {'country_region': 'Chad', 'reserves_as_of_2019': '2400', 'historical_production_to_2014': '0'},
        {'country_region': 'Chile', 'reserves_as_of_2019': '1400', 'historical_production_to_2014': '0'},
        {'country_region': 'China', 'reserves_as_of_2019': '269700', 'historical_production_to_2014': '39849'},
        {'country_region': 'Democratic Republic of the Congo', 'reserves_as_of_2019': '2700',
         'historical_production_to_2014': '25600'},
        {'country_region': 'Czech Republic', 'reserves_as_of_2019': '119200',
         'historical_production_to_2014': '111765'},
        {'country_region': 'Egypt', 'reserves_as_of_2019': '1900', 'historical_production_to_2014': '0'},
        {'country_region': 'Finland', 'reserves_as_of_2019': '1200', 'historical_production_to_2014': '30'},
        {'country_region': 'France', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '76006'},
        {'country_region': 'Gabon', 'reserves_as_of_2019': '5800', 'historical_production_to_2014': '25403'},
        {'country_region': 'Germany', 'reserves_as_of_2019': '7000', 'historical_production_to_2014': '219686'},
        {'country_region': 'Greece', 'reserves_as_of_2019': '7000', 'historical_production_to_2014': '0'},
        {'country_region': 'Denmark (Greenland)', 'reserves_as_of_2019': '114000',
         'historical_production_to_2014': '0'},
        {'country_region': 'Hungary', 'reserves_as_of_2019': '13500', 'historical_production_to_2014': '21067'},
        {'country_region': 'India', 'reserves_as_of_2019': '129000', 'historical_production_to_2014': '11398'},
        {'country_region': 'Indonesia', 'reserves_as_of_2019': '8400', 'historical_production_to_2014': '0'},
        {'country_region': 'Iran', 'reserves_as_of_2019': '7500', 'historical_production_to_2014': '0'},
        {'country_region': 'Italy', 'reserves_as_of_2019': '6100', 'historical_production_to_2014': '0'},
        {'country_region': 'Japan', 'reserves_as_of_2019': '6600', 'historical_production_to_2014': '84'},
        {'country_region': 'Jordan', 'reserves_as_of_2019': '52500', 'historical_production_to_2014': '0'},
        {'country_region': 'Kazakhstan', 'reserves_as_of_2019': '969200', 'historical_production_to_2014': '244707'},
        {'country_region': 'Madagascar', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '785'},
        {'country_region': 'Malawi', 'reserves_as_of_2019': '14300', 'historical_production_to_2014': '4217'},
        {'country_region': 'Mali', 'reserves_as_of_2019': '8900', 'historical_production_to_2014': '0'},
        {'country_region': 'Mauritania', 'reserves_as_of_2019': '24500', 'historical_production_to_2014': '0'},
        {'country_region': 'Mexico', 'reserves_as_of_2019': '5000', 'historical_production_to_2014': '49'},
        {'country_region': 'Mongolia', 'reserves_as_of_2019': '143500', 'historical_production_to_2014': '535'},
        {'country_region': 'Namibia', 'reserves_as_of_2019': '504200', 'historical_production_to_2014': '120418'},
        {'country_region': 'Niger', 'reserves_as_of_2019': '439400', 'historical_production_to_2014': '132017'},
        {'country_region': 'Pakistan', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '1439'},
        {'country_region': 'Paraguay', 'reserves_as_of_2019': '3600', 'historical_production_to_2014': ''},
        {'country_region': 'Peru', 'reserves_as_of_2019': '33400', 'historical_production_to_2014': '0'},
        {'country_region': 'Poland', 'reserves_as_of_2019': '0', 'historical_production_to_2014': '650'},
        {'country_region': 'Portugal', 'reserves_as_of_2019': '7000', 'historical_production_to_2014': '3720'},
        {'country_region': 'Romania', 'reserves_as_of_2019': '6600', 'historical_production_to_2014': '18899'},
        {'country_region': 'Russia', 'reserves_as_of_2019': '661900', 'historical_production_to_2014': '158844'},
        {'country_region': 'Senegal', 'reserves_as_of_2019': '1100', 'historical_production_to_2014': ''},
        {'country_region': 'Slovakia', 'reserves_as_of_2019': '15500', 'historical_production_to_2014': '211'},
        {'country_region': 'Slovenia', 'reserves_as_of_2019': '9200', 'historical_production_to_2014': '382'},
        {'country_region': 'Somalia', 'reserves_as_of_2019': '7600', 'historical_production_to_2014': '0'},
        {'country_region': 'South Africa', 'reserves_as_of_2019': '447700', 'historical_production_to_2014': '159510'},
        {'country_region': 'Spain', 'reserves_as_of_2019': '28500', 'historical_production_to_2014': '8028'},
        {'country_region': 'Sweden', 'reserves_as_of_2019': '9600', 'historical_production_to_2014': '200'},
        {'country_region': 'Tanzania', 'reserves_as_of_2019': '58200', 'historical_production_to_2014': '0'},
        {'country_region': 'Turkey', 'reserves_as_of_2019': '13600', 'historical_production_to_2014': '0'},
        {'country_region': 'Ukraine', 'reserves_as_of_2019': '186900', 'historical_production_to_2014': '129804'},
        {'country_region': 'United States', 'reserves_as_of_2019': '101900', 'historical_production_to_2014': '373075'},
        {'country_region': 'Uzbekistan', 'reserves_as_of_2019': '132300', 'historical_production_to_2014': '127591'},
        {'country_region': 'Vietnam', 'reserves_as_of_2019': '3900', 'historical_production_to_2014': '0'},
        {'country_region': 'Zambia', 'reserves_as_of_2019': '31000', 'historical_production_to_2014': '86'},
        {'country_region': 'Zimbabwe', 'reserves_as_of_2019': '1400', 'historical_production_to_2014': '0'},
    ]

    return data


# Get the list of countries by uranium consumption
def get_the_list_of_countries_by_uranium_consumption():
    data = [
        {'rank': '1', 'country_region': 'United States', 'uranium_consumption_in_2015_in_1000_metric_tons': '18.69'},
        {'rank': '2', 'country_region': 'France', 'uranium_consumption_in_2015_in_1000_metric_tons': '9.23'},
        {'rank': '3', 'country_region': 'China', 'uranium_consumption_in_2015_in_1000_metric_tons': '8.16'},
        {'rank': '4', 'country_region': 'South Korea', 'uranium_consumption_in_2015_in_1000_metric_tons': '5.02'},
        {'rank': '5', 'country_region': 'Russia', 'uranium_consumption_in_2015_in_1000_metric_tons': '4.21'},
        {'rank': '6', 'country_region': 'Japan', 'uranium_consumption_in_2015_in_1000_metric_tons': '2.55'},
        {'rank': '7', 'country_region': 'Ukraine', 'uranium_consumption_in_2015_in_1000_metric_tons': '2.37'},
        {'rank': '8', 'country_region': 'Germany', 'uranium_consumption_in_2015_in_1000_metric_tons': '1.89'},
        {'rank': '9', 'country_region': 'Canada', 'uranium_consumption_in_2015_in_1000_metric_tons': '1.78'},
        {'rank': '10', 'country_region': 'United Kingdom', 'uranium_consumption_in_2015_in_1000_metric_tons': '1.74'},
    ]

    return data


# Get the list of countries by uranium production
def get_the_list_of_countries_by_uranium_production():
    data = [
        {'rank': '', 'country_region': 'World', 'uranium_production_in_2018_in_tonnes': '53498',
         'percentage_of_world_production_in_2018': '100.00'},
        {'rank': '1', 'country_region': ' Kazakhstan', 'uranium_production_in_2018_in_tonnes': '21705',
         'percentage_of_world_production_in_2018': '40.57'},
        {'rank': '2', 'country_region': ' Canada', 'uranium_production_in_2018_in_tonnes': '7001',
         'percentage_of_world_production_in_2018': '13.09'},
        {'rank': '3', 'country_region': ' Australia', 'uranium_production_in_2018_in_tonnes': '6517',
         'percentage_of_world_production_in_2018': '12.18'},
        {'rank': '4', 'country_region': ' Namibia', 'uranium_production_in_2018_in_tonnes': '5525',
         'percentage_of_world_production_in_2018': '10.33'},
        {'rank': '5', 'country_region': ' Niger', 'uranium_production_in_2018_in_tonnes': '2911',
         'percentage_of_world_production_in_2018': '5.44'},
        {'rank': '6', 'country_region': ' Russia', 'uranium_production_in_2018_in_tonnes': '2904',
         'percentage_of_world_production_in_2018': '5.43'},
        {'rank': '7', 'country_region': ' Uzbekistan', 'uranium_production_in_2018_in_tonnes': '2404',
         'percentage_of_world_production_in_2018': '4.49'},
        {'rank': '8', 'country_region': ' China', 'uranium_production_in_2018_in_tonnes': '1885',
         'percentage_of_world_production_in_2018': '3.52'},
        {'rank': '9', 'country_region': ' Ukraine', 'uranium_production_in_2018_in_tonnes': '1180',
         'percentage_of_world_production_in_2018': '2.21'},
        {'rank': '10', 'country_region': ' United States', 'uranium_production_in_2018_in_tonnes': '582',
         'percentage_of_world_production_in_2018': '1.09'},
        {'rank': '11', 'country_region': ' India', 'uranium_production_in_2018_in_tonnes': '308',
         'percentage_of_world_production_in_2018': '0.79 '},
        {'rank': '12', 'country_region': ' South Africa', 'uranium_production_in_2018_in_tonnes': '346',
         'percentage_of_world_production_in_2018': '0.65'},
        {'rank': '13', 'country_region': ' Iran', 'uranium_production_in_2018_in_tonnes': '71',
         'percentage_of_world_production_in_2018': '0.13'},
        {'rank': '14', 'country_region': ' Pakistan', 'uranium_production_in_2018_in_tonnes': '45',
         'percentage_of_world_production_in_2018': '0.08'},
        {'rank': '15', 'country_region': ' Czech Republic', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
        {'rank': '16', 'country_region': ' Romania', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
        {'rank': '17', 'country_region': ' Brazil', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
        {'rank': '18', 'country_region': ' France', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
        {'rank': '19', 'country_region': 'Germany', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
        {'rank': '20', 'country_region': ' Malawi', 'uranium_production_in_2018_in_tonnes': '0',
         'percentage_of_world_production_in_2018': '0.01'},
    ]

    return data


# Get the list of countries by uranium imports
def get_the_list_of_countries_by_uranium_imports():
    data = [
        {'reporter': 'India', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '169873.11', 'quantity': '2972520', 'quantity_unit': 'kg'},
        {'reporter': 'United States', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '73077.69', 'quantity': '875035', 'quantity_unit': 'kg'},
        {'reporter': 'Congo Dem. Rep.', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '7.36', 'quantity': '275', 'quantity_unit': 'kg'},
        {'reporter': 'Canada', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '4.08', 'quantity': '270', 'quantity_unit': 'kg'},
        {'reporter': 'European Union', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '3.16', 'quantity': '1', 'quantity_unit': 'kg'},
        {'reporter': 'Italy', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '3.04', 'quantity': '1', 'quantity_unit': 'kg'},
        {'reporter': 'Mozambique', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '2.15', 'quantity': '9', 'quantity_unit': 'kg'},
        {'reporter': 'Namibia', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '2.13', 'quantity': '33', 'quantity_unit': 'kg'},
        {'reporter': 'Indonesia', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '1.55', 'quantity': '45', 'quantity_unit': 'kg'},
        {'reporter': 'Luxembourg', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '0.28', 'quantity': '17', 'quantity_unit': 'kg'},
        {'reporter': 'South Africa', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '0.17', 'quantity': '2041', 'quantity_unit': 'kg'},
        {'reporter': 'United Kingdom', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '0.15', 'quantity': '1', 'quantity_unit': 'kg'},
        {'reporter': 'Slovenia', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '0.13', 'quantity': '0', 'quantity_unit': 'kg'},
        {'reporter': 'Latvia', 'trade_flow': 'Import', 'product_code': '261210',
         'product_description': 'Uranium ores and concentrates', 'year': '2019', 'partner': ' World',
         'trade_value_in_thousand_usd': '0.12', 'quantity': '1', 'quantity_unit': 'kg'},
    ]

    return data


# Get the list of countries by uranium exports
def get_the_list_of_countries_by_uranium_exports():
    data = [
        {'country_region': 'Kazakhstan', 'value_worth_of_natural_uranium_in_2021': ' US$1.1 billion ',
         'percentage_of_global_exports': '33.7'},
        {'country_region': 'Canada', 'value_worth_of_natural_uranium_in_2021': ' $954.7 million ',
         'percentage_of_global_exports': '30.1'},
        {'country_region': 'Namibia', 'value_worth_of_natural_uranium_in_2021': ' $535.5 million ',
         'percentage_of_global_exports': '16.9'},
        {'country_region': 'Niger', 'value_worth_of_natural_uranium_in_2021': ' $252.1 million ',
         'percentage_of_global_exports': '8'},
        {'country_region': 'United States', 'value_worth_of_natural_uranium_in_2021': ' $210.8 million ',
         'percentage_of_global_exports': '6.7'},
        {'country_region': 'France', 'value_worth_of_natural_uranium_in_2021': ' $59.7 million ',
         'percentage_of_global_exports': '1.9'},
        {'country_region': 'United Kingdom', 'value_worth_of_natural_uranium_in_2021': ' $33.4 million ',
         'percentage_of_global_exports': '1.06'},
        {'country_region': 'Ukraine', 'value_worth_of_natural_uranium_in_2021': ' $33.0 million ',
         'percentage_of_global_exports': '1.04'},
        {'country_region': 'South Africa', 'value_worth_of_natural_uranium_in_2021': ' $12.2 million ',
         'percentage_of_global_exports': '0.4'},
        {'country_region': 'Czech Republic', 'value_worth_of_natural_uranium_in_2021': ' $3.1 million ',
         'percentage_of_global_exports': '0.1'},
        {'country_region': 'Germany', 'value_worth_of_natural_uranium_in_2021': ' $2.2 million ',
         'percentage_of_global_exports': '0.069'},
        {'country_region': 'Iran', 'value_worth_of_natural_uranium_in_2021': ' $2.1 million ',
         'percentage_of_global_exports': '0.067'},
        {'country_region': 'Netherlands', 'value_worth_of_natural_uranium_in_2021': ' $165,000 ',
         'percentage_of_global_exports': '0.005'},
        {'country_region': 'Sweden', 'value_worth_of_natural_uranium_in_2021': ' $43,000 ',
         'percentage_of_global_exports': '0.001'},
        {'country_region': 'Egypt', 'value_worth_of_natural_uranium_in_2021': ' $28,000 ',
         'percentage_of_global_exports': '0.0009'},
    ]

    return data
