# Get the list of countries by coal proven reserves
def get_the_list_of_countries_by_coal_proven_reserves():
    data = [
        {'rank': '1', 'country_region': 'United States', 'anthracite_and_bituminous_in_tonnes': '220167',
         'anthracite_and_bituminous_in_percentage': '30', 'subbituminous_and_lignite_in_tonnes': '30052',
         'subbituminous_and_lignite_in_percentage': '9.4', 'total_in_tonnes': '250219', 'total_in_percentage': '24'},
        {'rank': '2', 'country_region': 'Russia', 'anthracite_and_bituminous_in_tonnes': '69634',
         'anthracite_and_bituminous_in_percentage': '9.5', 'subbituminous_and_lignite_in_tonnes': '90730',
         'subbituminous_and_lignite_in_percentage': '28.4', 'total_in_tonnes': '160364', 'total_in_percentage': '15'},
        {'rank': '3', 'country_region': 'Australia', 'anthracite_and_bituminous_in_tonnes': '70927',
         'anthracite_and_bituminous_in_percentage': '9.7', 'subbituminous_and_lignite_in_tonnes': '76508',
         'subbituminous_and_lignite_in_percentage': '23.9', 'total_in_tonnes': '147435', 'total_in_percentage': '14'},
        {'rank': '4', 'country_region': 'China', 'anthracite_and_bituminous_in_tonnes': '130851',
         'anthracite_and_bituminous_in_percentage': '17.8', 'subbituminous_and_lignite_in_tonnes': '7968',
         'subbituminous_and_lignite_in_percentage': '2.5', 'total_in_tonnes': '138819', 'total_in_percentage': '13'},
        {'rank': '5', 'country_region': 'India', 'anthracite_and_bituminous_in_tonnes': '96468',
         'anthracite_and_bituminous_in_percentage': '13.1', 'subbituminous_and_lignite_in_tonnes': '4895',
         'subbituminous_and_lignite_in_percentage': '1.5', 'total_in_tonnes': '101363', 'total_in_percentage': '10'},
        {'rank': '6', 'country_region': 'Indonesia', 'anthracite_and_bituminous_in_tonnes': '26122',
         'anthracite_and_bituminous_in_percentage': '3.6', 'subbituminous_and_lignite_in_tonnes': '10878',
         'subbituminous_and_lignite_in_percentage': '3.4', 'total_in_tonnes': '37000', 'total_in_percentage': '4'},
        {'rank': '7', 'country_region': 'Germany', 'anthracite_and_bituminous_in_tonnes': '3',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '36100',
         'subbituminous_and_lignite_in_percentage': '11.3', 'total_in_tonnes': '36103', 'total_in_percentage': '3'},
        {'rank': '8', 'country_region': 'Ukraine', 'anthracite_and_bituminous_in_tonnes': '32039',
         'anthracite_and_bituminous_in_percentage': '4.4', 'subbituminous_and_lignite_in_tonnes': '2336',
         'subbituminous_and_lignite_in_percentage': '0.7', 'total_in_tonnes': '34375', 'total_in_percentage': '3'},
        {'rank': '9', 'country_region': 'Poland', 'anthracite_and_bituminous_in_tonnes': '20542',
         'anthracite_and_bituminous_in_percentage': '2.8', 'subbituminous_and_lignite_in_tonnes': '5937',
         'subbituminous_and_lignite_in_percentage': '1.9', 'total_in_tonnes': '26479', 'total_in_percentage': '3'},
        {'rank': '10', 'country_region': 'Kazakhstan', 'anthracite_and_bituminous_in_tonnes': '25605',
         'anthracite_and_bituminous_in_percentage': '3.5', 'subbituminous_and_lignite_in_tonnes': '0',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '25605', 'total_in_percentage': '2'},
        {'rank': '11', 'country_region': 'Turkey', 'anthracite_and_bituminous_in_tonnes': '551',
         'anthracite_and_bituminous_in_percentage': '0.1', 'subbituminous_and_lignite_in_tonnes': '10975',
         'subbituminous_and_lignite_in_percentage': '3.4', 'total_in_tonnes': '11526', 'total_in_percentage': '1'},
        {'rank': '12', 'country_region': 'South Africa', 'anthracite_and_bituminous_in_tonnes': '9893',
         'anthracite_and_bituminous_in_percentage': '1.3', 'subbituminous_and_lignite_in_tonnes': '0',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '9893', 'total_in_percentage': '1'},
        {'rank': '13', 'country_region': 'New Zealand', 'anthracite_and_bituminous_in_tonnes': '825',
         'anthracite_and_bituminous_in_percentage': '0.1', 'subbituminous_and_lignite_in_tonnes': '6750',
         'subbituminous_and_lignite_in_percentage': '2.1', 'total_in_tonnes': '7575', 'total_in_percentage': '1'},
        {'rank': '14', 'country_region': 'Serbia', 'anthracite_and_bituminous_in_tonnes': '402',
         'anthracite_and_bituminous_in_percentage': '0.1', 'subbituminous_and_lignite_in_tonnes': '7112',
         'subbituminous_and_lignite_in_percentage': '2.2', 'total_in_tonnes': '7514', 'total_in_percentage': '1'},
        {'rank': '15', 'country_region': 'Brazil', 'anthracite_and_bituminous_in_tonnes': '1547',
         'anthracite_and_bituminous_in_percentage': '0.2', 'subbituminous_and_lignite_in_tonnes': '5049',
         'subbituminous_and_lignite_in_percentage': '1.6', 'total_in_tonnes': '6596', 'total_in_percentage': '1'},
        {'rank': '16', 'country_region': 'Canada', 'anthracite_and_bituminous_in_tonnes': '4346',
         'anthracite_and_bituminous_in_percentage': '0.6', 'subbituminous_and_lignite_in_tonnes': '2236',
         'subbituminous_and_lignite_in_percentage': '0.7', 'total_in_tonnes': '6582', 'total_in_percentage': '1'},
        {'rank': '17', 'country_region': 'Colombia', 'anthracite_and_bituminous_in_tonnes': '4881',
         'anthracite_and_bituminous_in_percentage': '0.7', 'subbituminous_and_lignite_in_tonnes': '0',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '4881', 'total_in_percentage': '0'},
        {'rank': '18', 'country_region': 'Pakistan', 'anthracite_and_bituminous_in_tonnes': '207',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '2857',
         'subbituminous_and_lignite_in_percentage': '0.9', 'total_in_tonnes': '3064', 'total_in_percentage': '0'},
        {'rank': '19', 'country_region': 'Vietnam', 'anthracite_and_bituminous_in_tonnes': '3116',
         'anthracite_and_bituminous_in_percentage': '0.4', 'subbituminous_and_lignite_in_tonnes': '244',
         'subbituminous_and_lignite_in_percentage': '0.1', 'total_in_tonnes': '3360', 'total_in_percentage': '0'},
        {'rank': '20', 'country_region': 'Hungary', 'anthracite_and_bituminous_in_tonnes': '276',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '2633',
         'subbituminous_and_lignite_in_percentage': '0.8', 'total_in_tonnes': '2909', 'total_in_percentage': '0'},
        {'rank': '21', 'country_region': 'Greece', 'anthracite_and_bituminous_in_tonnes': '0',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '2876',
         'subbituminous_and_lignite_in_percentage': '0.9', 'total_in_tonnes': '2876', 'total_in_percentage': '0'},
        {'rank': '22', 'country_region': 'Czech Republic', 'anthracite_and_bituminous_in_tonnes': '110',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '2547',
         'subbituminous_and_lignite_in_percentage': '0.8', 'total_in_tonnes': '2657', 'total_in_percentage': '0'},
        {'rank': '23', 'country_region': 'Mongolia', 'anthracite_and_bituminous_in_tonnes': '1170',
         'anthracite_and_bituminous_in_percentage': '0.2', 'subbituminous_and_lignite_in_tonnes': '1350',
         'subbituminous_and_lignite_in_percentage': '0.4', 'total_in_tonnes': '2520', 'total_in_percentage': '0'},
        {'rank': '24', 'country_region': 'Bulgaria', 'anthracite_and_bituminous_in_tonnes': '192',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '2174',
         'subbituminous_and_lignite_in_percentage': '0.7', 'total_in_tonnes': '2366', 'total_in_percentage': '0'},
        {'rank': '25', 'country_region': 'Uzbekistan', 'anthracite_and_bituminous_in_tonnes': '1375',
         'anthracite_and_bituminous_in_percentage': '0.2', 'subbituminous_and_lignite_in_tonnes': '0',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '1375', 'total_in_percentage': '0'},
        {'rank': '26', 'country_region': 'Mexico', 'anthracite_and_bituminous_in_tonnes': '1160',
         'anthracite_and_bituminous_in_percentage': '0.2', 'subbituminous_and_lignite_in_tonnes': '51',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '1211', 'total_in_percentage': '0'},
        {'rank': '27', 'country_region': 'Spain', 'anthracite_and_bituminous_in_tonnes': '868',
         'anthracite_and_bituminous_in_percentage': '0.1', 'subbituminous_and_lignite_in_tonnes': '319',
         'subbituminous_and_lignite_in_percentage': '0.1', 'total_in_tonnes': '1187', 'total_in_percentage': '0'},
        {'rank': '28', 'country_region': 'Thailand', 'anthracite_and_bituminous_in_tonnes': '0',
         'anthracite_and_bituminous_in_percentage': '0', 'subbituminous_and_lignite_in_tonnes': '1063',
         'subbituminous_and_lignite_in_percentage': '0.3', 'total_in_tonnes': '1063', 'total_in_percentage': '0'},
        {'rank': '29', 'country_region': 'Venezuela', 'anthracite_and_bituminous_in_tonnes': '731',
         'anthracite_and_bituminous_in_percentage': '0.1', 'subbituminous_and_lignite_in_tonnes': '0',
         'subbituminous_and_lignite_in_percentage': '0', 'total_in_tonnes': '731', 'total_in_percentage': '0'},
    ]

    return data


# Get the list of countries by coal consumption
def get_the_list_of_countries_by_coal_consumption():
    data = [
        {'country_region': 'China', 'coal_consumption_in_millions_tonnes_in_2008': '2691',
         'coal_consumption_in_millions_tonnes_in_2009': '2892', 'coal_consumption_in_millions_tonnes_in_2010': '3352',
         'coal_consumption_in_millions_tonnes_in_2011': '3677', 'coal_consumption_in_millions_tonnes_in_2012': '4538',
         'coal_consumption_in_millions_tonnes_in_2013': '4678', 'coal_consumption_in_millions_tonnes_in_2014': '4539',
         'coal_consumption_in_millions_tonnes_in_2015': '4411', 'coal_consumption_in_millions_tonnes_in_2016': '4214',
         'share_in_percentage': '51'},
        {'country_region': 'India', 'coal_consumption_in_millions_tonnes_in_2008': '582',
         'coal_consumption_in_millions_tonnes_in_2009': '640', 'coal_consumption_in_millions_tonnes_in_2010': '655',
         'coal_consumption_in_millions_tonnes_in_2011': '715', 'coal_consumption_in_millions_tonnes_in_2012': '841',
         'coal_consumption_in_millions_tonnes_in_2013': '837', 'coal_consumption_in_millions_tonnes_in_2014': '880',
         'coal_consumption_in_millions_tonnes_in_2015': '923', 'coal_consumption_in_millions_tonnes_in_2016': '914',
         'share_in_percentage': '11'},
        {'country_region': 'United States', 'coal_consumption_in_millions_tonnes_in_2008': '1017',
         'coal_consumption_in_millions_tonnes_in_2009': '904', 'coal_consumption_in_millions_tonnes_in_2010': '951',
         'coal_consumption_in_millions_tonnes_in_2011': '910', 'coal_consumption_in_millions_tonnes_in_2012': '889',
         'coal_consumption_in_millions_tonnes_in_2013': '924', 'coal_consumption_in_millions_tonnes_in_2014': '918',
         'coal_consumption_in_millions_tonnes_in_2015': '736', 'coal_consumption_in_millions_tonnes_in_2016': '673',
         'share_in_percentage': '9'},
    ]

    return data


# Get the list of countries by coal production
def get_the_list_of_countries_by_coal_production():
    data = [
        {'country_region': 'China', 'coal_production_in_million_tonnes_in_2020': '3902.0',
         'coal_production_in_million_tonnes_in_2019': '3846.3', 'coal_production_in_million_tonnes_in_2018': '3697.7',
         'coal_production_in_million_tonnes_in_2017': '3523.2', 'coal_production_in_million_tonnes_in_2016': '3411.0',
         'coal_production_in_million_tonnes_in_2015': '3747.0', 'coal_production_in_million_tonnes_in_2014': '3874.0',
         'coal_production_in_million_tonnes_in_2013': '3974.3', 'coal_production_in_million_tonnes_in_2007': '2536.7'},
        {'country_region': 'India', 'coal_production_in_million_tonnes_in_2020': '756.5',
         'coal_production_in_million_tonnes_in_2019': '753.9', 'coal_production_in_million_tonnes_in_2018': '760.4',
         'coal_production_in_million_tonnes_in_2017': '716.0', 'coal_production_in_million_tonnes_in_2016': '692.4',
         'coal_production_in_million_tonnes_in_2015': '677.5', 'coal_production_in_million_tonnes_in_2014': '648.1',
         'coal_production_in_million_tonnes_in_2013': '608.5', 'coal_production_in_million_tonnes_in_2007': '478.2'},
        {'country_region': 'Indonesia', 'coal_production_in_million_tonnes_in_2020': '562.5',
         'coal_production_in_million_tonnes_in_2019': '616.1', 'coal_production_in_million_tonnes_in_2018': '557.8',
         'coal_production_in_million_tonnes_in_2017': '461.0', 'coal_production_in_million_tonnes_in_2016': '434.0',
         'coal_production_in_million_tonnes_in_2015': '392.0', 'coal_production_in_million_tonnes_in_2014': '458.0',
         'coal_production_in_million_tonnes_in_2013': '474.6', 'coal_production_in_million_tonnes_in_2007': '174.8'},
        {'country_region': 'United States', 'coal_production_in_million_tonnes_in_2020': '484.7',
         'coal_production_in_million_tonnes_in_2019': '640.8', 'coal_production_in_million_tonnes_in_2018': '686.0',
         'coal_production_in_million_tonnes_in_2017': '702.3', 'coal_production_in_million_tonnes_in_2016': '660.6',
         'coal_production_in_million_tonnes_in_2015': '812.8', 'coal_production_in_million_tonnes_in_2014': '906.9',
         'coal_production_in_million_tonnes_in_2013': '893.4', 'coal_production_in_million_tonnes_in_2007': '1039.2'},
        {'country_region': 'Australia', 'coal_production_in_million_tonnes_in_2020': '476.7',
         'coal_production_in_million_tonnes_in_2019': '504.1', 'coal_production_in_million_tonnes_in_2018': '502.0',
         'coal_production_in_million_tonnes_in_2017': '481.3', 'coal_production_in_million_tonnes_in_2016': '492.8',
         'coal_production_in_million_tonnes_in_2015': '484.5', 'coal_production_in_million_tonnes_in_2014': '503.2',
         'coal_production_in_million_tonnes_in_2013': '472.8', 'coal_production_in_million_tonnes_in_2007': '393.9'},
        {'country_region': 'Russia', 'coal_production_in_million_tonnes_in_2020': '399.8',
         'coal_production_in_million_tonnes_in_2019': '440.9', 'coal_production_in_million_tonnes_in_2018': '441.6',
         'coal_production_in_million_tonnes_in_2017': '411.2', 'coal_production_in_million_tonnes_in_2016': '385.4',
         'coal_production_in_million_tonnes_in_2015': '373.3', 'coal_production_in_million_tonnes_in_2014': '357.6',
         'coal_production_in_million_tonnes_in_2013': '355.2', 'coal_production_in_million_tonnes_in_2007': '314.2'},
        {'country_region': 'South Africa', 'coal_production_in_million_tonnes_in_2020': '248.3',
         'coal_production_in_million_tonnes_in_2019': '258.4', 'coal_production_in_million_tonnes_in_2018': '250.0',
         'coal_production_in_million_tonnes_in_2017': '252.3', 'coal_production_in_million_tonnes_in_2016': '251.2',
         'coal_production_in_million_tonnes_in_2015': '252.1', 'coal_production_in_million_tonnes_in_2014': '260.5',
         'coal_production_in_million_tonnes_in_2013': '256.3', 'coal_production_in_million_tonnes_in_2007': '269.4'},
        {'country_region': 'Kazakhstan', 'coal_production_in_million_tonnes_in_2020': '113.2',
         'coal_production_in_million_tonnes_in_2019': '115.0', 'coal_production_in_million_tonnes_in_2018': '118.5',
         'coal_production_in_million_tonnes_in_2017': '111.1', 'coal_production_in_million_tonnes_in_2016': '102.4',
         'coal_production_in_million_tonnes_in_2015': '106.5', 'coal_production_in_million_tonnes_in_2014': '108.7',
         'coal_production_in_million_tonnes_in_2013': '119.6', 'coal_production_in_million_tonnes_in_2007': '94.4'},
        {'country_region': 'Germany', 'coal_production_in_million_tonnes_in_2020': '107.4',
         'coal_production_in_million_tonnes_in_2019': '131.3', 'coal_production_in_million_tonnes_in_2018': '168.8',
         'coal_production_in_million_tonnes_in_2017': '175.1', 'coal_production_in_million_tonnes_in_2016': '176.1',
         'coal_production_in_million_tonnes_in_2015': '183.3', 'coal_production_in_million_tonnes_in_2014': '185.8',
         'coal_production_in_million_tonnes_in_2013': '190.6', 'coal_production_in_million_tonnes_in_2007': '201.9'},
        {'country_region': 'Poland', 'coal_production_in_million_tonnes_in_2020': '100.7',
         'coal_production_in_million_tonnes_in_2019': '112.4', 'coal_production_in_million_tonnes_in_2018': '122.4',
         'coal_production_in_million_tonnes_in_2017': '127.1', 'coal_production_in_million_tonnes_in_2016': '131.1',
         'coal_production_in_million_tonnes_in_2015': '135.5', 'coal_production_in_million_tonnes_in_2014': '137.1',
         'coal_production_in_million_tonnes_in_2013': '142.9', 'coal_production_in_million_tonnes_in_2007': '145.8'},
        {'country_region': 'Turkey', 'coal_production_in_million_tonnes_in_2020': '70.8',
         'coal_production_in_million_tonnes_in_2019': '87.1', 'coal_production_in_million_tonnes_in_2018': '83.9',
         'coal_production_in_million_tonnes_in_2017': '99.8', 'coal_production_in_million_tonnes_in_2016': '70.6',
         'coal_production_in_million_tonnes_in_2015': '58.4', 'coal_production_in_million_tonnes_in_2014': '65.2',
         'coal_production_in_million_tonnes_in_2013': '60.4', 'coal_production_in_million_tonnes_in_2007': '76.6'},
        {'country_region': 'Colombia', 'coal_production_in_million_tonnes_in_2020': '50.6',
         'coal_production_in_million_tonnes_in_2019': '84.3', 'coal_production_in_million_tonnes_in_2018': '84.3',
         'coal_production_in_million_tonnes_in_2017': '89.4', 'coal_production_in_million_tonnes_in_2016': '90.5',
         'coal_production_in_million_tonnes_in_2015': '85.5', 'coal_production_in_million_tonnes_in_2014': '88.6',
         'coal_production_in_million_tonnes_in_2013': '85.5', 'coal_production_in_million_tonnes_in_2007': '71.7'},
        {'country_region': 'Vietnam', 'coal_production_in_million_tonnes_in_2020': '48.6',
         'coal_production_in_million_tonnes_in_2019': '46.4', 'coal_production_in_million_tonnes_in_2018': '42.4',
         'coal_production_in_million_tonnes_in_2017': '38.1', 'coal_production_in_million_tonnes_in_2016': '39.4',
         'coal_production_in_million_tonnes_in_2015': '41.5', 'coal_production_in_million_tonnes_in_2014': '41.2',
         'coal_production_in_million_tonnes_in_2013': '41.1', 'coal_production_in_million_tonnes_in_2007': '41.2'},
        {'country_region': 'Mongolia', 'coal_production_in_million_tonnes_in_2020': '43.1',
         'coal_production_in_million_tonnes_in_2019': '57.1', 'coal_production_in_million_tonnes_in_2018': '54.6',
         'coal_production_in_million_tonnes_in_2017': '49.5', 'coal_production_in_million_tonnes_in_2016': '38.1',
         'coal_production_in_million_tonnes_in_2015': '24.5', 'coal_production_in_million_tonnes_in_2014': '25.3',
         'coal_production_in_million_tonnes_in_2013': '30.1', 'coal_production_in_million_tonnes_in_2007': '9.2'},
        {'country_region': 'Serbia', 'coal_production_in_million_tonnes_in_2020': '39.8',
         'coal_production_in_million_tonnes_in_2019': '39.0', 'coal_production_in_million_tonnes_in_2018': '37.7',
         'coal_production_in_million_tonnes_in_2017': '40.0', 'coal_production_in_million_tonnes_in_2016': '38.4',
         'coal_production_in_million_tonnes_in_2015': '38.1', 'coal_production_in_million_tonnes_in_2014': '29.8',
         'coal_production_in_million_tonnes_in_2013': '40.3', 'coal_production_in_million_tonnes_in_2007': '37.7'},
        {'country_region': 'Canada', 'coal_production_in_million_tonnes_in_2020': '39.6',
         'coal_production_in_million_tonnes_in_2019': '50.6', 'coal_production_in_million_tonnes_in_2018': '55.0',
         'coal_production_in_million_tonnes_in_2017': '59.5', 'coal_production_in_million_tonnes_in_2016': '60.3',
         'coal_production_in_million_tonnes_in_2015': '60.7', 'coal_production_in_million_tonnes_in_2014': '68.8',
         'coal_production_in_million_tonnes_in_2013': '68.4', 'coal_production_in_million_tonnes_in_2007': '69.4'},
        {'country_region': 'Czech Republic', 'coal_production_in_million_tonnes_in_2020': '31.7',
         'coal_production_in_million_tonnes_in_2019': '41.0', 'coal_production_in_million_tonnes_in_2018': '43.8',
         'coal_production_in_million_tonnes_in_2017': '44.9', 'coal_production_in_million_tonnes_in_2016': '46.0',
         'coal_production_in_million_tonnes_in_2015': '46.2', 'coal_production_in_million_tonnes_in_2014': '46.9',
         'coal_production_in_million_tonnes_in_2013': '49.0', 'coal_production_in_million_tonnes_in_2007': '62.6'},
        {'country_region': 'Ukraine', 'coal_production_in_million_tonnes_in_2020': '24.1',
         'coal_production_in_million_tonnes_in_2019': '26.1', 'coal_production_in_million_tonnes_in_2018': '26.8',
         'coal_production_in_million_tonnes_in_2017': '34.2', 'coal_production_in_million_tonnes_in_2016': '41.8',
         'coal_production_in_million_tonnes_in_2015': '38.5', 'coal_production_in_million_tonnes_in_2014': '60.9',
         'coal_production_in_million_tonnes_in_2013': '84.8', 'coal_production_in_million_tonnes_in_2007': '76.3'},
        {'country_region': 'Laos', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '22.5', 'coal_production_in_million_tonnes_in_2018': '17.7',
         'coal_production_in_million_tonnes_in_2017': '14.9', 'coal_production_in_million_tonnes_in_2016': '14.6',
         'coal_production_in_million_tonnes_in_2015': '5.3', 'coal_production_in_million_tonnes_in_2014': '1.3',
         'coal_production_in_million_tonnes_in_2013': '1.1', 'coal_production_in_million_tonnes_in_2007': '0.5'},
        {'country_region': 'North Korea', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '18.8', 'coal_production_in_million_tonnes_in_2018': '18.1',
         'coal_production_in_million_tonnes_in_2017': '21.8', 'coal_production_in_million_tonnes_in_2016': '32.0',
         'coal_production_in_million_tonnes_in_2015': '27.5', 'coal_production_in_million_tonnes_in_2014': '25.7',
         'coal_production_in_million_tonnes_in_2013': '25.6', 'coal_production_in_million_tonnes_in_2007': ''},
        {'country_region': 'Mozambique', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '15.3', 'coal_production_in_million_tonnes_in_2018': '17.5',
         'coal_production_in_million_tonnes_in_2017': '16.6', 'coal_production_in_million_tonnes_in_2016': '7.8',
         'coal_production_in_million_tonnes_in_2015': '7.2', 'coal_production_in_million_tonnes_in_2014': '15.8',
         'coal_production_in_million_tonnes_in_2013': '6.7', 'coal_production_in_million_tonnes_in_2007': ''},
        {'country_region': 'Romania', 'coal_production_in_million_tonnes_in_2020': '15.0',
         'coal_production_in_million_tonnes_in_2019': '21.7', 'coal_production_in_million_tonnes_in_2018': '23.7',
         'coal_production_in_million_tonnes_in_2017': '25.7', 'coal_production_in_million_tonnes_in_2016': '23.2',
         'coal_production_in_million_tonnes_in_2015': '25.5', 'coal_production_in_million_tonnes_in_2014': '23.6',
         'coal_production_in_million_tonnes_in_2013': '24.7', 'coal_production_in_million_tonnes_in_2007': '35.4'},
        {'country_region': 'Greece', 'coal_production_in_million_tonnes_in_2020': '14.0',
         'coal_production_in_million_tonnes_in_2019': '27.4', 'coal_production_in_million_tonnes_in_2018': '36.5',
         'coal_production_in_million_tonnes_in_2017': '37.8', 'coal_production_in_million_tonnes_in_2016': '33.1',
         'coal_production_in_million_tonnes_in_2015': '47.7', 'coal_production_in_million_tonnes_in_2014': '49.3',
         'coal_production_in_million_tonnes_in_2013': '53.9', 'coal_production_in_million_tonnes_in_2007': '62.5'},
        {'country_region': 'Thailand', 'coal_production_in_million_tonnes_in_2020': '13.3',
         'coal_production_in_million_tonnes_in_2019': '14.1', 'coal_production_in_million_tonnes_in_2018': '14.9',
         'coal_production_in_million_tonnes_in_2017': '16.3', 'coal_production_in_million_tonnes_in_2016': '17.0',
         'coal_production_in_million_tonnes_in_2015': '15.2', 'coal_production_in_million_tonnes_in_2014': '18.0',
         'coal_production_in_million_tonnes_in_2013': '18.1', 'coal_production_in_million_tonnes_in_2007': '18.3'},
        {'country_region': 'Philippines', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '12.3', 'coal_production_in_million_tonnes_in_2018': '14.4',
         'coal_production_in_million_tonnes_in_2017': '13.1', 'coal_production_in_million_tonnes_in_2016': '12.3',
         'coal_production_in_million_tonnes_in_2015': '7.8', 'coal_production_in_million_tonnes_in_2014': '10.5',
         'coal_production_in_million_tonnes_in_2013': '7.8', 'coal_production_in_million_tonnes_in_2007': ''},
        {'country_region': 'Bulgaria', 'coal_production_in_million_tonnes_in_2020': '12.3',
         'coal_production_in_million_tonnes_in_2019': '15.4', 'coal_production_in_million_tonnes_in_2018': '30.9',
         'coal_production_in_million_tonnes_in_2017': '34.5', 'coal_production_in_million_tonnes_in_2016': '31.5',
         'coal_production_in_million_tonnes_in_2015': '35.9', 'coal_production_in_million_tonnes_in_2014': '31.3',
         'coal_production_in_million_tonnes_in_2013': '28.6', 'coal_production_in_million_tonnes_in_2007': '30.4'},
        {'country_region': 'Kosovo', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '8.9', 'coal_production_in_million_tonnes_in_2018': '8.5',
         'coal_production_in_million_tonnes_in_2017': '8.4', 'coal_production_in_million_tonnes_in_2016': '9.7',
         'coal_production_in_million_tonnes_in_2015': '9.1', 'coal_production_in_million_tonnes_in_2014': '7.9',
         'coal_production_in_million_tonnes_in_2013': '9.1', 'coal_production_in_million_tonnes_in_2007': ''},
        {'country_region': 'Pakistan', 'coal_production_in_million_tonnes_in_2020': '7.7',
         'coal_production_in_million_tonnes_in_2019': '6.8', 'coal_production_in_million_tonnes_in_2018': '4.4',
         'coal_production_in_million_tonnes_in_2017': '4.0', 'coal_production_in_million_tonnes_in_2016': '3.3',
         'coal_production_in_million_tonnes_in_2015': '3.4', 'coal_production_in_million_tonnes_in_2014': '3.0',
         'coal_production_in_million_tonnes_in_2013': '3.0', 'coal_production_in_million_tonnes_in_2007': '3.6'},
        {'country_region': 'Bosnia and Herzegovina', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '7.2', 'coal_production_in_million_tonnes_in_2018': '7.7',
         'coal_production_in_million_tonnes_in_2017': '7.9', 'coal_production_in_million_tonnes_in_2016': '7.2',
         'coal_production_in_million_tonnes_in_2015': '6.7', 'coal_production_in_million_tonnes_in_2014': '6.8',
         'coal_production_in_million_tonnes_in_2013': '6.9', 'coal_production_in_million_tonnes_in_2007': '13.9'},
        {'country_region': 'Mexico', 'coal_production_in_million_tonnes_in_2020': '6.5',
         'coal_production_in_million_tonnes_in_2019': '9.8', 'coal_production_in_million_tonnes_in_2018': '11.9',
         'coal_production_in_million_tonnes_in_2017': '10.4', 'coal_production_in_million_tonnes_in_2016': '11.4',
         'coal_production_in_million_tonnes_in_2015': '14.4', 'coal_production_in_million_tonnes_in_2014': '13.8',
         'coal_production_in_million_tonnes_in_2013': '14.6', 'coal_production_in_million_tonnes_in_2007': '12.2'},
        {'country_region': 'Brazil', 'coal_production_in_million_tonnes_in_2020': '6.2',
         'coal_production_in_million_tonnes_in_2019': '5.8', 'coal_production_in_million_tonnes_in_2018': '6.4',
         'coal_production_in_million_tonnes_in_2017': '7.0', 'coal_production_in_million_tonnes_in_2016': '8.1',
         'coal_production_in_million_tonnes_in_2015': '8.0', 'coal_production_in_million_tonnes_in_2014': '7.9',
         'coal_production_in_million_tonnes_in_2013': '8.6', 'coal_production_in_million_tonnes_in_2007': '5.9'},
        {'country_region': 'Hungary', 'coal_production_in_million_tonnes_in_2020': '6.1',
         'coal_production_in_million_tonnes_in_2019': '6.8', 'coal_production_in_million_tonnes_in_2018': '7.9',
         'coal_production_in_million_tonnes_in_2017': '8.0', 'coal_production_in_million_tonnes_in_2016': '9.3',
         'coal_production_in_million_tonnes_in_2015': '9.6', 'coal_production_in_million_tonnes_in_2014': '0.1',
         'coal_production_in_million_tonnes_in_2013': '9.6', 'coal_production_in_million_tonnes_in_2007': '9.8'},
        {'country_region': 'North Macedonia', 'coal_production_in_million_tonnes_in_2020': '',
         'coal_production_in_million_tonnes_in_2019': '6.0', 'coal_production_in_million_tonnes_in_2018': '5.5',
         'coal_production_in_million_tonnes_in_2017': '5.6', 'coal_production_in_million_tonnes_in_2016': '5.7',
         'coal_production_in_million_tonnes_in_2015': '6.5', 'coal_production_in_million_tonnes_in_2014': '7.9',
         'coal_production_in_million_tonnes_in_2013': '7.4', 'coal_production_in_million_tonnes_in_2007': ''},
    ]

    return data


# Get the list of countries by coal imports
def get_the_list_of_countries_by_coal_imports():
    data = [
        {'country_region': 'China', 'imports_of_coal_in_millions_tonnes_in_2008': '281'},
        {'country_region': 'India', 'imports_of_coal_in_millions_tonnes_in_2008': '223'},
        {'country_region': 'Japan', 'imports_of_coal_in_millions_tonnes_in_2008': '189'},
        {'country_region': 'South Korea', 'imports_of_coal_in_millions_tonnes_in_2008': '149'},
        {'country_region': 'Taiwan', 'imports_of_coal_in_millions_tonnes_in_2008': '76'},
        {'country_region': 'Germany', 'imports_of_coal_in_millions_tonnes_in_2008': '44'},
        {'country_region': 'Netherlands', 'imports_of_coal_in_millions_tonnes_in_2008': '44'},
        {'country_region': 'Turkey', 'imports_of_coal_in_millions_tonnes_in_2008': '38'},
        {'country_region': 'Malaysia', 'imports_of_coal_in_millions_tonnes_in_2008': '34'},
        {'country_region': 'Thailand', 'imports_of_coal_in_millions_tonnes_in_2008': '25'},
    ]

    return data


# Get the list of countries by coal exports
def get_the_list_of_countries_by_coal_exports():
    data = [
        {'country_region': 'Indonesia', 'exports_of_coal_in_millions_tonnes_in_2008': '472'},
        {'country_region': 'Australia', 'exports_of_coal_in_millions_tonnes_in_2008': '426'},
        {'country_region': 'Russia', 'exports_of_coal_in_millions_tonnes_in_2008': '231'},
        {'country_region': 'United States', 'exports_of_coal_in_millions_tonnes_in_2008': '115'},
        {'country_region': 'Colombia', 'exports_of_coal_in_millions_tonnes_in_2008': '92'},
        {'country_region': 'South Africa', 'exports_of_coal_in_millions_tonnes_in_2008': '88'},
        {'country_region': 'Mongolia', 'exports_of_coal_in_millions_tonnes_in_2008': '39'},
        {'country_region': 'Canada', 'exports_of_coal_in_millions_tonnes_in_2008': '37'},
        {'country_region': 'Mozambique', 'exports_of_coal_in_millions_tonnes_in_2008': '16'},
    ]

    return data
